// Generated by CIRCT firtool-1.139.0
module AguUnit(
  input         clock,
                reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [31:0] io_in_bits_pc,
                io_in_bits_inst,
  input  [11:0] io_in_bits_aluOp,
  input  [6:0]  io_in_bits_mduOp,
  input  [8:0]  io_in_bits_brType,
  input  [31:0] io_in_bits_imm,
  input         io_in_bits_src1IsPC,
                io_in_bits_src2IsImm,
                io_in_bits_src2IsFour,
  input  [4:0]  io_in_bits_src1_addr,
                io_in_bits_src2_addr,
  input  [31:0] io_in_bits_src1_value,
                io_in_bits_src2_value,
  input         io_in_bits_resFromMulDiv,
                io_in_bits_memWe,
  input  [7:0]  io_in_bits_lsOp,
  input         io_in_bits_resFromMem,
                io_in_bits_regWriteEn,
  input  [4:0]  io_in_bits_destReg,
  input         io_in_bits_hasException,
  input  [5:0]  io_in_bits_ecode,
  input  [8:0]  io_in_bits_esubcode,
  input         io_in_bits_isCsr,
                io_in_bits_csrWe,
  input  [13:0] io_in_bits_csrNum,
  input         io_in_bits_inst_ertn,
                io_in_bits_rdtimel,
                io_in_bits_rdtimeh,
  input  [4:0]  io_in_bits_tlbOp,
                io_in_bits_invtlb_op,
  input         io_in_bits_is_refetch,
                io_in_bits_is_cacop,
  input  [4:0]  io_in_bits_cacop_op,
                io_in_bits_rob_idx,
  input         io_in_bits_src1_read,
                io_in_bits_src2_read,
  input  [5:0]  io_in_bits_pdest,
                io_in_bits_old_pdest,
                io_in_bits_psrc1,
                io_in_bits_psrc2,
  input         io_in_bits_is_branch,
  input  [1:0]  io_in_bits_branch_tag,
  input  [3:0]  io_in_bits_branch_mask,
                io_in_bits_lsq_idx,
  input         io_in_bits_pred_taken,
  input  [31:0] io_in_bits_pred_target,
  input  [1:0]  io_in_bits_bpu_type,
  input  [9:0]  io_in_bits_ghr,
  input  [3:0]  io_in_bits_ras_tos,
  input         io_out_ready,
  output        io_out_valid,
  output [31:0] io_out_bits_pc,
                io_out_bits_inst,
  output [11:0] io_out_bits_aluOp,
  output [6:0]  io_out_bits_mduOp,
  output [8:0]  io_out_bits_brType,
  output [31:0] io_out_bits_imm,
  output        io_out_bits_src1IsPC,
                io_out_bits_src2IsImm,
                io_out_bits_src2IsFour,
  output [4:0]  io_out_bits_src1_addr,
                io_out_bits_src2_addr,
  output [31:0] io_out_bits_src1_value,
                io_out_bits_src2_value,
  output        io_out_bits_resFromMulDiv,
                io_out_bits_memWe,
  output [7:0]  io_out_bits_lsOp,
  output        io_out_bits_resFromMem,
                io_out_bits_regWriteEn,
  output [4:0]  io_out_bits_destReg,
  output [31:0] io_out_bits_ex_result,
                io_out_bits_aux_data,
  output        io_out_bits_hasException,
  output [5:0]  io_out_bits_ecode,
  output [8:0]  io_out_bits_esubcode,
  output        io_out_bits_isCsr,
                io_out_bits_csrWe,
  output [13:0] io_out_bits_csrNum,
  output        io_out_bits_inst_ertn,
                io_out_bits_rdtimel,
                io_out_bits_rdtimeh,
  output [4:0]  io_out_bits_tlbOp,
                io_out_bits_invtlb_op,
  output        io_out_bits_is_refetch,
                io_out_bits_is_cacop,
  output [4:0]  io_out_bits_cacop_op,
                io_out_bits_rob_idx,
  output        io_out_bits_src1_read,
                io_out_bits_src2_read,
  output [5:0]  io_out_bits_pdest,
                io_out_bits_old_pdest,
                io_out_bits_psrc1,
                io_out_bits_psrc2,
  output        io_out_bits_is_branch,
  output [1:0]  io_out_bits_branch_tag,
  output [3:0]  io_out_bits_branch_mask,
                io_out_bits_lsq_idx,
  output        io_out_bits_pred_taken,
  output [31:0] io_out_bits_pred_target,
  output [1:0]  io_out_bits_bpu_type,
  output [9:0]  io_out_bits_ghr,
  output [3:0]  io_out_bits_ras_tos,
  input         io_flush,
                io_br_resolve_in_valid,
                io_br_resolve_in_mispredict,
  input  [1:0]  io_br_resolve_in_tag,
  output [1:0]  io_data_sram_size,
  output [3:0]  io_data_sram_wstrb,
  output [31:0] io_data_sram_addr,
                io_data_sram_wdata,
  output        io_data_uncached,
  input  [1:0]  io_mmu_config_crmd_datm,
  input         io_mmu_config_crmd_pg,
                io_mmu_config_crmd_da,
  input  [1:0]  io_mmu_config_crmd_plv,
  input  [9:0]  io_mmu_config_asid_asid,
  input  [2:0]  io_mmu_config_dmw0_vseg,
                io_mmu_config_dmw0_pseg,
  input  [1:0]  io_mmu_config_dmw0_mat,
  input         io_mmu_config_dmw0_plv3,
                io_mmu_config_dmw0_plv0,
  input  [2:0]  io_mmu_config_dmw1_vseg,
                io_mmu_config_dmw1_pseg,
  input  [1:0]  io_mmu_config_dmw1_mat,
  input         io_mmu_config_dmw1_plv3,
                io_mmu_config_dmw1_plv0,
  input  [18:0] io_mmu_config_tlbehi_vppn,
  output [18:0] io_tlb_s1_vppn,
  output        io_tlb_s1_va_bit12,
  output [9:0]  io_tlb_s1_asid,
  input         io_tlb_s1_found,
  input  [3:0]  io_tlb_s1_index,
  input  [19:0] io_tlb_s1_ppn,
  input  [5:0]  io_tlb_s1_ps,
  input  [1:0]  io_tlb_s1_plv,
                io_tlb_s1_mat,
  input         io_tlb_s1_d,
                io_tlb_s1_v,
  output        io_invtlb_valid,
  output [4:0]  io_invtlb_op
);

  reg         valid_reg;
  reg  [31:0] data_reg_pc;
  reg  [31:0] data_reg_inst;
  reg  [11:0] data_reg_aluOp;
  reg  [6:0]  data_reg_mduOp;
  reg  [8:0]  data_reg_brType;
  reg  [31:0] data_reg_imm;
  reg         data_reg_src1IsPC;
  reg         data_reg_src2IsImm;
  reg         data_reg_src2IsFour;
  reg  [4:0]  data_reg_src1_addr;
  reg  [4:0]  data_reg_src2_addr;
  reg  [31:0] data_reg_src1_value;
  reg  [31:0] data_reg_src2_value;
  reg         data_reg_resFromMulDiv;
  reg         data_reg_memWe;
  reg  [7:0]  data_reg_lsOp;
  reg         data_reg_resFromMem;
  reg         data_reg_regWriteEn;
  reg  [4:0]  data_reg_destReg;
  reg         data_reg_hasException;
  reg  [5:0]  data_reg_ecode;
  reg  [8:0]  data_reg_esubcode;
  reg         data_reg_isCsr;
  reg         data_reg_csrWe;
  reg  [13:0] data_reg_csrNum;
  reg         data_reg_inst_ertn;
  reg         data_reg_rdtimel;
  reg         data_reg_rdtimeh;
  reg  [4:0]  data_reg_tlbOp;
  reg  [4:0]  data_reg_invtlb_op;
  reg         data_reg_is_refetch;
  reg         data_reg_is_cacop;
  reg  [4:0]  data_reg_cacop_op;
  reg  [4:0]  data_reg_rob_idx;
  reg         data_reg_src1_read;
  reg         data_reg_src2_read;
  reg  [5:0]  data_reg_pdest;
  reg  [5:0]  data_reg_old_pdest;
  reg  [5:0]  data_reg_psrc1;
  reg  [5:0]  data_reg_psrc2;
  reg         data_reg_is_branch;
  reg  [1:0]  data_reg_branch_tag;
  reg  [3:0]  data_reg_branch_mask;
  reg  [3:0]  data_reg_lsq_idx;
  reg         data_reg_pred_taken;
  reg  [31:0] data_reg_pred_target;
  reg  [1:0]  data_reg_bpu_type;
  reg  [9:0]  data_reg_ghr;
  reg  [3:0]  data_reg_ras_tos;
  wire [6:0]  _clear_mask_T = 7'h1 << io_br_resolve_in_tag;
  wire        current_is_killed =
    valid_reg & io_br_resolve_in_valid & io_br_resolve_in_mispredict
    & (|(_clear_mask_T[3:0] & data_reg_branch_mask));
  wire        real_valid = valid_reg & ~current_is_killed;
  wire [31:0] _va_T =
    (data_reg_src1IsPC ? data_reg_pc : data_reg_src1_value)
    + (data_reg_src2IsImm
         ? data_reg_imm
         : data_reg_src2IsFour ? 32'h4 : data_reg_src2_value);
  wire        is_tlbsrch = data_reg_tlbOp == 5'h1;
  wire        is_invtlb = data_reg_tlbOp == 5'h10;
  wire        _dmw1_hit_T_6 = io_mmu_config_crmd_plv == 2'h0;
  wire        dmw0_hit =
    io_mmu_config_crmd_pg & ~io_mmu_config_crmd_da
    & _va_T[31:29] == io_mmu_config_dmw0_vseg
    & (_dmw1_hit_T_6 & io_mmu_config_dmw0_plv0 | (&io_mmu_config_crmd_plv)
       & io_mmu_config_dmw0_plv3);
  wire        dmw_hit =
    dmw0_hit | io_mmu_config_crmd_pg & ~io_mmu_config_crmd_da
    & _va_T[31:29] == io_mmu_config_dmw1_vseg
    & (_dmw1_hit_T_6 & io_mmu_config_dmw1_plv0 | (&io_mmu_config_crmd_plv)
       & io_mmu_config_dmw1_plv3);
  wire        _raw_tlb_code_T_17 = io_tlb_s1_found & io_tlb_s1_v;
  wire        isWord = data_reg_lsOp == 8'h4 | data_reg_lsOp == 8'h80;
  wire        isHalf =
    data_reg_lsOp == 8'h2 | data_reg_lsOp == 8'h10 | data_reg_lsOp == 8'h40;
  wire        ale =
    (data_reg_resFromMem | data_reg_memWe) & valid_reg
    & (isWord & (|(_va_T[1:0])) | isHalf & _va_T[0]);
  wire        early_is_load = data_reg_resFromMem & valid_reg;
  wire        early_is_store = data_reg_memWe & valid_reg;
  wire        early_hit_inv =
    data_reg_is_cacop & data_reg_cacop_op[4:3] == 2'h2 & valid_reg;
  wire        early_is_mapped =
    io_mmu_config_crmd_pg & ~io_mmu_config_crmd_da & ~dmw_hit
    & (early_is_load | early_is_store | early_hit_inv);
  wire        priv_fault = (&io_mmu_config_crmd_plv) & io_tlb_s1_plv == 2'h0;
  wire [6:0]  stMaskB = 7'h1 << _va_T[1:0];
  wire        allow_in = ~valid_reg | current_is_killed | io_out_ready;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_reg <= 1'h0;
      data_reg_pc <= 32'h0;
      data_reg_inst <= 32'h0;
      data_reg_aluOp <= 12'h0;
      data_reg_mduOp <= 7'h0;
      data_reg_brType <= 9'h0;
      data_reg_imm <= 32'h0;
      data_reg_src1IsPC <= 1'h0;
      data_reg_src2IsImm <= 1'h0;
      data_reg_src2IsFour <= 1'h0;
      data_reg_src1_addr <= 5'h0;
      data_reg_src2_addr <= 5'h0;
      data_reg_src1_value <= 32'h0;
      data_reg_src2_value <= 32'h0;
      data_reg_resFromMulDiv <= 1'h0;
      data_reg_memWe <= 1'h0;
      data_reg_lsOp <= 8'h0;
      data_reg_resFromMem <= 1'h0;
      data_reg_regWriteEn <= 1'h0;
      data_reg_destReg <= 5'h0;
      data_reg_hasException <= 1'h0;
      data_reg_ecode <= 6'h0;
      data_reg_esubcode <= 9'h0;
      data_reg_isCsr <= 1'h0;
      data_reg_csrWe <= 1'h0;
      data_reg_csrNum <= 14'h0;
      data_reg_inst_ertn <= 1'h0;
      data_reg_rdtimel <= 1'h0;
      data_reg_rdtimeh <= 1'h0;
      data_reg_tlbOp <= 5'h0;
      data_reg_invtlb_op <= 5'h0;
      data_reg_is_refetch <= 1'h0;
      data_reg_is_cacop <= 1'h0;
      data_reg_cacop_op <= 5'h0;
      data_reg_rob_idx <= 5'h0;
      data_reg_src1_read <= 1'h0;
      data_reg_src2_read <= 1'h0;
      data_reg_pdest <= 6'h0;
      data_reg_old_pdest <= 6'h0;
      data_reg_psrc1 <= 6'h0;
      data_reg_psrc2 <= 6'h0;
      data_reg_is_branch <= 1'h0;
      data_reg_branch_tag <= 2'h0;
      data_reg_branch_mask <= 4'h0;
      data_reg_lsq_idx <= 4'h0;
      data_reg_pred_taken <= 1'h0;
      data_reg_pred_target <= 32'h0;
      data_reg_bpu_type <= 2'h0;
      data_reg_ghr <= 10'h0;
      data_reg_ras_tos <= 4'h0;
    end
    else begin
      automatic logic _GEN;
      _GEN = io_in_valid & allow_in;
      valid_reg <=
        ~io_flush
        & (allow_in
             ? io_in_valid
               & ~(io_in_valid & io_br_resolve_in_valid & io_br_resolve_in_mispredict
                   & (|(_clear_mask_T[3:0] & io_in_bits_branch_mask)))
             : ~current_is_killed & valid_reg);
      if (_GEN) begin
        data_reg_pc <= io_in_bits_pc;
        data_reg_inst <= io_in_bits_inst;
        data_reg_aluOp <= io_in_bits_aluOp;
        data_reg_mduOp <= io_in_bits_mduOp;
        data_reg_brType <= io_in_bits_brType;
        data_reg_imm <= io_in_bits_imm;
        data_reg_src1IsPC <= io_in_bits_src1IsPC;
        data_reg_src2IsImm <= io_in_bits_src2IsImm;
        data_reg_src2IsFour <= io_in_bits_src2IsFour;
        data_reg_src1_addr <= io_in_bits_src1_addr;
        data_reg_src2_addr <= io_in_bits_src2_addr;
        data_reg_src1_value <= io_in_bits_src1_value;
        data_reg_src2_value <= io_in_bits_src2_value;
        data_reg_resFromMulDiv <= io_in_bits_resFromMulDiv;
        data_reg_memWe <= io_in_bits_memWe;
        data_reg_lsOp <= io_in_bits_lsOp;
        data_reg_resFromMem <= io_in_bits_resFromMem;
        data_reg_regWriteEn <= io_in_bits_regWriteEn;
        data_reg_destReg <= io_in_bits_destReg;
        data_reg_hasException <= io_in_bits_hasException;
        data_reg_ecode <= io_in_bits_ecode;
        data_reg_esubcode <= io_in_bits_esubcode;
        data_reg_isCsr <= io_in_bits_isCsr;
        data_reg_csrWe <= io_in_bits_csrWe;
        data_reg_csrNum <= io_in_bits_csrNum;
        data_reg_inst_ertn <= io_in_bits_inst_ertn;
        data_reg_rdtimel <= io_in_bits_rdtimel;
        data_reg_rdtimeh <= io_in_bits_rdtimeh;
        data_reg_tlbOp <= io_in_bits_tlbOp;
        data_reg_invtlb_op <= io_in_bits_invtlb_op;
        data_reg_is_refetch <= io_in_bits_is_refetch;
        data_reg_is_cacop <= io_in_bits_is_cacop;
        data_reg_cacop_op <= io_in_bits_cacop_op;
        data_reg_rob_idx <= io_in_bits_rob_idx;
        data_reg_src1_read <= io_in_bits_src1_read;
        data_reg_src2_read <= io_in_bits_src2_read;
        data_reg_pdest <= io_in_bits_pdest;
        data_reg_old_pdest <= io_in_bits_old_pdest;
        data_reg_psrc1 <= io_in_bits_psrc1;
        data_reg_psrc2 <= io_in_bits_psrc2;
        data_reg_is_branch <= io_in_bits_is_branch;
        data_reg_branch_tag <= io_in_bits_branch_tag;
        data_reg_lsq_idx <= io_in_bits_lsq_idx;
        data_reg_pred_taken <= io_in_bits_pred_taken;
        data_reg_pred_target <= io_in_bits_pred_target;
        data_reg_bpu_type <= io_in_bits_bpu_type;
        data_reg_ghr <= io_in_bits_ghr;
        data_reg_ras_tos <= io_in_bits_ras_tos;
      end
      if (io_br_resolve_in_valid & ~io_br_resolve_in_mispredict)
        data_reg_branch_mask <=
          ~(_clear_mask_T[3:0])
          & (io_in_valid & allow_in ? io_in_bits_branch_mask : data_reg_branch_mask);
      else if (_GEN)
        data_reg_branch_mask <= io_in_bits_branch_mask;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        valid_reg = 1'h0;
        data_reg_pc = 32'h0;
        data_reg_inst = 32'h0;
        data_reg_aluOp = 12'h0;
        data_reg_mduOp = 7'h0;
        data_reg_brType = 9'h0;
        data_reg_imm = 32'h0;
        data_reg_src1IsPC = 1'h0;
        data_reg_src2IsImm = 1'h0;
        data_reg_src2IsFour = 1'h0;
        data_reg_src1_addr = 5'h0;
        data_reg_src2_addr = 5'h0;
        data_reg_src1_value = 32'h0;
        data_reg_src2_value = 32'h0;
        data_reg_resFromMulDiv = 1'h0;
        data_reg_memWe = 1'h0;
        data_reg_lsOp = 8'h0;
        data_reg_resFromMem = 1'h0;
        data_reg_regWriteEn = 1'h0;
        data_reg_destReg = 5'h0;
        data_reg_hasException = 1'h0;
        data_reg_ecode = 6'h0;
        data_reg_esubcode = 9'h0;
        data_reg_isCsr = 1'h0;
        data_reg_csrWe = 1'h0;
        data_reg_csrNum = 14'h0;
        data_reg_inst_ertn = 1'h0;
        data_reg_rdtimel = 1'h0;
        data_reg_rdtimeh = 1'h0;
        data_reg_tlbOp = 5'h0;
        data_reg_invtlb_op = 5'h0;
        data_reg_is_refetch = 1'h0;
        data_reg_is_cacop = 1'h0;
        data_reg_cacop_op = 5'h0;
        data_reg_rob_idx = 5'h0;
        data_reg_src1_read = 1'h0;
        data_reg_src2_read = 1'h0;
        data_reg_pdest = 6'h0;
        data_reg_old_pdest = 6'h0;
        data_reg_psrc1 = 6'h0;
        data_reg_psrc2 = 6'h0;
        data_reg_is_branch = 1'h0;
        data_reg_branch_tag = 2'h0;
        data_reg_branch_mask = 4'h0;
        data_reg_lsq_idx = 4'h0;
        data_reg_pred_taken = 1'h0;
        data_reg_pred_target = 32'h0;
        data_reg_bpu_type = 2'h0;
        data_reg_ghr = 10'h0;
        data_reg_ras_tos = 4'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = allow_in;
  assign io_out_valid = valid_reg;
  assign io_out_bits_pc = data_reg_pc;
  assign io_out_bits_inst = data_reg_inst;
  assign io_out_bits_aluOp = data_reg_aluOp;
  assign io_out_bits_mduOp = data_reg_mduOp;
  assign io_out_bits_brType = data_reg_brType;
  assign io_out_bits_imm = data_reg_imm;
  assign io_out_bits_src1IsPC = data_reg_src1IsPC;
  assign io_out_bits_src2IsImm = data_reg_src2IsImm;
  assign io_out_bits_src2IsFour = data_reg_src2IsFour;
  assign io_out_bits_src1_addr = data_reg_src1_addr;
  assign io_out_bits_src2_addr = data_reg_src2_addr;
  assign io_out_bits_src1_value = data_reg_src1_value;
  assign io_out_bits_src2_value = data_reg_src2_value;
  assign io_out_bits_resFromMulDiv = data_reg_resFromMulDiv;
  assign io_out_bits_memWe = data_reg_memWe;
  assign io_out_bits_lsOp = data_reg_lsOp;
  assign io_out_bits_resFromMem = data_reg_resFromMem;
  assign io_out_bits_regWriteEn = data_reg_regWriteEn;
  assign io_out_bits_destReg = data_reg_destReg;
  assign io_out_bits_ex_result =
    is_tlbsrch ? {~io_tlb_s1_found, 27'h0, io_tlb_s1_index} : _va_T;
  assign io_out_bits_aux_data =
    is_tlbsrch ? (io_tlb_s1_found ? 32'h8000000F : 32'h80000000) : 32'h0;
  assign io_out_bits_hasException =
    data_reg_hasException | ale | early_is_mapped
    & (~io_tlb_s1_found | ~io_tlb_s1_v | priv_fault | ~io_tlb_s1_d & early_is_store);
  assign io_out_bits_ecode =
    data_reg_hasException
      ? data_reg_ecode
      : ale
          ? 6'h9
          : early_is_mapped
              ? {6{~io_tlb_s1_found}} | (_raw_tlb_code_T_17 & priv_fault ? 6'h7 : 6'h0)
                | {5'h0, io_tlb_s1_found & ~io_tlb_s1_v & (early_is_load | early_hit_inv)}
                | {4'h0, io_tlb_s1_found & ~io_tlb_s1_v & early_is_store, 1'h0}
                | {3'h0,
                   _raw_tlb_code_T_17 & ~priv_fault & ~io_tlb_s1_d & early_is_store,
                   2'h0}
              : 6'h0;
  assign io_out_bits_esubcode = data_reg_esubcode;
  assign io_out_bits_isCsr = data_reg_isCsr;
  assign io_out_bits_csrWe = data_reg_csrWe;
  assign io_out_bits_csrNum = data_reg_csrNum;
  assign io_out_bits_inst_ertn = data_reg_inst_ertn;
  assign io_out_bits_rdtimel = data_reg_rdtimel;
  assign io_out_bits_rdtimeh = data_reg_rdtimeh;
  assign io_out_bits_tlbOp = data_reg_tlbOp;
  assign io_out_bits_invtlb_op = data_reg_invtlb_op;
  assign io_out_bits_is_refetch = data_reg_is_refetch;
  assign io_out_bits_is_cacop = real_valid & data_reg_is_cacop;
  assign io_out_bits_cacop_op = real_valid ? data_reg_cacop_op : 5'h0;
  assign io_out_bits_rob_idx = data_reg_rob_idx;
  assign io_out_bits_src1_read = data_reg_src1_read;
  assign io_out_bits_src2_read = data_reg_src2_read;
  assign io_out_bits_pdest = data_reg_pdest;
  assign io_out_bits_old_pdest = data_reg_old_pdest;
  assign io_out_bits_psrc1 = data_reg_psrc1;
  assign io_out_bits_psrc2 = data_reg_psrc2;
  assign io_out_bits_is_branch = data_reg_is_branch;
  assign io_out_bits_branch_tag = data_reg_branch_tag;
  assign io_out_bits_branch_mask = data_reg_branch_mask;
  assign io_out_bits_lsq_idx = data_reg_lsq_idx;
  assign io_out_bits_pred_taken = data_reg_pred_taken;
  assign io_out_bits_pred_target = data_reg_pred_target;
  assign io_out_bits_bpu_type = data_reg_bpu_type;
  assign io_out_bits_ghr = data_reg_ghr;
  assign io_out_bits_ras_tos = data_reg_ras_tos;
  assign io_data_sram_size = isWord ? 2'h2 : {1'h0, isHalf};
  assign io_data_sram_wstrb =
    data_reg_memWe & real_valid & ~io_flush
      ? (isWord ? 4'hF : isHalf ? (_va_T[1] ? 4'hC : 4'h3) : stMaskB[3:0])
      : 4'h0;
  assign io_data_sram_addr =
    {data_reg_is_cacop & data_reg_cacop_op[4:3] != 2'h2
       ? _va_T[31:12]
       : io_mmu_config_crmd_da & ~io_mmu_config_crmd_pg
           ? _va_T[31:12]
           : dmw_hit
               ? {dmw0_hit ? io_mmu_config_dmw0_pseg : io_mmu_config_dmw1_pseg,
                  _va_T[28:12]}
               : _raw_tlb_code_T_17
                   ? (io_tlb_s1_ps == 6'hC
                        ? io_tlb_s1_ppn
                        : {io_tlb_s1_ppn[19:9], _va_T[20:12]})
                   : _va_T[31:12],
     _va_T[11:0]};
  assign io_data_sram_wdata =
    isWord
      ? data_reg_src2_value
      : isHalf ? {2{data_reg_src2_value[15:0]}} : {4{data_reg_src2_value[7:0]}};
  assign io_data_uncached =
    (io_mmu_config_crmd_da & ~io_mmu_config_crmd_pg
       ? io_mmu_config_crmd_datm
       : dmw_hit
           ? (dmw0_hit ? io_mmu_config_dmw0_mat : io_mmu_config_dmw1_mat)
           : io_tlb_s1_mat) == 2'h0;
  assign io_tlb_s1_vppn =
    is_invtlb
      ? data_reg_src2_value[31:13]
      : is_tlbsrch ? io_mmu_config_tlbehi_vppn : _va_T[31:13];
  assign io_tlb_s1_va_bit12 = _va_T[12];
  assign io_tlb_s1_asid = is_invtlb ? data_reg_src1_value[9:0] : io_mmu_config_asid_asid;
  assign io_invtlb_valid = is_invtlb & real_valid & ~data_reg_hasException;
  assign io_invtlb_op = data_reg_invtlb_op;
endmodule

