// Generated by CIRCT firtool-1.139.0
module ALU(
  input  [11:0] io_aluOp,
  input  [31:0] io_src1,
                io_src2,
  output [31:0] io_res
);

  wire        adderCin = io_aluOp[1] | io_aluOp[2] | io_aluOp[3];
  wire [32:0] _adderRes_T_1 =
    {1'h0, io_src1} + {1'h0, {32{adderCin}} ^ io_src2} + {32'h0, adderCin};
  wire [62:0] sllRes = {31'h0, io_src1} << io_src2[4:0];
  wire [31:0] _GEN = {27'h0, io_src2[4:0]};
  wire [31:0] _io_res_T_3 = io_src1 | io_src2;
  assign io_res =
    (io_aluOp[0] | io_aluOp[1] ? _adderRes_T_1[31:0] : 32'h0)
    | (io_aluOp[2]
         ? {31'h0,
            io_src1[31] & ~(io_src2[31]) | io_src1[31] == io_src2[31] & _adderRes_T_1[31]}
         : 32'h0) | (io_aluOp[3] ? {31'h0, ~(_adderRes_T_1[32])} : 32'h0)
    | (io_aluOp[4] ? io_src1 & io_src2 : 32'h0) | (io_aluOp[5] ? ~_io_res_T_3 : 32'h0)
    | (io_aluOp[6] ? _io_res_T_3 : 32'h0) | (io_aluOp[7] ? io_src1 ^ io_src2 : 32'h0)
    | (io_aluOp[8] ? sllRes[31:0] : 32'h0) | (io_aluOp[9] ? io_src1 >> _GEN : 32'h0)
    | (io_aluOp[10] ? $signed($signed(io_src1) >>> _GEN) : 32'h0)
    | (io_aluOp[11] ? io_src2 : 32'h0);
endmodule

