// Generated by CIRCT firtool-1.139.0
module AluSimpleUnit(
  input         clock,
                reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [31:0] io_in_bits_pc,
  input  [12:0] io_in_bits_aluOp,
  input  [31:0] io_in_bits_imm,
  input         io_in_bits_src1IsPC,
                io_in_bits_src2IsImm,
                io_in_bits_src2IsFour,
  input  [31:0] io_in_bits_src1_value,
                io_in_bits_src2_value,
  input         io_in_bits_memWe,
                io_in_bits_resFromMem,
                io_in_bits_regWriteEn,
  input  [31:0] io_in_bits_aux_data,
  input         io_in_bits_hasException,
  input  [5:0]  io_in_bits_ecode,
  input         io_in_bits_isCsr,
                io_in_bits_csrWe,
  input  [13:0] io_in_bits_csrNum,
  input         io_in_bits_inst_ertn,
  input  [4:0]  io_in_bits_tlbOp,
  input         io_in_bits_is_refetch,
                io_in_bits_is_cacop,
  input  [4:0]  io_in_bits_rob_idx,
  input  [5:0]  io_in_bits_pdest,
  input         io_in_bits_is_branch,
  input  [3:0]  io_in_bits_branch_mask,
  input  [9:0]  io_in_bits_ghr,
  input         io_in_bits_br_actual_taken,
  input  [1:0]  io_in_bits_br_type,
  input         io_in_bits_bimodal_pred,
                io_in_bits_gshare_pred,
                io_out_ready,
  output        io_out_valid,
  output [31:0] io_out_bits_pc,
                io_out_bits_src2_value,
  output        io_out_bits_memWe,
                io_out_bits_resFromMem,
                io_out_bits_regWriteEn,
  output [31:0] io_out_bits_ex_result,
                io_out_bits_aux_data,
  output        io_out_bits_hasException,
  output [5:0]  io_out_bits_ecode,
  output        io_out_bits_isCsr,
                io_out_bits_csrWe,
  output [13:0] io_out_bits_csrNum,
  output        io_out_bits_inst_ertn,
  output [4:0]  io_out_bits_tlbOp,
  output        io_out_bits_is_refetch,
                io_out_bits_is_cacop,
  output [4:0]  io_out_bits_rob_idx,
  output [5:0]  io_out_bits_pdest,
  output        io_out_bits_is_branch,
  output [9:0]  io_out_bits_ghr,
  output        io_out_bits_br_actual_taken,
  output [1:0]  io_out_bits_br_type,
  output        io_out_bits_bimodal_pred,
                io_out_bits_gshare_pred,
  input         io_flush,
                io_br_resolve_in_valid,
                io_br_resolve_in_mispredict,
  input  [1:0]  io_br_resolve_in_tag
);

  wire        br_fail = io_br_resolve_in_valid & io_br_resolve_in_mispredict;
  wire [6:0]  br_tag_bit = 7'h1 << io_br_resolve_in_tag;
  reg         valid_reg;
  reg  [31:0] data_reg_pc;
  reg  [12:0] data_reg_aluOp;
  reg  [31:0] data_reg_imm;
  reg         data_reg_src1IsPC;
  reg         data_reg_src2IsImm;
  reg         data_reg_src2IsFour;
  reg  [31:0] data_reg_src1_value;
  reg  [31:0] data_reg_src2_value;
  reg         data_reg_memWe;
  reg         data_reg_resFromMem;
  reg         data_reg_regWriteEn;
  reg  [31:0] data_reg_aux_data;
  reg         data_reg_hasException;
  reg  [5:0]  data_reg_ecode;
  reg         data_reg_isCsr;
  reg         data_reg_csrWe;
  reg  [13:0] data_reg_csrNum;
  reg         data_reg_inst_ertn;
  reg  [4:0]  data_reg_tlbOp;
  reg         data_reg_is_refetch;
  reg         data_reg_is_cacop;
  reg  [4:0]  data_reg_rob_idx;
  reg  [5:0]  data_reg_pdest;
  reg         data_reg_is_branch;
  reg  [3:0]  data_reg_branch_mask;
  reg  [9:0]  data_reg_ghr;
  reg         data_reg_br_actual_taken;
  reg  [1:0]  data_reg_br_type;
  reg         data_reg_bimodal_pred;
  reg         data_reg_gshare_pred;
  wire [3:0]  _GEN = br_tag_bit[3:0] & data_reg_branch_mask;
  wire        active = valid_reg & ~(br_fail & (|_GEN));
  wire        in_ready = ~active | io_out_ready;
  always @(posedge clock) begin
    if (reset) begin
      valid_reg <= 1'h0;
      data_reg_pc <= 32'h0;
      data_reg_aluOp <= 13'h0;
      data_reg_imm <= 32'h0;
      data_reg_src1IsPC <= 1'h0;
      data_reg_src2IsImm <= 1'h0;
      data_reg_src2IsFour <= 1'h0;
      data_reg_src1_value <= 32'h0;
      data_reg_src2_value <= 32'h0;
      data_reg_memWe <= 1'h0;
      data_reg_resFromMem <= 1'h0;
      data_reg_regWriteEn <= 1'h0;
      data_reg_aux_data <= 32'h0;
      data_reg_hasException <= 1'h0;
      data_reg_ecode <= 6'h0;
      data_reg_isCsr <= 1'h0;
      data_reg_csrWe <= 1'h0;
      data_reg_csrNum <= 14'h0;
      data_reg_inst_ertn <= 1'h0;
      data_reg_tlbOp <= 5'h0;
      data_reg_is_refetch <= 1'h0;
      data_reg_is_cacop <= 1'h0;
      data_reg_rob_idx <= 5'h0;
      data_reg_pdest <= 6'h0;
      data_reg_is_branch <= 1'h0;
      data_reg_branch_mask <= 4'h0;
      data_reg_ghr <= 10'h0;
      data_reg_br_actual_taken <= 1'h0;
      data_reg_br_type <= 2'h0;
      data_reg_bimodal_pred <= 1'h0;
      data_reg_gshare_pred <= 1'h0;
    end
    else begin
      automatic logic _GEN_0 = io_flush | ~in_ready;
      valid_reg <=
        ~io_flush
        & (in_ready
             ? io_in_valid & ~(br_fail & (|(br_tag_bit[3:0] & io_in_bits_branch_mask)))
             : ~(br_fail & (|_GEN)) & valid_reg);
      if (_GEN_0) begin
      end
      else begin
        data_reg_pc <= io_in_bits_pc;
        data_reg_aluOp <= io_in_bits_aluOp;
        data_reg_imm <= io_in_bits_imm;
        data_reg_src1IsPC <= io_in_bits_src1IsPC;
        data_reg_src2IsImm <= io_in_bits_src2IsImm;
        data_reg_src2IsFour <= io_in_bits_src2IsFour;
        data_reg_src1_value <= io_in_bits_src1_value;
        data_reg_src2_value <= io_in_bits_src2_value;
        data_reg_memWe <= io_in_bits_memWe;
        data_reg_resFromMem <= io_in_bits_resFromMem;
        data_reg_regWriteEn <= io_in_bits_regWriteEn;
        data_reg_aux_data <= io_in_bits_aux_data;
        data_reg_hasException <= io_in_bits_hasException;
        data_reg_ecode <= io_in_bits_ecode;
        data_reg_isCsr <= io_in_bits_isCsr;
        data_reg_csrWe <= io_in_bits_csrWe;
        data_reg_csrNum <= io_in_bits_csrNum;
        data_reg_inst_ertn <= io_in_bits_inst_ertn;
        data_reg_tlbOp <= io_in_bits_tlbOp;
        data_reg_is_refetch <= io_in_bits_is_refetch;
        data_reg_is_cacop <= io_in_bits_is_cacop;
        data_reg_rob_idx <= io_in_bits_rob_idx;
        data_reg_pdest <= io_in_bits_pdest;
        data_reg_is_branch <= io_in_bits_is_branch;
      end
      if (io_flush) begin
      end
      else begin
        automatic logic [3:0] _GEN_1 =
          {4{io_br_resolve_in_valid & ~io_br_resolve_in_mispredict}} & br_tag_bit[3:0];
        data_reg_branch_mask <=
          in_ready ? ~_GEN_1 & io_in_bits_branch_mask : ~_GEN_1 & data_reg_branch_mask;
      end
      if (_GEN_0) begin
      end
      else begin
        data_reg_ghr <= io_in_bits_ghr;
        data_reg_br_actual_taken <= io_in_bits_br_actual_taken;
        data_reg_br_type <= io_in_bits_br_type;
        data_reg_bimodal_pred <= io_in_bits_bimodal_pred;
        data_reg_gshare_pred <= io_in_bits_gshare_pred;
      end
    end
  end // always @(posedge)
  ALU alu (
    .io_aluOp (data_reg_aluOp),
    .io_src1  (data_reg_src1IsPC ? data_reg_pc : data_reg_src1_value),
    .io_src2
      (data_reg_src2IsImm
         ? data_reg_imm
         : data_reg_src2IsFour ? 32'h4 : data_reg_src2_value),
    .io_res   (io_out_bits_ex_result)
  );
  assign io_in_ready = in_ready;
  assign io_out_valid = active;
  assign io_out_bits_pc = data_reg_pc;
  assign io_out_bits_src2_value = data_reg_src2_value;
  assign io_out_bits_memWe = data_reg_memWe;
  assign io_out_bits_resFromMem = data_reg_resFromMem;
  assign io_out_bits_regWriteEn = data_reg_regWriteEn;
  assign io_out_bits_aux_data = data_reg_aux_data;
  assign io_out_bits_hasException = data_reg_hasException;
  assign io_out_bits_ecode = data_reg_ecode;
  assign io_out_bits_isCsr = data_reg_isCsr;
  assign io_out_bits_csrWe = data_reg_csrWe;
  assign io_out_bits_csrNum = data_reg_csrNum;
  assign io_out_bits_inst_ertn = data_reg_inst_ertn;
  assign io_out_bits_tlbOp = data_reg_tlbOp;
  assign io_out_bits_is_refetch = data_reg_is_refetch;
  assign io_out_bits_is_cacop = data_reg_is_cacop;
  assign io_out_bits_rob_idx = data_reg_rob_idx;
  assign io_out_bits_pdest = data_reg_pdest;
  assign io_out_bits_is_branch = data_reg_is_branch;
  assign io_out_bits_ghr = data_reg_ghr;
  assign io_out_bits_br_actual_taken = data_reg_br_actual_taken;
  assign io_out_bits_br_type = data_reg_br_type;
  assign io_out_bits_bimodal_pred = data_reg_bimodal_pred;
  assign io_out_bits_gshare_pred = data_reg_gshare_pred;
endmodule

