// Generated by CIRCT firtool-1.139.0
module AluUnit(
  input         clock,
                reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [31:0] io_in_bits_pc,
                io_in_bits_inst,
  input  [11:0] io_in_bits_aluOp,
  input  [8:0]  io_in_bits_brType,
  input  [31:0] io_in_bits_imm,
  input         io_in_bits_src1IsPC,
                io_in_bits_src2IsImm,
                io_in_bits_src2IsFour,
  input  [4:0]  io_in_bits_src1_addr,
  input  [31:0] io_in_bits_src1_value,
                io_in_bits_src2_value,
  input         io_in_bits_memWe,
                io_in_bits_resFromMem,
                io_in_bits_regWriteEn,
                io_in_bits_hasException,
  input  [5:0]  io_in_bits_ecode,
  input         io_in_bits_isCsr,
                io_in_bits_csrWe,
  input  [13:0] io_in_bits_csrNum,
  input         io_in_bits_inst_ertn,
                io_in_bits_rdtimel,
                io_in_bits_rdtimeh,
  input  [4:0]  io_in_bits_tlbOp,
  input         io_in_bits_is_refetch,
                io_in_bits_is_cacop,
  input  [4:0]  io_in_bits_rob_idx,
  input  [5:0]  io_in_bits_pdest,
  input         io_in_bits_is_branch,
  input  [1:0]  io_in_bits_branch_tag,
  input  [3:0]  io_in_bits_branch_mask,
  input         io_in_bits_pred_taken,
  input  [31:0] io_in_bits_pred_target,
  input  [9:0]  io_in_bits_ghr,
  input  [3:0]  io_in_bits_ras_tos,
  input         io_out_ready,
  output        io_out_valid,
  output [31:0] io_out_bits_src2_value,
  output        io_out_bits_memWe,
                io_out_bits_resFromMem,
                io_out_bits_regWriteEn,
  output [31:0] io_out_bits_ex_result,
                io_out_bits_aux_data,
  output        io_out_bits_hasException,
  output [5:0]  io_out_bits_ecode,
  output        io_out_bits_isCsr,
                io_out_bits_csrWe,
  output [13:0] io_out_bits_csrNum,
  output        io_out_bits_inst_ertn,
  output [4:0]  io_out_bits_tlbOp,
  output        io_out_bits_is_refetch,
                io_out_bits_is_cacop,
  output [4:0]  io_out_bits_rob_idx,
  output [5:0]  io_out_bits_pdest,
  output        io_branch_req,
  output [31:0] io_branch_pc,
  output        io_br_resolve_valid,
                io_br_resolve_mispredict,
  output [1:0]  io_br_resolve_tag,
  input         io_flush,
  input  [63:0] io_timer_in,
  input         io_br_resolve_in_valid,
                io_br_resolve_in_mispredict,
  input  [1:0]  io_br_resolve_in_tag,
  output [13:0] io_csr_raddr,
  input  [31:0] io_csr_rdata,
  output        io_bpu_update_valid,
  output [31:0] io_bpu_update_bits_pc,
                io_bpu_update_bits_target,
  output        io_bpu_update_bits_taken,
  output [1:0]  io_bpu_update_bits_bpu_type,
  output [9:0]  io_bpu_update_bits_ghr,
  output        io_bpu_update_bits_mispredict,
  output [3:0]  io_bpu_update_bits_ras_tos
);

  wire [31:0] _alu_io_res;
  reg         valid_reg;
  reg  [31:0] data_reg_pc;
  reg  [31:0] data_reg_inst;
  reg  [11:0] data_reg_aluOp;
  reg  [8:0]  data_reg_brType;
  reg  [31:0] data_reg_imm;
  reg         data_reg_src1IsPC;
  reg         data_reg_src2IsImm;
  reg         data_reg_src2IsFour;
  reg  [4:0]  data_reg_src1_addr;
  reg  [31:0] data_reg_src1_value;
  reg  [31:0] data_reg_src2_value;
  reg         data_reg_memWe;
  reg         data_reg_resFromMem;
  reg         data_reg_regWriteEn;
  reg         data_reg_hasException;
  reg  [5:0]  data_reg_ecode;
  reg         data_reg_isCsr;
  reg         data_reg_csrWe;
  reg  [13:0] data_reg_csrNum;
  reg         data_reg_inst_ertn;
  reg         data_reg_rdtimel;
  reg         data_reg_rdtimeh;
  reg  [4:0]  data_reg_tlbOp;
  reg         data_reg_is_refetch;
  reg         data_reg_is_cacop;
  reg  [4:0]  data_reg_rob_idx;
  reg  [5:0]  data_reg_pdest;
  reg         data_reg_is_branch;
  reg  [1:0]  data_reg_branch_tag;
  reg         data_reg_pred_taken;
  reg  [31:0] data_reg_pred_target;
  reg  [9:0]  data_reg_ghr;
  reg  [3:0]  data_reg_ras_tos;
  wire        allow_in = ~valid_reg | io_out_ready;
  wire        _br_base_T = data_reg_brType == 9'h40;
  wire        actual_taken =
    data_reg_brType == 9'h100 | data_reg_brType == 9'h80 | _br_base_T
    | (data_reg_brType == 9'h20
         ? data_reg_src1_value >= data_reg_src2_value
         : data_reg_brType == 9'h10
             ? data_reg_src1_value < data_reg_src2_value
             : data_reg_brType == 9'h8
                 ? $signed(data_reg_src1_value) >= $signed(data_reg_src2_value)
                 : data_reg_brType == 9'h4
                     ? $signed(data_reg_src1_value) < $signed(data_reg_src2_value)
                     : data_reg_brType == 9'h2
                         ? data_reg_src1_value != data_reg_src2_value
                         : data_reg_brType == 9'h1
                           & data_reg_src1_value == data_reg_src2_value);
  wire [31:0] _actual_target_T =
    (_br_base_T ? data_reg_src1_value : data_reg_pc) + data_reg_imm;
  wire        mispredict =
    actual_taken != data_reg_pred_taken | actual_taken
    & _actual_target_T != data_reg_pred_target;
  reg         br_broadcasted;
  wire        do_br_resolve =
    valid_reg & data_reg_is_branch & ~data_reg_hasException & ~br_broadcasted;
  wire        _is_uncond_T_3 = data_reg_inst[31:26] == 6'h13;
  wire        is_call =
    data_reg_inst[31:26] == 6'h15 | _is_uncond_T_3 & data_reg_inst[4:0] == 5'h1;
  wire        is_ret =
    _is_uncond_T_3 & data_reg_inst[9:5] == 5'h1 & data_reg_inst[4:0] == 5'h0;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_reg <= 1'h0;
      data_reg_pc <= 32'h0;
      data_reg_inst <= 32'h0;
      data_reg_aluOp <= 12'h0;
      data_reg_brType <= 9'h0;
      data_reg_imm <= 32'h0;
      data_reg_src1IsPC <= 1'h0;
      data_reg_src2IsImm <= 1'h0;
      data_reg_src2IsFour <= 1'h0;
      data_reg_src1_addr <= 5'h0;
      data_reg_src1_value <= 32'h0;
      data_reg_src2_value <= 32'h0;
      data_reg_memWe <= 1'h0;
      data_reg_resFromMem <= 1'h0;
      data_reg_regWriteEn <= 1'h0;
      data_reg_hasException <= 1'h0;
      data_reg_ecode <= 6'h0;
      data_reg_isCsr <= 1'h0;
      data_reg_csrWe <= 1'h0;
      data_reg_csrNum <= 14'h0;
      data_reg_inst_ertn <= 1'h0;
      data_reg_rdtimel <= 1'h0;
      data_reg_rdtimeh <= 1'h0;
      data_reg_tlbOp <= 5'h0;
      data_reg_is_refetch <= 1'h0;
      data_reg_is_cacop <= 1'h0;
      data_reg_rob_idx <= 5'h0;
      data_reg_pdest <= 6'h0;
      data_reg_is_branch <= 1'h0;
      data_reg_branch_tag <= 2'h0;
      data_reg_pred_taken <= 1'h0;
      data_reg_pred_target <= 32'h0;
      data_reg_ghr <= 10'h0;
      data_reg_ras_tos <= 4'h0;
      br_broadcasted <= 1'h0;
    end
    else begin
      automatic logic [6:0] _clear_mask_T = 7'h1 << io_br_resolve_in_tag;
      valid_reg <=
        ~io_flush
        & (allow_in
             ? io_in_valid
               & ~(io_in_valid & io_br_resolve_in_valid & io_br_resolve_in_mispredict
                   & (|(_clear_mask_T[3:0] & io_in_bits_branch_mask)))
             : valid_reg);
      if (io_in_valid & allow_in) begin
        data_reg_pc <= io_in_bits_pc;
        data_reg_inst <= io_in_bits_inst;
        data_reg_aluOp <= io_in_bits_aluOp;
        data_reg_brType <= io_in_bits_brType;
        data_reg_imm <= io_in_bits_imm;
        data_reg_src1IsPC <= io_in_bits_src1IsPC;
        data_reg_src2IsImm <= io_in_bits_src2IsImm;
        data_reg_src2IsFour <= io_in_bits_src2IsFour;
        data_reg_src1_addr <= io_in_bits_src1_addr;
        data_reg_src1_value <= io_in_bits_src1_value;
        data_reg_src2_value <= io_in_bits_src2_value;
        data_reg_memWe <= io_in_bits_memWe;
        data_reg_resFromMem <= io_in_bits_resFromMem;
        data_reg_regWriteEn <= io_in_bits_regWriteEn;
        data_reg_hasException <= io_in_bits_hasException;
        data_reg_ecode <= io_in_bits_ecode;
        data_reg_isCsr <= io_in_bits_isCsr;
        data_reg_csrWe <= io_in_bits_csrWe;
        data_reg_csrNum <= io_in_bits_csrNum;
        data_reg_inst_ertn <= io_in_bits_inst_ertn;
        data_reg_rdtimel <= io_in_bits_rdtimel;
        data_reg_rdtimeh <= io_in_bits_rdtimeh;
        data_reg_tlbOp <= io_in_bits_tlbOp;
        data_reg_is_refetch <= io_in_bits_is_refetch;
        data_reg_is_cacop <= io_in_bits_is_cacop;
        data_reg_rob_idx <= io_in_bits_rob_idx;
        data_reg_pdest <= io_in_bits_pdest;
        data_reg_is_branch <= io_in_bits_is_branch;
        data_reg_branch_tag <= io_in_bits_branch_tag;
        data_reg_pred_taken <= io_in_bits_pred_taken;
        data_reg_pred_target <= io_in_bits_pred_target;
        data_reg_ghr <= io_in_bits_ghr;
        data_reg_ras_tos <= io_in_bits_ras_tos;
      end
      br_broadcasted <= ~(io_flush | allow_in) & (do_br_resolve | br_broadcasted);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        valid_reg = 1'h0;
        data_reg_pc = 32'h0;
        data_reg_inst = 32'h0;
        data_reg_aluOp = 12'h0;
        data_reg_brType = 9'h0;
        data_reg_imm = 32'h0;
        data_reg_src1IsPC = 1'h0;
        data_reg_src2IsImm = 1'h0;
        data_reg_src2IsFour = 1'h0;
        data_reg_src1_addr = 5'h0;
        data_reg_src1_value = 32'h0;
        data_reg_src2_value = 32'h0;
        data_reg_memWe = 1'h0;
        data_reg_resFromMem = 1'h0;
        data_reg_regWriteEn = 1'h0;
        data_reg_hasException = 1'h0;
        data_reg_ecode = 6'h0;
        data_reg_isCsr = 1'h0;
        data_reg_csrWe = 1'h0;
        data_reg_csrNum = 14'h0;
        data_reg_inst_ertn = 1'h0;
        data_reg_rdtimel = 1'h0;
        data_reg_rdtimeh = 1'h0;
        data_reg_tlbOp = 5'h0;
        data_reg_is_refetch = 1'h0;
        data_reg_is_cacop = 1'h0;
        data_reg_rob_idx = 5'h0;
        data_reg_pdest = 6'h0;
        data_reg_is_branch = 1'h0;
        data_reg_branch_tag = 2'h0;
        data_reg_pred_taken = 1'h0;
        data_reg_pred_target = 32'h0;
        data_reg_ghr = 10'h0;
        data_reg_ras_tos = 4'h0;
        br_broadcasted = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ALU alu (
    .io_aluOp (data_reg_aluOp),
    .io_src1  (data_reg_src1IsPC ? data_reg_pc : data_reg_src1_value),
    .io_src2
      (data_reg_src2IsImm
         ? data_reg_imm
         : data_reg_src2IsFour ? 32'h4 : data_reg_src2_value),
    .io_res   (_alu_io_res)
  );
  assign io_in_ready = allow_in;
  assign io_out_valid = valid_reg;
  assign io_out_bits_src2_value = data_reg_src2_value;
  assign io_out_bits_memWe = data_reg_memWe;
  assign io_out_bits_resFromMem = data_reg_resFromMem;
  assign io_out_bits_regWriteEn = data_reg_regWriteEn;
  assign io_out_bits_ex_result =
    data_reg_rdtimel
      ? io_timer_in[31:0]
      : data_reg_rdtimeh
          ? io_timer_in[63:32]
          : data_reg_isCsr ? io_csr_rdata : _alu_io_res;
  assign io_out_bits_aux_data =
    data_reg_isCsr
      ? (data_reg_src1_addr == 5'h0
           ? 32'h0
           : data_reg_src1_addr == 5'h1 ? 32'hFFFFFFFF : data_reg_src1_value)
      : data_reg_src2_value;
  assign io_out_bits_hasException = data_reg_hasException;
  assign io_out_bits_ecode = data_reg_ecode;
  assign io_out_bits_isCsr = data_reg_isCsr;
  assign io_out_bits_csrWe = data_reg_csrWe;
  assign io_out_bits_csrNum = data_reg_csrNum;
  assign io_out_bits_inst_ertn = data_reg_inst_ertn;
  assign io_out_bits_tlbOp = data_reg_tlbOp;
  assign io_out_bits_is_refetch = data_reg_is_refetch;
  assign io_out_bits_is_cacop = data_reg_is_cacop;
  assign io_out_bits_rob_idx = data_reg_rob_idx;
  assign io_out_bits_pdest = data_reg_pdest;
  assign io_branch_req = do_br_resolve & mispredict;
  assign io_branch_pc = actual_taken ? _actual_target_T : data_reg_pc + 32'h4;
  assign io_br_resolve_valid = do_br_resolve;
  assign io_br_resolve_mispredict = mispredict;
  assign io_br_resolve_tag = data_reg_branch_tag;
  assign io_csr_raddr = data_reg_csrNum;
  assign io_bpu_update_valid = do_br_resolve;
  assign io_bpu_update_bits_pc = data_reg_pc;
  assign io_bpu_update_bits_target = _actual_target_T;
  assign io_bpu_update_bits_taken = actual_taken;
  assign io_bpu_update_bits_bpu_type =
    is_ret
      ? 2'h3
      : is_call
          ? 2'h2
          : {1'h0, data_reg_inst[31:26] == 6'h14 | is_call | is_ret | _is_uncond_T_3};
  assign io_bpu_update_bits_ghr = data_reg_ghr;
  assign io_bpu_update_bits_mispredict = mispredict;
  assign io_bpu_update_bits_ras_tos = data_reg_ras_tos;
endmodule

