// Generated by CIRCT firtool-1.139.0
// VCS coverage exclude_file
module bht_1024x2(
  input  [9:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [1:0] R0_data,
  input  [9:0] R1_addr,
  input        R1_en,
               R1_clk,
  output [1:0] R1_data,
  input  [9:0] R2_addr,
  input        R2_en,
               R2_clk,
  output [1:0] R2_data,
  input  [9:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [1:0] W0_data
);

  reg [1:0] Memory[0:1023];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 2'bx;
  assign R1_data = R1_en ? Memory[R1_addr] : 2'bx;
  assign R2_data = R2_en ? Memory[R2_addr] : 2'bx;
endmodule

