// Generated by CIRCT firtool-1.139.0
// VCS coverage exclude_file
module btb_payload_512x55(
  input  [8:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [54:0] R0_data,
  input  [8:0]  R1_addr,
  input         R1_en,
                R1_clk,
  output [54:0] R1_data,
  input  [8:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [54:0] W0_data
);

  reg [54:0] Memory[0:511];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 55'bx;
  assign R1_data = R1_en ? Memory[R1_addr] : 55'bx;
endmodule

