// Generated by CIRCT firtool-1.139.0
module CdbArbiter(
  output        io_reqs_0_ready,
  input         io_reqs_0_valid,
  input  [31:0] io_reqs_0_bits_pc,
                io_reqs_0_bits_src2_value,
  input         io_reqs_0_bits_memWe,
                io_reqs_0_bits_resFromMem,
                io_reqs_0_bits_regWriteEn,
  input  [31:0] io_reqs_0_bits_ex_result,
                io_reqs_0_bits_aux_data,
  input         io_reqs_0_bits_hasException,
  input  [5:0]  io_reqs_0_bits_ecode,
  input         io_reqs_0_bits_isCsr,
                io_reqs_0_bits_csrWe,
  input  [13:0] io_reqs_0_bits_csrNum,
  input         io_reqs_0_bits_inst_ertn,
  input  [4:0]  io_reqs_0_bits_tlbOp,
  input         io_reqs_0_bits_is_refetch,
                io_reqs_0_bits_is_cacop,
  input  [4:0]  io_reqs_0_bits_rob_idx,
  input  [5:0]  io_reqs_0_bits_pdest,
  input         io_reqs_0_bits_is_branch,
  input  [9:0]  io_reqs_0_bits_ghr,
  input         io_reqs_0_bits_br_actual_taken,
  input  [1:0]  io_reqs_0_bits_br_type,
  output        io_reqs_1_ready,
  input         io_reqs_1_valid,
  input  [31:0] io_reqs_1_bits_pc,
                io_reqs_1_bits_ex_result,
                io_reqs_1_bits_aux_data,
  input         io_reqs_1_bits_hasException,
  input  [5:0]  io_reqs_1_bits_ecode,
  input  [4:0]  io_reqs_1_bits_rob_idx,
  input  [5:0]  io_reqs_1_bits_pdest,
  output        io_reqs_2_ready,
  input         io_reqs_2_valid,
  input  [31:0] io_reqs_2_bits_pc,
                io_reqs_2_bits_src2_value,
  input         io_reqs_2_bits_memWe,
                io_reqs_2_bits_resFromMem,
                io_reqs_2_bits_regWriteEn,
  input  [31:0] io_reqs_2_bits_ex_result,
                io_reqs_2_bits_aux_data,
  input         io_reqs_2_bits_hasException,
  input  [5:0]  io_reqs_2_bits_ecode,
  input         io_reqs_2_bits_isCsr,
                io_reqs_2_bits_csrWe,
  input  [13:0] io_reqs_2_bits_csrNum,
  input         io_reqs_2_bits_inst_ertn,
  input  [4:0]  io_reqs_2_bits_tlbOp,
  input         io_reqs_2_bits_is_refetch,
                io_reqs_2_bits_is_cacop,
  input  [4:0]  io_reqs_2_bits_rob_idx,
  input  [5:0]  io_reqs_2_bits_pdest,
  input         io_reqs_2_bits_is_branch,
  input  [9:0]  io_reqs_2_bits_ghr,
  input         io_reqs_2_bits_br_actual_taken,
  input  [1:0]  io_reqs_2_bits_br_type,
  output        io_reqs_3_ready,
  input         io_reqs_3_valid,
  input  [31:0] io_reqs_3_bits_pc,
                io_reqs_3_bits_src2_value,
  input         io_reqs_3_bits_memWe,
                io_reqs_3_bits_resFromMem,
                io_reqs_3_bits_regWriteEn,
  input  [31:0] io_reqs_3_bits_ex_result,
                io_reqs_3_bits_aux_data,
  input         io_reqs_3_bits_hasException,
  input  [5:0]  io_reqs_3_bits_ecode,
  input         io_reqs_3_bits_isCsr,
                io_reqs_3_bits_csrWe,
  input  [13:0] io_reqs_3_bits_csrNum,
  input         io_reqs_3_bits_inst_ertn,
  input  [4:0]  io_reqs_3_bits_tlbOp,
  input         io_reqs_3_bits_is_refetch,
                io_reqs_3_bits_is_cacop,
  input  [4:0]  io_reqs_3_bits_rob_idx,
  input  [5:0]  io_reqs_3_bits_pdest,
  input         io_reqs_3_bits_is_branch,
  input  [9:0]  io_reqs_3_bits_ghr,
  input         io_reqs_3_bits_br_actual_taken,
  input  [1:0]  io_reqs_3_bits_br_type,
  output        io_reqs_4_ready,
  input         io_reqs_4_valid,
  input  [31:0] io_reqs_4_bits_pc,
                io_reqs_4_bits_src2_value,
  input         io_reqs_4_bits_memWe,
                io_reqs_4_bits_resFromMem,
                io_reqs_4_bits_regWriteEn,
  input  [31:0] io_reqs_4_bits_ex_result,
                io_reqs_4_bits_aux_data,
  input         io_reqs_4_bits_hasException,
  input  [5:0]  io_reqs_4_bits_ecode,
  input         io_reqs_4_bits_isCsr,
                io_reqs_4_bits_csrWe,
  input  [13:0] io_reqs_4_bits_csrNum,
  input         io_reqs_4_bits_inst_ertn,
  input  [4:0]  io_reqs_4_bits_tlbOp,
  input         io_reqs_4_bits_is_refetch,
                io_reqs_4_bits_is_cacop,
  input  [4:0]  io_reqs_4_bits_rob_idx,
  input  [5:0]  io_reqs_4_bits_pdest,
  input         io_reqs_4_bits_is_branch,
  input  [9:0]  io_reqs_4_bits_ghr,
  input         io_reqs_4_bits_br_actual_taken,
  input  [1:0]  io_reqs_4_bits_br_type,
  output        io_cdb0_valid,
  output [31:0] io_cdb0_bits_pc,
                io_cdb0_bits_src2_value,
  output        io_cdb0_bits_memWe,
                io_cdb0_bits_resFromMem,
                io_cdb0_bits_regWriteEn,
  output [31:0] io_cdb0_bits_ex_result,
                io_cdb0_bits_aux_data,
  output        io_cdb0_bits_hasException,
  output [5:0]  io_cdb0_bits_ecode,
  output        io_cdb0_bits_isCsr,
                io_cdb0_bits_csrWe,
  output [13:0] io_cdb0_bits_csrNum,
  output        io_cdb0_bits_inst_ertn,
  output [4:0]  io_cdb0_bits_tlbOp,
  output        io_cdb0_bits_is_refetch,
                io_cdb0_bits_is_cacop,
  output [4:0]  io_cdb0_bits_rob_idx,
  output [5:0]  io_cdb0_bits_pdest,
  output        io_cdb0_bits_is_branch,
  output [9:0]  io_cdb0_bits_ghr,
  output        io_cdb0_bits_br_actual_taken,
  output [1:0]  io_cdb0_bits_br_type,
  output        io_cdb1_valid,
  output [31:0] io_cdb1_bits_pc,
                io_cdb1_bits_src2_value,
  output        io_cdb1_bits_memWe,
                io_cdb1_bits_resFromMem,
                io_cdb1_bits_regWriteEn,
  output [31:0] io_cdb1_bits_ex_result,
                io_cdb1_bits_aux_data,
  output        io_cdb1_bits_hasException,
  output [5:0]  io_cdb1_bits_ecode,
  output        io_cdb1_bits_isCsr,
                io_cdb1_bits_csrWe,
  output [13:0] io_cdb1_bits_csrNum,
  output        io_cdb1_bits_inst_ertn,
  output [4:0]  io_cdb1_bits_tlbOp,
  output        io_cdb1_bits_is_refetch,
                io_cdb1_bits_is_cacop,
  output [4:0]  io_cdb1_bits_rob_idx,
  output [5:0]  io_cdb1_bits_pdest,
  output        io_cdb1_bits_is_branch,
  output [9:0]  io_cdb1_bits_ghr,
  output        io_cdb1_bits_br_actual_taken,
  output [1:0]  io_cdb1_bits_br_type
);

  wire [4:0] req_valids =
    {io_reqs_4_valid, io_reqs_3_valid, io_reqs_2_valid, io_reqs_1_valid, io_reqs_0_valid};
  wire [7:0] _grant0_T =
    8'h1
    << (io_reqs_0_valid
          ? 3'h0
          : io_reqs_1_valid
              ? 3'h1
              : io_reqs_2_valid ? 3'h2 : io_reqs_3_valid ? 3'h3 : 3'h4);
  wire [4:0] grant0 = (|req_valids) ? _grant0_T[4:0] : 5'h0;
  wire [4:0] _GEN = ~grant0 & req_valids;
  wire [7:0] _grant1_T =
    8'h1
    << (_GEN[0]
          ? 3'h0
          : _GEN[1] ? 3'h1 : _GEN[2] ? 3'h2 : _GEN[3] ? 3'h3 : _GEN[4] ? 3'h4 : 3'h7);
  wire [4:0] grant1 = (|_GEN) ? _grant1_T[4:0] : 5'h0;
  assign io_reqs_0_ready = grant0[0] | grant1[0];
  assign io_reqs_1_ready = grant0[1] | grant1[1];
  assign io_reqs_2_ready = grant0[2] | grant1[2];
  assign io_reqs_3_ready = grant0[3] | grant1[3];
  assign io_reqs_4_ready = grant0[4] | grant1[4];
  assign io_cdb0_valid = |req_valids;
  assign io_cdb0_bits_pc =
    (grant0[0] ? io_reqs_0_bits_pc : 32'h0) | (grant0[1] ? io_reqs_1_bits_pc : 32'h0)
    | (grant0[2] ? io_reqs_2_bits_pc : 32'h0) | (grant0[3] ? io_reqs_3_bits_pc : 32'h0)
    | (grant0[4] ? io_reqs_4_bits_pc : 32'h0);
  assign io_cdb0_bits_src2_value =
    (grant0[0] ? io_reqs_0_bits_src2_value : 32'h0)
    | (grant0[2] ? io_reqs_2_bits_src2_value : 32'h0)
    | (grant0[3] ? io_reqs_3_bits_src2_value : 32'h0)
    | (grant0[4] ? io_reqs_4_bits_src2_value : 32'h0);
  assign io_cdb0_bits_memWe =
    grant0[0] & io_reqs_0_bits_memWe | grant0[2] & io_reqs_2_bits_memWe | grant0[3]
    & io_reqs_3_bits_memWe | grant0[4] & io_reqs_4_bits_memWe;
  assign io_cdb0_bits_resFromMem =
    grant0[0] & io_reqs_0_bits_resFromMem | grant0[1] | grant0[2]
    & io_reqs_2_bits_resFromMem | grant0[3] & io_reqs_3_bits_resFromMem | grant0[4]
    & io_reqs_4_bits_resFromMem;
  assign io_cdb0_bits_regWriteEn =
    grant0[0] & io_reqs_0_bits_regWriteEn | grant0[1] | grant0[2]
    & io_reqs_2_bits_regWriteEn | grant0[3] & io_reqs_3_bits_regWriteEn | grant0[4]
    & io_reqs_4_bits_regWriteEn;
  assign io_cdb0_bits_ex_result =
    (grant0[0] ? io_reqs_0_bits_ex_result : 32'h0)
    | (grant0[1] ? io_reqs_1_bits_ex_result : 32'h0)
    | (grant0[2] ? io_reqs_2_bits_ex_result : 32'h0)
    | (grant0[3] ? io_reqs_3_bits_ex_result : 32'h0)
    | (grant0[4] ? io_reqs_4_bits_ex_result : 32'h0);
  assign io_cdb0_bits_aux_data =
    (grant0[0] ? io_reqs_0_bits_aux_data : 32'h0)
    | (grant0[1] ? io_reqs_1_bits_aux_data : 32'h0)
    | (grant0[2] ? io_reqs_2_bits_aux_data : 32'h0)
    | (grant0[3] ? io_reqs_3_bits_aux_data : 32'h0)
    | (grant0[4] ? io_reqs_4_bits_aux_data : 32'h0);
  assign io_cdb0_bits_hasException =
    grant0[0] & io_reqs_0_bits_hasException | grant0[1] & io_reqs_1_bits_hasException
    | grant0[2] & io_reqs_2_bits_hasException | grant0[3] & io_reqs_3_bits_hasException
    | grant0[4] & io_reqs_4_bits_hasException;
  assign io_cdb0_bits_ecode =
    (grant0[0] ? io_reqs_0_bits_ecode : 6'h0) | (grant0[1] ? io_reqs_1_bits_ecode : 6'h0)
    | (grant0[2] ? io_reqs_2_bits_ecode : 6'h0)
    | (grant0[3] ? io_reqs_3_bits_ecode : 6'h0)
    | (grant0[4] ? io_reqs_4_bits_ecode : 6'h0);
  assign io_cdb0_bits_isCsr =
    grant0[0] & io_reqs_0_bits_isCsr | grant0[2] & io_reqs_2_bits_isCsr | grant0[3]
    & io_reqs_3_bits_isCsr | grant0[4] & io_reqs_4_bits_isCsr;
  assign io_cdb0_bits_csrWe =
    grant0[0] & io_reqs_0_bits_csrWe | grant0[2] & io_reqs_2_bits_csrWe | grant0[3]
    & io_reqs_3_bits_csrWe | grant0[4] & io_reqs_4_bits_csrWe;
  assign io_cdb0_bits_csrNum =
    (grant0[0] ? io_reqs_0_bits_csrNum : 14'h0)
    | (grant0[2] ? io_reqs_2_bits_csrNum : 14'h0)
    | (grant0[3] ? io_reqs_3_bits_csrNum : 14'h0)
    | (grant0[4] ? io_reqs_4_bits_csrNum : 14'h0);
  assign io_cdb0_bits_inst_ertn =
    grant0[0] & io_reqs_0_bits_inst_ertn | grant0[2] & io_reqs_2_bits_inst_ertn
    | grant0[3] & io_reqs_3_bits_inst_ertn | grant0[4] & io_reqs_4_bits_inst_ertn;
  assign io_cdb0_bits_tlbOp =
    (grant0[0] ? io_reqs_0_bits_tlbOp : 5'h0) | (grant0[2] ? io_reqs_2_bits_tlbOp : 5'h0)
    | (grant0[3] ? io_reqs_3_bits_tlbOp : 5'h0)
    | (grant0[4] ? io_reqs_4_bits_tlbOp : 5'h0);
  assign io_cdb0_bits_is_refetch =
    grant0[0] & io_reqs_0_bits_is_refetch | grant0[2] & io_reqs_2_bits_is_refetch
    | grant0[3] & io_reqs_3_bits_is_refetch | grant0[4] & io_reqs_4_bits_is_refetch;
  assign io_cdb0_bits_is_cacop =
    grant0[0] & io_reqs_0_bits_is_cacop | grant0[2] & io_reqs_2_bits_is_cacop | grant0[3]
    & io_reqs_3_bits_is_cacop | grant0[4] & io_reqs_4_bits_is_cacop;
  assign io_cdb0_bits_rob_idx =
    (grant0[0] ? io_reqs_0_bits_rob_idx : 5'h0)
    | (grant0[1] ? io_reqs_1_bits_rob_idx : 5'h0)
    | (grant0[2] ? io_reqs_2_bits_rob_idx : 5'h0)
    | (grant0[3] ? io_reqs_3_bits_rob_idx : 5'h0)
    | (grant0[4] ? io_reqs_4_bits_rob_idx : 5'h0);
  assign io_cdb0_bits_pdest =
    (grant0[0] ? io_reqs_0_bits_pdest : 6'h0) | (grant0[1] ? io_reqs_1_bits_pdest : 6'h0)
    | (grant0[2] ? io_reqs_2_bits_pdest : 6'h0)
    | (grant0[3] ? io_reqs_3_bits_pdest : 6'h0)
    | (grant0[4] ? io_reqs_4_bits_pdest : 6'h0);
  assign io_cdb0_bits_is_branch =
    grant0[0] & io_reqs_0_bits_is_branch | grant0[2] & io_reqs_2_bits_is_branch
    | grant0[3] & io_reqs_3_bits_is_branch | grant0[4] & io_reqs_4_bits_is_branch;
  assign io_cdb0_bits_ghr =
    (grant0[0] ? io_reqs_0_bits_ghr : 10'h0) | (grant0[2] ? io_reqs_2_bits_ghr : 10'h0)
    | (grant0[3] ? io_reqs_3_bits_ghr : 10'h0) | (grant0[4] ? io_reqs_4_bits_ghr : 10'h0);
  assign io_cdb0_bits_br_actual_taken =
    grant0[0] & io_reqs_0_bits_br_actual_taken | grant0[2]
    & io_reqs_2_bits_br_actual_taken | grant0[3] & io_reqs_3_bits_br_actual_taken
    | grant0[4] & io_reqs_4_bits_br_actual_taken;
  assign io_cdb0_bits_br_type =
    (grant0[0] ? io_reqs_0_bits_br_type : 2'h0)
    | (grant0[2] ? io_reqs_2_bits_br_type : 2'h0)
    | (grant0[3] ? io_reqs_3_bits_br_type : 2'h0)
    | (grant0[4] ? io_reqs_4_bits_br_type : 2'h0);
  assign io_cdb1_valid = |_GEN;
  assign io_cdb1_bits_pc =
    (grant1[0] ? io_reqs_0_bits_pc : 32'h0) | (grant1[1] ? io_reqs_1_bits_pc : 32'h0)
    | (grant1[2] ? io_reqs_2_bits_pc : 32'h0) | (grant1[3] ? io_reqs_3_bits_pc : 32'h0)
    | (grant1[4] ? io_reqs_4_bits_pc : 32'h0);
  assign io_cdb1_bits_src2_value =
    (grant1[0] ? io_reqs_0_bits_src2_value : 32'h0)
    | (grant1[2] ? io_reqs_2_bits_src2_value : 32'h0)
    | (grant1[3] ? io_reqs_3_bits_src2_value : 32'h0)
    | (grant1[4] ? io_reqs_4_bits_src2_value : 32'h0);
  assign io_cdb1_bits_memWe =
    grant1[0] & io_reqs_0_bits_memWe | grant1[2] & io_reqs_2_bits_memWe | grant1[3]
    & io_reqs_3_bits_memWe | grant1[4] & io_reqs_4_bits_memWe;
  assign io_cdb1_bits_resFromMem =
    grant1[0] & io_reqs_0_bits_resFromMem | grant1[1] | grant1[2]
    & io_reqs_2_bits_resFromMem | grant1[3] & io_reqs_3_bits_resFromMem | grant1[4]
    & io_reqs_4_bits_resFromMem;
  assign io_cdb1_bits_regWriteEn =
    grant1[0] & io_reqs_0_bits_regWriteEn | grant1[1] | grant1[2]
    & io_reqs_2_bits_regWriteEn | grant1[3] & io_reqs_3_bits_regWriteEn | grant1[4]
    & io_reqs_4_bits_regWriteEn;
  assign io_cdb1_bits_ex_result =
    (grant1[0] ? io_reqs_0_bits_ex_result : 32'h0)
    | (grant1[1] ? io_reqs_1_bits_ex_result : 32'h0)
    | (grant1[2] ? io_reqs_2_bits_ex_result : 32'h0)
    | (grant1[3] ? io_reqs_3_bits_ex_result : 32'h0)
    | (grant1[4] ? io_reqs_4_bits_ex_result : 32'h0);
  assign io_cdb1_bits_aux_data =
    (grant1[0] ? io_reqs_0_bits_aux_data : 32'h0)
    | (grant1[1] ? io_reqs_1_bits_aux_data : 32'h0)
    | (grant1[2] ? io_reqs_2_bits_aux_data : 32'h0)
    | (grant1[3] ? io_reqs_3_bits_aux_data : 32'h0)
    | (grant1[4] ? io_reqs_4_bits_aux_data : 32'h0);
  assign io_cdb1_bits_hasException =
    grant1[0] & io_reqs_0_bits_hasException | grant1[1] & io_reqs_1_bits_hasException
    | grant1[2] & io_reqs_2_bits_hasException | grant1[3] & io_reqs_3_bits_hasException
    | grant1[4] & io_reqs_4_bits_hasException;
  assign io_cdb1_bits_ecode =
    (grant1[0] ? io_reqs_0_bits_ecode : 6'h0) | (grant1[1] ? io_reqs_1_bits_ecode : 6'h0)
    | (grant1[2] ? io_reqs_2_bits_ecode : 6'h0)
    | (grant1[3] ? io_reqs_3_bits_ecode : 6'h0)
    | (grant1[4] ? io_reqs_4_bits_ecode : 6'h0);
  assign io_cdb1_bits_isCsr =
    grant1[0] & io_reqs_0_bits_isCsr | grant1[2] & io_reqs_2_bits_isCsr | grant1[3]
    & io_reqs_3_bits_isCsr | grant1[4] & io_reqs_4_bits_isCsr;
  assign io_cdb1_bits_csrWe =
    grant1[0] & io_reqs_0_bits_csrWe | grant1[2] & io_reqs_2_bits_csrWe | grant1[3]
    & io_reqs_3_bits_csrWe | grant1[4] & io_reqs_4_bits_csrWe;
  assign io_cdb1_bits_csrNum =
    (grant1[0] ? io_reqs_0_bits_csrNum : 14'h0)
    | (grant1[2] ? io_reqs_2_bits_csrNum : 14'h0)
    | (grant1[3] ? io_reqs_3_bits_csrNum : 14'h0)
    | (grant1[4] ? io_reqs_4_bits_csrNum : 14'h0);
  assign io_cdb1_bits_inst_ertn =
    grant1[0] & io_reqs_0_bits_inst_ertn | grant1[2] & io_reqs_2_bits_inst_ertn
    | grant1[3] & io_reqs_3_bits_inst_ertn | grant1[4] & io_reqs_4_bits_inst_ertn;
  assign io_cdb1_bits_tlbOp =
    (grant1[0] ? io_reqs_0_bits_tlbOp : 5'h0) | (grant1[2] ? io_reqs_2_bits_tlbOp : 5'h0)
    | (grant1[3] ? io_reqs_3_bits_tlbOp : 5'h0)
    | (grant1[4] ? io_reqs_4_bits_tlbOp : 5'h0);
  assign io_cdb1_bits_is_refetch =
    grant1[0] & io_reqs_0_bits_is_refetch | grant1[2] & io_reqs_2_bits_is_refetch
    | grant1[3] & io_reqs_3_bits_is_refetch | grant1[4] & io_reqs_4_bits_is_refetch;
  assign io_cdb1_bits_is_cacop =
    grant1[0] & io_reqs_0_bits_is_cacop | grant1[2] & io_reqs_2_bits_is_cacop | grant1[3]
    & io_reqs_3_bits_is_cacop | grant1[4] & io_reqs_4_bits_is_cacop;
  assign io_cdb1_bits_rob_idx =
    (grant1[0] ? io_reqs_0_bits_rob_idx : 5'h0)
    | (grant1[1] ? io_reqs_1_bits_rob_idx : 5'h0)
    | (grant1[2] ? io_reqs_2_bits_rob_idx : 5'h0)
    | (grant1[3] ? io_reqs_3_bits_rob_idx : 5'h0)
    | (grant1[4] ? io_reqs_4_bits_rob_idx : 5'h0);
  assign io_cdb1_bits_pdest =
    (grant1[0] ? io_reqs_0_bits_pdest : 6'h0) | (grant1[1] ? io_reqs_1_bits_pdest : 6'h0)
    | (grant1[2] ? io_reqs_2_bits_pdest : 6'h0)
    | (grant1[3] ? io_reqs_3_bits_pdest : 6'h0)
    | (grant1[4] ? io_reqs_4_bits_pdest : 6'h0);
  assign io_cdb1_bits_is_branch =
    grant1[0] & io_reqs_0_bits_is_branch | grant1[2] & io_reqs_2_bits_is_branch
    | grant1[3] & io_reqs_3_bits_is_branch | grant1[4] & io_reqs_4_bits_is_branch;
  assign io_cdb1_bits_ghr =
    (grant1[0] ? io_reqs_0_bits_ghr : 10'h0) | (grant1[2] ? io_reqs_2_bits_ghr : 10'h0)
    | (grant1[3] ? io_reqs_3_bits_ghr : 10'h0) | (grant1[4] ? io_reqs_4_bits_ghr : 10'h0);
  assign io_cdb1_bits_br_actual_taken =
    grant1[0] & io_reqs_0_bits_br_actual_taken | grant1[2]
    & io_reqs_2_bits_br_actual_taken | grant1[3] & io_reqs_3_bits_br_actual_taken
    | grant1[4] & io_reqs_4_bits_br_actual_taken;
  assign io_cdb1_bits_br_type =
    (grant1[0] ? io_reqs_0_bits_br_type : 2'h0)
    | (grant1[2] ? io_reqs_2_bits_br_type : 2'h0)
    | (grant1[3] ? io_reqs_3_bits_br_type : 2'h0)
    | (grant1[4] ? io_reqs_4_bits_br_type : 2'h0);
endmodule

