// Generated by CIRCT firtool-1.139.0
module CSR(
  input         clock,
                reset,
  input  [13:0] io_raddr,
                io_waddr,
  output [31:0] io_readData,
  input         io_writeEn,
  input  [31:0] io_writeData,
                io_writeMask,
  output [31:0] io_eentryOut,
                io_eraOut,
  output        io_hasInt,
  input         io_excValid,
  input  [5:0]  io_excEcode,
  input  [31:0] io_excPc,
                io_excAddr,
  input         io_ertnFlush,
  output [1:0]  io_mmu_config_crmd_datm,
                io_mmu_config_crmd_datf,
  output        io_mmu_config_crmd_pg,
                io_mmu_config_crmd_da,
  output [1:0]  io_mmu_config_crmd_plv,
  output [9:0]  io_mmu_config_asid_asid,
  output [2:0]  io_mmu_config_dmw0_vseg,
                io_mmu_config_dmw0_pseg,
  output [1:0]  io_mmu_config_dmw0_mat,
  output        io_mmu_config_dmw0_plv3,
                io_mmu_config_dmw0_plv0,
  output [2:0]  io_mmu_config_dmw1_vseg,
                io_mmu_config_dmw1_pseg,
  output [1:0]  io_mmu_config_dmw1_mat,
  output        io_mmu_config_dmw1_plv3,
                io_mmu_config_dmw1_plv0,
  output [18:0] io_mmu_config_tlbehi_vppn,
  input         io_tlbrd_we,
                io_tlbrd_in_e,
                io_tlbrd_in_ps4MB,
  input  [18:0] io_tlbrd_in_vppn,
  input  [9:0]  io_tlbrd_in_asid,
  input  [23:0] io_tlbrd_in_lo0_ppn,
  input         io_tlbrd_in_lo0_g,
  input  [1:0]  io_tlbrd_in_lo0_mat,
                io_tlbrd_in_lo0_plv,
  input         io_tlbrd_in_lo0_d,
                io_tlbrd_in_lo0_v,
  input  [23:0] io_tlbrd_in_lo1_ppn,
  input         io_tlbrd_in_lo1_g,
  input  [1:0]  io_tlbrd_in_lo1_mat,
                io_tlbrd_in_lo1_plv,
  input         io_tlbrd_in_lo1_d,
                io_tlbrd_in_lo1_v,
  output        io_tlb_out_e,
                io_tlb_out_ps4MB,
  output [18:0] io_tlb_out_vppn,
  output [9:0]  io_tlb_out_asid,
  output        io_tlb_out_g,
  output [23:0] io_tlb_out_lo0_ppn,
  output        io_tlb_out_lo0_g,
  output [1:0]  io_tlb_out_lo0_mat,
                io_tlb_out_lo0_plv,
  output        io_tlb_out_lo0_d,
                io_tlb_out_lo0_v,
  output [23:0] io_tlb_out_lo1_ppn,
  output        io_tlb_out_lo1_g,
  output [1:0]  io_tlb_out_lo1_mat,
                io_tlb_out_lo1_plv,
  output        io_tlb_out_lo1_d,
                io_tlb_out_lo1_v,
  output [3:0]  io_tlbidx_out,
  output [31:0] io_tlbrentryOut
);

  reg  [1:0]  crmd_datm;
  reg  [1:0]  crmd_datf;
  reg         crmd_pg;
  reg         crmd_da;
  reg         crmd_ie;
  reg  [1:0]  crmd_plv;
  reg         prmd_pie;
  reg  [1:0]  prmd_pplv;
  reg         ecfg_lie_ipi;
  reg         ecfg_lie_timer;
  reg  [7:0]  ecfg_lie_hw;
  reg  [1:0]  ecfg_lie_sw;
  reg  [1:0]  estat_is_sw;
  reg         estat_is_timer;
  reg  [5:0]  estat_ecode;
  reg         tlbidx_ne;
  reg  [5:0]  tlbidx_ps;
  reg  [3:0]  tlbidx_index;
  reg  [18:0] tlbehi_vppn;
  reg  [23:0] tlbelo0_ppn;
  reg         tlbelo0_g;
  reg  [1:0]  tlbelo0_mat;
  reg  [1:0]  tlbelo0_plv;
  reg         tlbelo0_d;
  reg         tlbelo0_v;
  reg  [23:0] tlbelo1_ppn;
  reg         tlbelo1_g;
  reg  [1:0]  tlbelo1_mat;
  reg  [1:0]  tlbelo1_plv;
  reg         tlbelo1_d;
  reg         tlbelo1_v;
  reg  [9:0]  asid_asid;
  reg  [2:0]  dmw0_vseg;
  reg  [2:0]  dmw0_pseg;
  reg  [1:0]  dmw0_mat;
  reg         dmw0_plv3;
  reg         dmw0_plv0;
  reg  [2:0]  dmw1_vseg;
  reg  [2:0]  dmw1_pseg;
  reg  [1:0]  dmw1_mat;
  reg         dmw1_plv3;
  reg         dmw1_plv0;
  reg  [29:0] tcfg_initval;
  reg         tcfg_periodic;
  reg         tcfg_en;
  reg  [31:0] eraReg;
  reg  [31:0] badvReg;
  reg  [25:0] eentry_va;
  reg  [31:0] save0Reg;
  reg  [31:0] save1Reg;
  reg  [31:0] save2Reg;
  reg  [31:0] save3Reg;
  reg  [31:0] tidReg;
  reg  [31:0] timer_cnt;
  reg  [25:0] tlbrentry_va;
  wire [11:0] _io_hasInt_T_2 =
    {ecfg_lie_timer, 1'h0, ecfg_lie_hw, ecfg_lie_sw}
    & {estat_is_timer, 9'h0, estat_is_sw};
  wire [31:0] _io_readData_T_10 = {tcfg_initval, tcfg_periodic, tcfg_en};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      crmd_datm <= 2'h0;
      crmd_datf <= 2'h0;
      crmd_pg <= 1'h0;
      crmd_da <= 1'h1;
      crmd_ie <= 1'h0;
      crmd_plv <= 2'h0;
      prmd_pie <= 1'h0;
      prmd_pplv <= 2'h0;
      ecfg_lie_ipi <= 1'h0;
      ecfg_lie_timer <= 1'h0;
      ecfg_lie_hw <= 8'h0;
      ecfg_lie_sw <= 2'h0;
      estat_is_sw <= 2'h0;
      estat_is_timer <= 1'h0;
      estat_ecode <= 6'h0;
      tlbidx_ne <= 1'h0;
      tlbidx_ps <= 6'h0;
      tlbidx_index <= 4'h0;
      tlbehi_vppn <= 19'h0;
      tlbelo0_ppn <= 24'h0;
      tlbelo0_g <= 1'h0;
      tlbelo0_mat <= 2'h0;
      tlbelo0_plv <= 2'h0;
      tlbelo0_d <= 1'h0;
      tlbelo0_v <= 1'h0;
      tlbelo1_ppn <= 24'h0;
      tlbelo1_g <= 1'h0;
      tlbelo1_mat <= 2'h0;
      tlbelo1_plv <= 2'h0;
      tlbelo1_d <= 1'h0;
      tlbelo1_v <= 1'h0;
      asid_asid <= 10'h0;
      dmw0_vseg <= 3'h0;
      dmw0_pseg <= 3'h0;
      dmw0_mat <= 2'h0;
      dmw0_plv3 <= 1'h0;
      dmw0_plv0 <= 1'h0;
      dmw1_vseg <= 3'h0;
      dmw1_pseg <= 3'h0;
      dmw1_mat <= 2'h0;
      dmw1_plv3 <= 1'h0;
      dmw1_plv0 <= 1'h0;
      tcfg_initval <= 30'h0;
      tcfg_periodic <= 1'h0;
      tcfg_en <= 1'h0;
      eraReg <= 32'h0;
      badvReg <= 32'h0;
      eentry_va <= 26'h0;
      save0Reg <= 32'h0;
      save1Reg <= 32'h0;
      save2Reg <= 32'h0;
      save3Reg <= 32'h0;
      tidReg <= 32'h0;
      timer_cnt <= 32'hFFFFFFFF;
      tlbrentry_va <= 26'h0;
    end
    else begin
      automatic logic        _GEN;
      automatic logic [8:0]  _crmd_T_4;
      automatic logic        _GEN_0;
      automatic logic        _GEN_1;
      automatic logic        _GEN_2;
      automatic logic        _GEN_3;
      automatic logic        _GEN_4;
      automatic logic        _GEN_5;
      automatic logic        _GEN_6;
      automatic logic        _GEN_7;
      automatic logic        _GEN_8;
      automatic logic        _GEN_9;
      automatic logic [31:0] _tlbidx_T_4;
      automatic logic        _GEN_10;
      automatic logic        _GEN_11;
      automatic logic        _GEN_12;
      automatic logic        _GEN_13;
      automatic logic        _GEN_14;
      automatic logic        _GEN_15 = io_waddr == 14'h30;
      automatic logic        _GEN_16 = io_waddr == 14'h31;
      automatic logic        _GEN_17 = io_waddr == 14'h32;
      automatic logic        _GEN_18 = io_waddr == 14'h33;
      automatic logic        _GEN_19 = io_waddr == 14'h40;
      automatic logic        _GEN_20 = io_waddr == 14'h41;
      automatic logic        _GEN_21 = io_waddr == 14'h44;
      automatic logic        _GEN_22 = io_waddr == 14'h88;
      automatic logic        _GEN_23 = io_waddr == 14'h180;
      automatic logic [31:0] _tcfg_next_value_T_4;
      automatic logic        _GEN_24;
      automatic logic        _GEN_25;
      automatic logic        _GEN_26;
      automatic logic        _GEN_27;
      automatic logic        _GEN_28;
      _GEN = io_waddr == 14'h0;
      _crmd_T_4 =
        {crmd_datm, crmd_datf, crmd_pg, crmd_da, crmd_ie, crmd_plv} & ~(io_writeMask[8:0])
        | io_writeData[8:0] & io_writeMask[8:0];
      _GEN_0 = io_writeEn & _GEN;
      _GEN_1 = _GEN_0 ? _crmd_T_4[4] : crmd_pg;
      _GEN_2 = _GEN_0 ? _crmd_T_4[3] : crmd_da;
      _GEN_3 = io_waddr == 14'h1;
      _GEN_4 = io_waddr == 14'h4;
      _GEN_5 = io_waddr == 14'h5;
      _GEN_6 = io_waddr == 14'h6;
      _GEN_7 = io_waddr == 14'h7;
      _GEN_8 = io_waddr == 14'hC;
      _GEN_9 = io_waddr == 14'h10;
      _tlbidx_T_4 =
        {tlbidx_ne, 1'h0, tlbidx_ps, 20'h0, tlbidx_index} & ~io_writeMask | io_writeData
        & io_writeMask;
      _GEN_10 =
        ~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
        | ~_GEN_9;
      _GEN_11 = io_waddr == 14'h11;
      _GEN_12 = io_waddr == 14'h12;
      _GEN_13 = io_waddr == 14'h13;
      _GEN_14 = io_waddr == 14'h18;
      _tcfg_next_value_T_4 =
        _io_readData_T_10 & ~io_writeMask | io_writeData & io_writeMask;
      _GEN_24 = io_writeEn & io_waddr == 14'h41 & _tcfg_next_value_T_4[0];
      _GEN_25 = tcfg_en & timer_cnt != 32'hFFFFFFFF;
      _GEN_26 = timer_cnt == 32'h0;
      _GEN_27 =
        io_excValid
        & (io_excEcode == 6'h1 | io_excEcode == 6'h2 | io_excEcode == 6'h3
           | io_excEcode == 6'h4 | io_excEcode == 6'h7 | io_excEcode == 6'h8
           | io_excEcode == 6'h9 | (&io_excEcode));
      _GEN_28 = io_ertnFlush & (&estat_ecode);
      if (_GEN_0) begin
        crmd_datm <= _crmd_T_4[8:7];
        crmd_datf <= _crmd_T_4[6:5];
      end
      crmd_pg <= io_excValid ? ~(&io_excEcode) & _GEN_1 : _GEN_28 | _GEN_1;
      crmd_da <= io_excValid ? (&io_excEcode) | _GEN_2 : ~_GEN_28 & _GEN_2;
      crmd_ie <=
        ~io_excValid & (io_ertnFlush ? prmd_pie : _GEN_0 ? _crmd_T_4[2] : crmd_ie);
      if (io_excValid) begin
        crmd_plv <= 2'h0;
        prmd_pie <= crmd_ie;
        prmd_pplv <= crmd_plv;
        estat_ecode <= io_excEcode;
        eraReg <= io_excPc;
      end
      else begin
        if (io_ertnFlush)
          crmd_plv <= prmd_pplv;
        else if (_GEN_0)
          crmd_plv <= _crmd_T_4[1:0];
        if (~io_writeEn | _GEN | ~_GEN_3) begin
        end
        else begin
          automatic logic [2:0] _prmd_T_4;
          _prmd_T_4 =
            {prmd_pie, prmd_pplv} & ~(io_writeMask[2:0]) | io_writeData[2:0]
            & io_writeMask[2:0];
          prmd_pie <= _prmd_T_4[2];
          prmd_pplv <= _prmd_T_4[1:0];
        end
        if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | ~_GEN_6) begin
        end
        else
          eraReg <= eraReg & ~io_writeMask | io_writeData & io_writeMask;
      end
      if (~io_writeEn | _GEN | _GEN_3 | ~_GEN_4) begin
      end
      else begin
        automatic logic [12:0] _ecfg_T_4;
        _ecfg_T_4 =
          {ecfg_lie_ipi, ecfg_lie_timer, 1'h0, ecfg_lie_hw, ecfg_lie_sw}
          & ~(io_writeMask[12:0]) | io_writeData[12:0] & io_writeMask[12:0];
        ecfg_lie_ipi <= _ecfg_T_4[12];
        ecfg_lie_timer <= _ecfg_T_4[11];
        ecfg_lie_hw <= _ecfg_T_4[9:2];
        ecfg_lie_sw <= _ecfg_T_4[1:0];
      end
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | ~_GEN_5) begin
      end
      else
        estat_is_sw <=
          estat_is_sw & ~(io_writeMask[1:0]) | io_writeData[1:0] & io_writeMask[1:0];
      estat_is_timer <=
        ~_GEN_24 & _GEN_25 & _GEN_26
        | (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
           | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
           | _GEN_18 | _GEN_19 | _GEN_20 | ~(_GEN_21 & io_writeMask[0] & io_writeData[0]))
        & estat_is_timer;
      if (io_tlbrd_we) begin
        tlbidx_ne <= ~io_tlbrd_in_e;
        tlbidx_ps <= io_tlbrd_in_e ? (io_tlbrd_in_ps4MB ? 6'h15 : 6'hC) : 6'h0;
        tlbehi_vppn <= io_tlbrd_in_e ? io_tlbrd_in_vppn : 19'h0;
        tlbelo0_ppn <= io_tlbrd_in_e ? io_tlbrd_in_lo0_ppn : 24'h0;
        tlbelo0_g <= io_tlbrd_in_e & io_tlbrd_in_lo0_g;
        tlbelo0_mat <= io_tlbrd_in_e ? io_tlbrd_in_lo0_mat : 2'h0;
        tlbelo0_plv <= io_tlbrd_in_e ? io_tlbrd_in_lo0_plv : 2'h0;
        tlbelo0_d <= io_tlbrd_in_e & io_tlbrd_in_lo0_d;
        tlbelo0_v <= io_tlbrd_in_e & io_tlbrd_in_lo0_v;
        tlbelo1_ppn <= io_tlbrd_in_e ? io_tlbrd_in_lo1_ppn : 24'h0;
        tlbelo1_g <= io_tlbrd_in_e & io_tlbrd_in_lo1_g;
        tlbelo1_mat <= io_tlbrd_in_e ? io_tlbrd_in_lo1_mat : 2'h0;
        tlbelo1_plv <= io_tlbrd_in_e ? io_tlbrd_in_lo1_plv : 2'h0;
        tlbelo1_d <= io_tlbrd_in_e & io_tlbrd_in_lo1_d;
        tlbelo1_v <= io_tlbrd_in_e & io_tlbrd_in_lo1_v;
        asid_asid <= io_tlbrd_in_e ? io_tlbrd_in_asid : 10'h0;
      end
      else begin
        if (_GEN_10) begin
        end
        else begin
          tlbidx_ne <= _tlbidx_T_4[31];
          tlbidx_ps <= _tlbidx_T_4[29:24];
        end
        if (_GEN_27)
          tlbehi_vppn <= io_excAddr[31:13];
        else if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
                 | _GEN_9 | ~_GEN_11) begin
        end
        else
          tlbehi_vppn <=
            tlbehi_vppn & ~(io_writeMask[31:13]) | io_writeData[31:13]
            & io_writeMask[31:13];
        if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
            | _GEN_9 | _GEN_11 | ~_GEN_12) begin
        end
        else begin
          automatic logic [31:0] _tlbelo0_T_4;
          _tlbelo0_T_4 =
            {tlbelo0_ppn, 1'h0, tlbelo0_g, tlbelo0_mat, tlbelo0_plv, tlbelo0_d, tlbelo0_v}
            & ~io_writeMask | io_writeData & io_writeMask;
          tlbelo0_ppn <= _tlbelo0_T_4[31:8];
          tlbelo0_g <= _tlbelo0_T_4[6];
          tlbelo0_mat <= _tlbelo0_T_4[5:4];
          tlbelo0_plv <= _tlbelo0_T_4[3:2];
          tlbelo0_d <= _tlbelo0_T_4[1];
          tlbelo0_v <= _tlbelo0_T_4[0];
        end
        if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
            | _GEN_9 | _GEN_11 | _GEN_12 | ~_GEN_13) begin
        end
        else begin
          automatic logic [31:0] _tlbelo1_T_4;
          _tlbelo1_T_4 =
            {tlbelo1_ppn, 1'h0, tlbelo1_g, tlbelo1_mat, tlbelo1_plv, tlbelo1_d, tlbelo1_v}
            & ~io_writeMask | io_writeData & io_writeMask;
          tlbelo1_ppn <= _tlbelo1_T_4[31:8];
          tlbelo1_g <= _tlbelo1_T_4[6];
          tlbelo1_mat <= _tlbelo1_T_4[5:4];
          tlbelo1_plv <= _tlbelo1_T_4[3:2];
          tlbelo1_d <= _tlbelo1_T_4[1];
          tlbelo1_v <= _tlbelo1_T_4[0];
        end
        if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
            | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | ~_GEN_14) begin
        end
        else
          asid_asid <=
            asid_asid & ~(io_writeMask[9:0]) | io_writeData[9:0] & io_writeMask[9:0];
      end
      if (_GEN_10) begin
      end
      else
        tlbidx_index <= _tlbidx_T_4[3:0];
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
          | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21 | _GEN_22 | ~_GEN_23) begin
      end
      else begin
        automatic logic [31:0] _dmw0_T_4;
        _dmw0_T_4 =
          {dmw0_vseg, 1'h0, dmw0_pseg, 19'h0, dmw0_mat, dmw0_plv3, 2'h0, dmw0_plv0}
          & ~io_writeMask | io_writeData & io_writeMask;
        dmw0_vseg <= _dmw0_T_4[31:29];
        dmw0_pseg <= _dmw0_T_4[27:25];
        dmw0_mat <= _dmw0_T_4[5:4];
        dmw0_plv3 <= _dmw0_T_4[3];
        dmw0_plv0 <= _dmw0_T_4[0];
      end
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
          | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21 | _GEN_22 | _GEN_23
          | io_waddr != 14'h181) begin
      end
      else begin
        automatic logic [31:0] _dmw1_T_4;
        _dmw1_T_4 =
          {dmw1_vseg, 1'h0, dmw1_pseg, 19'h0, dmw1_mat, dmw1_plv3, 2'h0, dmw1_plv0}
          & ~io_writeMask | io_writeData & io_writeMask;
        dmw1_vseg <= _dmw1_T_4[31:29];
        dmw1_pseg <= _dmw1_T_4[27:25];
        dmw1_mat <= _dmw1_T_4[5:4];
        dmw1_plv3 <= _dmw1_T_4[3];
        dmw1_plv0 <= _dmw1_T_4[0];
      end
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
          | _GEN_18 | _GEN_19 | ~_GEN_20) begin
      end
      else begin
        automatic logic [31:0] _tcfg_T_4;
        _tcfg_T_4 =
          {tcfg_initval, tcfg_periodic, tcfg_en} & ~io_writeMask | io_writeData
          & io_writeMask;
        tcfg_initval <= _tcfg_T_4[31:2];
        tcfg_periodic <= _tcfg_T_4[1];
        tcfg_en <= _tcfg_T_4[0];
      end
      if (_GEN_27)
        badvReg <= io_excAddr;
      else if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | ~_GEN_7) begin
      end
      else
        badvReg <= badvReg & ~io_writeMask | io_writeData & io_writeMask;
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | ~_GEN_8) begin
      end
      else
        eentry_va <=
          eentry_va & ~(io_writeMask[31:6]) | io_writeData[31:6] & io_writeMask[31:6];
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | ~_GEN_15) begin
      end
      else
        save0Reg <= save0Reg & ~io_writeMask | io_writeData & io_writeMask;
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | ~_GEN_16) begin
      end
      else
        save1Reg <= save1Reg & ~io_writeMask | io_writeData & io_writeMask;
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16
          | ~_GEN_17) begin
      end
      else
        save2Reg <= save2Reg & ~io_writeMask | io_writeData & io_writeMask;
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
          | ~_GEN_18) begin
      end
      else
        save3Reg <= save3Reg & ~io_writeMask | io_writeData & io_writeMask;
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
          | _GEN_18 | ~_GEN_19) begin
      end
      else
        tidReg <= tidReg & ~io_writeMask | io_writeData & io_writeMask;
      if (_GEN_24)
        timer_cnt <= {_tcfg_next_value_T_4[31:2], 2'h0};
      else if (_GEN_25)
        timer_cnt <=
          _GEN_26
            ? (tcfg_periodic ? {tcfg_initval, 2'h0} : 32'hFFFFFFFF)
            : timer_cnt - 32'h1;
      if (~io_writeEn | _GEN | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_9 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
          | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21 | ~_GEN_22) begin
      end
      else
        tlbrentry_va <=
          tlbrentry_va & ~(io_writeMask[31:6]) | io_writeData[31:6] & io_writeMask[31:6];
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        crmd_datm = 2'h0;
        crmd_datf = 2'h0;
        crmd_pg = 1'h0;
        crmd_da = 1'h1;
        crmd_ie = 1'h0;
        crmd_plv = 2'h0;
        prmd_pie = 1'h0;
        prmd_pplv = 2'h0;
        ecfg_lie_ipi = 1'h0;
        ecfg_lie_timer = 1'h0;
        ecfg_lie_hw = 8'h0;
        ecfg_lie_sw = 2'h0;
        estat_is_sw = 2'h0;
        estat_is_timer = 1'h0;
        estat_ecode = 6'h0;
        tlbidx_ne = 1'h0;
        tlbidx_ps = 6'h0;
        tlbidx_index = 4'h0;
        tlbehi_vppn = 19'h0;
        tlbelo0_ppn = 24'h0;
        tlbelo0_g = 1'h0;
        tlbelo0_mat = 2'h0;
        tlbelo0_plv = 2'h0;
        tlbelo0_d = 1'h0;
        tlbelo0_v = 1'h0;
        tlbelo1_ppn = 24'h0;
        tlbelo1_g = 1'h0;
        tlbelo1_mat = 2'h0;
        tlbelo1_plv = 2'h0;
        tlbelo1_d = 1'h0;
        tlbelo1_v = 1'h0;
        asid_asid = 10'h0;
        dmw0_vseg = 3'h0;
        dmw0_pseg = 3'h0;
        dmw0_mat = 2'h0;
        dmw0_plv3 = 1'h0;
        dmw0_plv0 = 1'h0;
        dmw1_vseg = 3'h0;
        dmw1_pseg = 3'h0;
        dmw1_mat = 2'h0;
        dmw1_plv3 = 1'h0;
        dmw1_plv0 = 1'h0;
        tcfg_initval = 30'h0;
        tcfg_periodic = 1'h0;
        tcfg_en = 1'h0;
        eraReg = 32'h0;
        badvReg = 32'h0;
        eentry_va = 26'h0;
        save0Reg = 32'h0;
        save1Reg = 32'h0;
        save2Reg = 32'h0;
        save3Reg = 32'h0;
        tidReg = 32'h0;
        timer_cnt = 32'hFFFFFFFF;
        tlbrentry_va = 26'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_readData =
    io_raddr == 14'h0
      ? {23'h0, crmd_datm, crmd_datf, crmd_pg, crmd_da, crmd_ie, crmd_plv}
      : io_raddr == 14'h1
          ? {29'h0, prmd_pie, prmd_pplv}
          : io_raddr == 14'h4
              ? {19'h0, ecfg_lie_ipi, ecfg_lie_timer, 1'h0, ecfg_lie_hw, ecfg_lie_sw}
              : io_raddr == 14'h5
                  ? {10'h0, estat_ecode, 4'h0, estat_is_timer, 9'h0, estat_is_sw}
                  : io_raddr == 14'h6
                      ? eraReg
                      : io_raddr == 14'h7
                          ? badvReg
                          : io_raddr == 14'hC
                              ? {eentry_va, 6'h0}
                              : io_raddr == 14'h10
                                  ? {tlbidx_ne, 1'h0, tlbidx_ps, 20'h0, tlbidx_index}
                                  : io_raddr == 14'h11
                                      ? {tlbehi_vppn, 13'h0}
                                      : io_raddr == 14'h12
                                          ? {tlbelo0_ppn,
                                             1'h0,
                                             tlbelo0_g,
                                             tlbelo0_mat,
                                             tlbelo0_plv,
                                             tlbelo0_d,
                                             tlbelo0_v}
                                          : io_raddr == 14'h13
                                              ? {tlbelo1_ppn,
                                                 1'h0,
                                                 tlbelo1_g,
                                                 tlbelo1_mat,
                                                 tlbelo1_plv,
                                                 tlbelo1_d,
                                                 tlbelo1_v}
                                              : io_raddr == 14'h18
                                                  ? {22'h280, asid_asid}
                                                  : io_raddr == 14'h30
                                                      ? save0Reg
                                                      : io_raddr == 14'h31
                                                          ? save1Reg
                                                          : io_raddr == 14'h32
                                                              ? save2Reg
                                                              : io_raddr == 14'h33
                                                                  ? save3Reg
                                                                  : io_raddr == 14'h40
                                                                      ? tidReg
                                                                      : io_raddr == 14'h41
                                                                          ? _io_readData_T_10
                                                                          : io_raddr == 14'h42
                                                                              ? timer_cnt
                                                                              : io_raddr == 14'h88
                                                                                  ? {tlbrentry_va,
                                                                                     6'h0}
                                                                                  : io_raddr == 14'h180
                                                                                      ? {dmw0_vseg,
                                                                                         1'h0,
                                                                                         dmw0_pseg,
                                                                                         19'h0,
                                                                                         dmw0_mat,
                                                                                         dmw0_plv3,
                                                                                         2'h0,
                                                                                         dmw0_plv0}
                                                                                      : io_raddr == 14'h181
                                                                                          ? {dmw1_vseg,
                                                                                             1'h0,
                                                                                             dmw1_pseg,
                                                                                             19'h0,
                                                                                             dmw1_mat,
                                                                                             dmw1_plv3,
                                                                                             2'h0,
                                                                                             dmw1_plv0}
                                                                                          : 32'h0;
  assign io_eentryOut = {eentry_va, 6'h0};
  assign io_eraOut = eraReg;
  assign io_hasInt = (|{_io_hasInt_T_2[11], _io_hasInt_T_2[1:0]}) & crmd_ie;
  assign io_mmu_config_crmd_datm = crmd_datm;
  assign io_mmu_config_crmd_datf = crmd_datf;
  assign io_mmu_config_crmd_pg = crmd_pg;
  assign io_mmu_config_crmd_da = crmd_da;
  assign io_mmu_config_crmd_plv = crmd_plv;
  assign io_mmu_config_asid_asid = asid_asid;
  assign io_mmu_config_dmw0_vseg = dmw0_vseg;
  assign io_mmu_config_dmw0_pseg = dmw0_pseg;
  assign io_mmu_config_dmw0_mat = dmw0_mat;
  assign io_mmu_config_dmw0_plv3 = dmw0_plv3;
  assign io_mmu_config_dmw0_plv0 = dmw0_plv0;
  assign io_mmu_config_dmw1_vseg = dmw1_vseg;
  assign io_mmu_config_dmw1_pseg = dmw1_pseg;
  assign io_mmu_config_dmw1_mat = dmw1_mat;
  assign io_mmu_config_dmw1_plv3 = dmw1_plv3;
  assign io_mmu_config_dmw1_plv0 = dmw1_plv0;
  assign io_mmu_config_tlbehi_vppn = tlbehi_vppn;
  assign io_tlb_out_e = (&estat_ecode) | ~tlbidx_ne;
  assign io_tlb_out_ps4MB = tlbidx_ps == 6'h15;
  assign io_tlb_out_vppn = tlbehi_vppn;
  assign io_tlb_out_asid = asid_asid;
  assign io_tlb_out_g = tlbelo0_g & tlbelo1_g;
  assign io_tlb_out_lo0_ppn = tlbelo0_ppn;
  assign io_tlb_out_lo0_g = tlbelo0_g;
  assign io_tlb_out_lo0_mat = tlbelo0_mat;
  assign io_tlb_out_lo0_plv = tlbelo0_plv;
  assign io_tlb_out_lo0_d = tlbelo0_d;
  assign io_tlb_out_lo0_v = tlbelo0_v;
  assign io_tlb_out_lo1_ppn = tlbelo1_ppn;
  assign io_tlb_out_lo1_g = tlbelo1_g;
  assign io_tlb_out_lo1_mat = tlbelo1_mat;
  assign io_tlb_out_lo1_plv = tlbelo1_plv;
  assign io_tlb_out_lo1_d = tlbelo1_d;
  assign io_tlb_out_lo1_v = tlbelo1_v;
  assign io_tlbidx_out = tlbidx_index;
  assign io_tlbrentryOut = {tlbrentry_va, 6'h0};
endmodule

