// Generated by CIRCT firtool-1.139.0
module Ctrl(
  input         io_ex_branch_req,
  input  [31:0] io_ex_branch_pc,
  input         io_wb_flush,
  input  [31:0] io_wb_target_pc,
  output [31:0] io_next_pc,
  output        io_flush_if,
                io_flush_id
);

  wire do_flush = io_wb_flush | io_ex_branch_req;
  assign io_next_pc = io_wb_flush ? io_wb_target_pc : io_ex_branch_pc;
  assign io_flush_if = do_flush;
  assign io_flush_id = do_flush;
endmodule

