// Generated by CIRCT firtool-1.139.0
module Decoder(
  input  [31:0] io_inst,
  output [11:0] io_out_aluOp,
  output [7:0]  io_out_lsOp,
  output [6:0]  io_out_mduOp,
  output [8:0]  io_out_brType,
  output [31:0] io_out_imm,
  output        io_out_src1IsPC,
                io_out_src2IsImm,
                io_out_src2IsFour,
  output [4:0]  io_out_destReg,
  output        io_out_regWe,
                io_out_memWe,
                io_out_resFromMem,
                io_out_resFromMulDiv,
                io_out_hasException,
  output [5:0]  io_out_ecode,
  output        io_out_isCsr,
                io_out_csrWe,
  output [13:0] io_out_csrNum,
  output        io_out_inst_ertn,
                io_out_rdtimel,
                io_out_rdtimeh,
                io_out_src1_read,
                io_out_src2_read,
  output [4:0]  io_out_tlbOp,
                io_out_invtlb_op,
  output        io_out_is_refetch,
                io_out_is_cacop,
  output [4:0]  io_out_cacop_op
);

  wire [13:0] io_out_csrNum_0;
  wire        io_out_csrWe_0;
  wire        _decoded_T_1 = io_inst[31:15] == 17'h20;
  wire        _decoded_T_3 = io_inst[31:15] == 17'h22;
  wire        _decoded_T_5 = io_inst[31:15] == 17'h24;
  wire        _decoded_T_7 = io_inst[31:15] == 17'h25;
  wire        _decoded_T_9 = io_inst[31:15] == 17'h28;
  wire        _decoded_T_11 = io_inst[31:15] == 17'h29;
  wire        _decoded_T_13 = io_inst[31:15] == 17'h2A;
  wire        _decoded_T_15 = io_inst[31:15] == 17'h2B;
  wire        _decoded_T_17 = io_inst[31:15] == 17'h2E;
  wire        _decoded_T_19 = io_inst[31:15] == 17'h2F;
  wire        _decoded_T_21 = io_inst[31:15] == 17'h30;
  wire        _decoded_T_23 = io_inst[31:15] == 17'h81;
  wire        _decoded_T_25 = io_inst[31:15] == 17'h89;
  wire        _decoded_T_27 = io_inst[31:15] == 17'h91;
  wire        _decoded_T_29 = io_inst[31:22] == 10'h8;
  wire        _decoded_T_31 = io_inst[31:22] == 10'h9;
  wire        _decoded_T_33 = io_inst[31:22] == 10'hA;
  wire        _decoded_T_35 = io_inst[31:22] == 10'hD;
  wire        _decoded_T_37 = io_inst[31:22] == 10'hE;
  wire        _decoded_T_39 = io_inst[31:22] == 10'hF;
  wire        _decoded_T_41 = io_inst[31:25] == 7'hA;
  wire        _decoded_T_43 = io_inst[31:25] == 7'hE;
  wire        _decoded_T_45 = io_inst[31:15] == 17'h38;
  wire        _decoded_T_47 = io_inst[31:15] == 17'h39;
  wire        _decoded_T_49 = io_inst[31:15] == 17'h3A;
  wire        _decoded_T_51 = io_inst[31:15] == 17'h40;
  wire        _decoded_T_53 = io_inst[31:15] == 17'h41;
  wire        _decoded_T_55 = io_inst[31:15] == 17'h42;
  wire        _decoded_T_57 = io_inst[31:15] == 17'h43;
  wire        _decoded_T_59 = io_inst[31:22] == 10'hA0;
  wire        _decoded_T_61 = io_inst[31:22] == 10'hA1;
  wire        _decoded_T_63 = io_inst[31:22] == 10'hA2;
  wire        _decoded_T_65 = io_inst[31:22] == 10'hA8;
  wire        _decoded_T_67 = io_inst[31:22] == 10'hA9;
  wire        _decoded_T_69 = io_inst[31:22] == 10'hA4;
  wire        _decoded_T_71 = io_inst[31:22] == 10'hA5;
  wire        _decoded_T_527 = io_inst[31:22] == 10'hA6;
  wire        _decoded_T_75 = io_inst[31:26] == 6'h13;
  wire        _decoded_T_77 = io_inst[31:26] == 6'h14;
  wire        _decoded_T_473 = io_inst[31:26] == 6'h15;
  wire        _decoded_T_81 = io_inst[31:26] == 6'h16;
  wire        _decoded_T_83 = io_inst[31:26] == 6'h17;
  wire        _decoded_T_85 = io_inst[31:26] == 6'h18;
  wire        _decoded_T_87 = io_inst[31:26] == 6'h19;
  wire        _decoded_T_89 = io_inst[31:26] == 6'h1A;
  wire        _decoded_T_91 = io_inst[31:26] == 6'h1B;
  wire        _decoded_T_93 = io_inst == 32'h6482800;
  wire        _decoded_T_95 = io_inst == 32'h6482C00;
  wire        _decoded_T_97 = io_inst == 32'h6483000;
  wire        _decoded_T_99 = io_inst == 32'h6483400;
  wire        _decoded_T_666 = io_inst[31:15] == 17'hC93;
  wire        _decoded_T_614 = io_inst[31:22] == 10'h18;
  wire        _GEN =
    _decoded_T_93 | _decoded_T_95 | _decoded_T_97 | _decoded_T_99 | _decoded_T_666;
  wire        _GEN_0 =
    _decoded_T_59 | _decoded_T_61 | _decoded_T_63 | _decoded_T_65 | _decoded_T_67
    | _decoded_T_69 | _decoded_T_71 | _decoded_T_527 | _decoded_T_75;
  wire        _GEN_1 =
    _decoded_T_45 | _decoded_T_47 | _decoded_T_49 | _decoded_T_51 | _decoded_T_53
    | _decoded_T_55 | _decoded_T_57;
  wire [11:0] decoded_0 =
    _decoded_T_1
      ? 12'h1
      : _decoded_T_3
          ? 12'h2
          : _decoded_T_5
              ? 12'h4
              : _decoded_T_7
                  ? 12'h8
                  : _decoded_T_9
                      ? 12'h20
                      : _decoded_T_11
                          ? 12'h10
                          : _decoded_T_13
                              ? 12'h40
                              : _decoded_T_15
                                  ? 12'h80
                                  : _decoded_T_17
                                      ? 12'h100
                                      : _decoded_T_19
                                          ? 12'h200
                                          : _decoded_T_21
                                              ? 12'h400
                                              : _decoded_T_23
                                                  ? 12'h100
                                                  : _decoded_T_25
                                                      ? 12'h200
                                                      : _decoded_T_27
                                                          ? 12'h400
                                                          : _decoded_T_29
                                                              ? 12'h4
                                                              : _decoded_T_31
                                                                  ? 12'h8
                                                                  : _decoded_T_33
                                                                      ? 12'h1
                                                                      : _decoded_T_35
                                                                          ? 12'h10
                                                                          : _decoded_T_37
                                                                              ? 12'h40
                                                                              : _decoded_T_39
                                                                                  ? 12'h80
                                                                                  : _decoded_T_41
                                                                                      ? 12'h800
                                                                                      : _decoded_T_43
                                                                                          ? 12'h1
                                                                                          : _GEN_1
                                                                                              ? 12'h0
                                                                                              : _GEN_0
                                                                                                  ? 12'h1
                                                                                                  : _decoded_T_77
                                                                                                      ? 12'h0
                                                                                                      : _decoded_T_473
                                                                                                          ? 12'h1
                                                                                                          : _decoded_T_81
                                                                                                            | _decoded_T_83
                                                                                                            | _decoded_T_85
                                                                                                            | _decoded_T_87
                                                                                                            | _decoded_T_89
                                                                                                            | _decoded_T_91
                                                                                                            | _GEN
                                                                                                              ? 12'h0
                                                                                                              : {11'h0,
                                                                                                                 _decoded_T_614};
  wire [7:0]  decoded_1 =
    _decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
    | _decoded_T_11 | _decoded_T_13 | _decoded_T_15 | _decoded_T_17 | _decoded_T_19
    | _decoded_T_21 | _decoded_T_23 | _decoded_T_25 | _decoded_T_27 | _decoded_T_29
    | _decoded_T_31 | _decoded_T_33 | _decoded_T_35 | _decoded_T_37 | _decoded_T_39
    | _decoded_T_41 | _decoded_T_43 | _GEN_1
      ? 8'h0
      : _decoded_T_59
          ? 8'h1
          : _decoded_T_61
              ? 8'h2
              : _decoded_T_63
                  ? 8'h4
                  : _decoded_T_65
                      ? 8'h8
                      : _decoded_T_67
                          ? 8'h10
                          : _decoded_T_69
                              ? 8'h20
                              : _decoded_T_71 ? 8'h40 : {_decoded_T_527, 7'h0};
  wire        _GEN_2 = _decoded_T_41 | _decoded_T_43;
  wire        _GEN_3 =
    _decoded_T_23 | _decoded_T_25 | _decoded_T_27 | _decoded_T_29 | _decoded_T_31
    | _decoded_T_33 | _decoded_T_35 | _decoded_T_37 | _decoded_T_39 | _GEN_2;
  wire [6:0]  decoded_2 =
    _decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
    | _decoded_T_11 | _decoded_T_13 | _decoded_T_15 | _decoded_T_17 | _decoded_T_19
    | _decoded_T_21 | _GEN_3
      ? 7'h0
      : _decoded_T_45
          ? 7'h1
          : _decoded_T_47
              ? 7'h2
              : _decoded_T_49
                  ? 7'h4
                  : _decoded_T_51
                      ? 7'h8
                      : _decoded_T_53
                          ? 7'h10
                          : _decoded_T_55 ? 7'h20 : {_decoded_T_57, 6'h0};
  wire        _GEN_4 = _decoded_T_93 | _decoded_T_95 | _decoded_T_97 | _decoded_T_99;
  wire        _GEN_5 =
    _decoded_T_81 | _decoded_T_83 | _decoded_T_85 | _decoded_T_87 | _decoded_T_89
    | _decoded_T_91;
  wire        _GEN_6 = _decoded_T_69 | _decoded_T_71 | _decoded_T_527;
  wire        _GEN_7 =
    _decoded_T_59 | _decoded_T_61 | _decoded_T_63 | _decoded_T_65 | _decoded_T_67
    | _GEN_6;
  wire        _GEN_8 =
    _decoded_T_45 | _decoded_T_47 | _decoded_T_49 | _decoded_T_51 | _decoded_T_53
    | _decoded_T_55 | _decoded_T_57 | _GEN_7;
  wire        _GEN_9 = _decoded_T_35 | _decoded_T_37 | _decoded_T_39;
  wire        _GEN_10 =
    _decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
    | _decoded_T_11 | _decoded_T_13 | _decoded_T_15 | _decoded_T_17 | _decoded_T_19
    | _decoded_T_21 | _decoded_T_23 | _decoded_T_25 | _decoded_T_27 | _decoded_T_29
    | _decoded_T_31 | _decoded_T_33 | _GEN_9;
  wire        _GEN_11 =
    _decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
    | _decoded_T_11 | _decoded_T_13 | _decoded_T_15 | _decoded_T_17 | _decoded_T_19
    | _decoded_T_21;
  wire        _GEN_12 = _decoded_T_77 | _decoded_T_473;
  wire [2:0]  decoded_5 =
    _GEN_11
      ? 3'h0
      : _decoded_T_23 | _decoded_T_25 | _decoded_T_27
          ? 3'h6
          : _decoded_T_29 | _decoded_T_31 | _decoded_T_33
              ? 3'h1
              : _GEN_9
                  ? 3'h2
                  : _GEN_2
                      ? 3'h4
                      : _GEN_1
                          ? 3'h0
                          : _GEN_7
                              ? 3'h1
                              : _decoded_T_75
                                  ? 3'h3
                                  : _GEN_12
                                      ? 3'h5
                                      : _GEN_5
                                          ? 3'h3
                                          : _GEN ? 3'h0 : {2'h0, _decoded_T_614};
  wire        _GEN_13 =
    _decoded_T_59 | _decoded_T_61 | _decoded_T_63 | _decoded_T_65 | _decoded_T_67;
  wire        _GEN_14 =
    _decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
    | _decoded_T_11 | _decoded_T_13 | _decoded_T_15 | _decoded_T_17 | _decoded_T_19
    | _decoded_T_21 | _decoded_T_23 | _decoded_T_25 | _decoded_T_27 | _decoded_T_29
    | _decoded_T_31 | _decoded_T_33 | _decoded_T_35 | _decoded_T_37 | _decoded_T_39
    | _decoded_T_41 | _decoded_T_43 | _decoded_T_45 | _decoded_T_47 | _decoded_T_49
    | _decoded_T_51 | _decoded_T_53 | _decoded_T_55 | _decoded_T_57 | _GEN_13;
  wire [1:0]  decoded_6 =
    _GEN_14
      ? 2'h1
      : _GEN_6 ? 2'h0 : _decoded_T_75 ? 2'h1 : _decoded_T_77 ? 2'h0 : {2{_decoded_T_473}};
  wire        decoded_8 = ~_GEN_14 & (_decoded_T_69 | _decoded_T_71 | _decoded_T_527);
  wire [8:0]  decoded_9 =
    _decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
    | _decoded_T_11 | _decoded_T_13 | _decoded_T_15 | _decoded_T_17 | _decoded_T_19
    | _decoded_T_21 | _decoded_T_23 | _decoded_T_25 | _decoded_T_27 | _decoded_T_29
    | _decoded_T_31 | _decoded_T_33 | _decoded_T_35 | _decoded_T_37 | _decoded_T_39
    | _decoded_T_41 | _decoded_T_43 | _GEN_8
      ? 9'h0
      : _decoded_T_75
          ? 9'h40
          : _decoded_T_77
              ? 9'h80
              : _decoded_T_473
                  ? 9'h100
                  : _decoded_T_81
                      ? 9'h1
                      : _decoded_T_83
                          ? 9'h2
                          : _decoded_T_85
                              ? 9'h4
                              : _decoded_T_87
                                  ? 9'h8
                                  : _decoded_T_89 ? 9'h10 : {3'h0, _decoded_T_91, 5'h0};
  wire        is_syscall = io_inst[31:15] == 17'h56;
  wire        is_break = io_inst[31:15] == 17'h54;
  wire        is_ertn = io_inst == 32'h6483800;
  wire        is_csr = io_inst[31:24] == 8'h4;
  wire        is_rdtime_base = io_inst[31:11] == 21'hC;
  wire        is_rdcntid = is_rdtime_base & ~(io_inst[10]) & io_inst[4:0] == 5'h0;
  wire        is_tlbsrch = io_inst == 32'h6482800;
  wire        is_tlbrd = io_inst == 32'h6482C00;
  wire        is_tlbwr = io_inst == 32'h6483000;
  wire        is_tlbfill = io_inst == 32'h6483400;
  wire        is_invtlb = io_inst[31:15] == 17'hC93 & io_inst[4:0] < 5'h7;
  assign io_out_csrWe_0 = is_csr & (|(io_inst[9:5])) | is_tlbsrch;
  assign io_out_csrNum_0 = is_tlbsrch ? 14'h10 : is_rdcntid ? 14'h40 : io_inst[23:10];
  wire        is_cacop = io_inst[31:22] == 10'h18;
  wire        inst_valid =
    (|{decoded_0, decoded_1, decoded_2, decoded_9}) | is_syscall | is_break | is_ertn
    | is_csr | is_rdtime_base | is_tlbsrch | is_tlbrd | is_tlbwr | is_tlbfill | is_invtlb
    | is_cacop;
  assign io_out_aluOp = decoded_0;
  assign io_out_lsOp = decoded_1;
  assign io_out_mduOp = decoded_2;
  assign io_out_brType = decoded_9;
  assign io_out_imm =
    (decoded_5 == 3'h6 ? {27'h0, io_inst[14:10]} : 32'h0)
    | (decoded_5 == 3'h1 ? {{20{io_inst[21]}}, io_inst[21:10]} : 32'h0)
    | (decoded_5 == 3'h2 ? {20'h0, io_inst[21:10]} : 32'h0)
    | (decoded_5 == 3'h3 ? {{14{io_inst[25]}}, io_inst[25:10], 2'h0} : 32'h0)
    | (decoded_5 == 3'h4 ? {io_inst[24:5], 12'h0} : 32'h0)
    | (decoded_5 == 3'h5 ? {{4{io_inst[9]}}, io_inst[9:0], io_inst[25:10], 2'h0} : 32'h0);
  assign io_out_src1IsPC =
    (_GEN_10
       ? 2'h1
       : _decoded_T_41
           ? 2'h0
           : _decoded_T_43
               ? 2'h2
               : _GEN_8
                   ? 2'h1
                   : _decoded_T_75
                       ? 2'h2
                       : _decoded_T_77
                           ? 2'h1
                           : _decoded_T_473
                               ? 2'h2
                               : _GEN_5 ? 2'h1 : {1'h0, ~_GEN_4}) == 2'h2;
  assign io_out_src2IsImm =
    (_GEN_11
       ? 2'h1
       : _GEN_3
           ? 2'h2
           : _GEN_1
               ? 2'h1
               : _GEN_7
                   ? 2'h2
                   : _decoded_T_75 | _decoded_T_77 | _decoded_T_473 | _GEN_5
                       ? 2'h1
                       : _GEN_4
                           ? 2'h0
                           : _decoded_T_666 | ~_decoded_T_614 ? 2'h1 : 2'h2) == 2'h2;
  assign io_out_src2IsFour = decoded_9 == 9'h40 | decoded_9 == 9'h100;
  assign io_out_destReg =
    is_rdcntid
      ? io_inst[9:5]
      : is_rdtime_base | is_csr
          ? io_inst[4:0]
          : (decoded_6 == 2'h1 ? io_inst[4:0] : 5'h0)
            | (decoded_6 == 2'h2 ? io_inst[9:5] : 5'h0) | {4'h0, &decoded_6};
  assign io_out_regWe =
    _GEN_14 | ~_GEN_6 & (_decoded_T_75 | ~_decoded_T_77 & _decoded_T_473) | is_csr
    | is_rdtime_base;
  assign io_out_memWe = decoded_8;
  assign io_out_resFromMem = (|decoded_1) & ~decoded_8;
  assign io_out_resFromMulDiv = |decoded_2;
  assign io_out_hasException = ~inst_valid | is_syscall | is_break;
  assign io_out_ecode = is_syscall ? 6'hB : is_break ? 6'hC : inst_valid ? 6'h0 : 6'hD;
  assign io_out_isCsr = is_csr | is_rdcntid;
  assign io_out_csrWe = io_out_csrWe_0;
  assign io_out_csrNum = io_out_csrNum_0;
  assign io_out_inst_ertn = is_ertn;
  assign io_out_rdtimel = is_rdtime_base & ~(io_inst[10]) & ~is_rdcntid;
  assign io_out_rdtimeh = is_rdtime_base & io_inst[10];
  assign io_out_src1_read =
    inst_valid
    & (_GEN_10 | ~_GEN_2
       & (_decoded_T_45 | _decoded_T_47 | _decoded_T_49 | _decoded_T_51 | _decoded_T_53
          | _decoded_T_55 | _decoded_T_57 | _GEN_0 | ~_GEN_12
          & (_GEN_5 | ~_GEN_4 & (_decoded_T_666 | _decoded_T_614))) | is_csr
       & (|(io_inst[9:5])) & io_inst[9:5] != 5'h1);
  assign io_out_src2_read =
    inst_valid
    & (_GEN_11 | ~_GEN_3
       & (_GEN_1 | ~_GEN_13
          & (_GEN_6 | ~(_decoded_T_75 | _GEN_12) & (_GEN_5 | ~_GEN_4 & _decoded_T_666)))
       | is_csr & (|(io_inst[9:5])));
  assign io_out_tlbOp =
    is_tlbsrch
      ? 5'h1
      : is_tlbrd ? 5'h2 : is_tlbwr ? 5'h4 : is_tlbfill ? 5'h8 : {is_invtlb, 4'h0};
  assign io_out_invtlb_op = is_invtlb ? io_inst[4:0] : 5'h0;
  assign io_out_is_refetch =
    is_csr & io_out_csrWe_0
    & (io_out_csrNum_0 == 14'h0 | io_out_csrNum_0 == 14'h18 | io_out_csrNum_0 == 14'h180
       | io_out_csrNum_0 == 14'h181) | is_tlbrd | is_tlbwr | is_tlbfill | is_invtlb;
  assign io_out_is_cacop = is_cacop;
  assign io_out_cacop_op = io_inst[4:0];
endmodule

