// Generated by CIRCT firtool-1.139.0
module DispatchBuffer(
  input         clock,
                reset,
                io_flush,
  output        io_in0_ready,
  input         io_in0_valid,
  input  [31:0] io_in0_bits_pc,
                io_in0_bits_inst,
  input  [12:0] io_in0_bits_aluOp,
  input  [6:0]  io_in0_bits_mduOp,
  input  [8:0]  io_in0_bits_brType,
  input  [31:0] io_in0_bits_imm,
  input         io_in0_bits_src1IsPC,
                io_in0_bits_src2IsImm,
                io_in0_bits_src2IsFour,
  input  [4:0]  io_in0_bits_src1_addr,
                io_in0_bits_src2_addr,
  input         io_in0_bits_resFromMulDiv,
                io_in0_bits_memWe,
  input  [7:0]  io_in0_bits_lsOp,
  input         io_in0_bits_resFromMem,
                io_in0_bits_regWriteEn,
  input  [4:0]  io_in0_bits_destReg,
  input  [31:0] io_in0_bits_aux_data,
  input         io_in0_bits_hasException,
  input  [5:0]  io_in0_bits_ecode,
  input         io_in0_bits_isCsr,
                io_in0_bits_csrWe,
  input  [13:0] io_in0_bits_csrNum,
  input         io_in0_bits_inst_ertn,
                io_in0_bits_rdtimel,
                io_in0_bits_rdtimeh,
  input  [4:0]  io_in0_bits_tlbOp,
                io_in0_bits_invtlb_op,
  input         io_in0_bits_is_refetch,
                io_in0_bits_is_cacop,
  input  [4:0]  io_in0_bits_cacop_op,
  input         io_in0_bits_src1_read,
                io_in0_bits_src2_read,
                io_in0_bits_is_branch,
                io_in0_bits_pred_taken,
  input  [31:0] io_in0_bits_pred_target,
  input  [1:0]  io_in0_bits_bpu_type,
  input  [9:0]  io_in0_bits_ghr,
  input  [3:0]  io_in0_bits_ras_tos,
  output        io_in1_ready,
  input         io_in1_valid,
  input  [31:0] io_in1_bits_pc,
                io_in1_bits_inst,
  input  [12:0] io_in1_bits_aluOp,
  input  [6:0]  io_in1_bits_mduOp,
  input  [8:0]  io_in1_bits_brType,
  input  [31:0] io_in1_bits_imm,
  input         io_in1_bits_src1IsPC,
                io_in1_bits_src2IsImm,
                io_in1_bits_src2IsFour,
  input  [4:0]  io_in1_bits_src1_addr,
                io_in1_bits_src2_addr,
  input         io_in1_bits_resFromMulDiv,
                io_in1_bits_memWe,
  input  [7:0]  io_in1_bits_lsOp,
  input         io_in1_bits_resFromMem,
                io_in1_bits_regWriteEn,
  input  [4:0]  io_in1_bits_destReg,
  input  [31:0] io_in1_bits_aux_data,
  input         io_in1_bits_hasException,
  input  [5:0]  io_in1_bits_ecode,
  input         io_in1_bits_isCsr,
                io_in1_bits_csrWe,
  input  [13:0] io_in1_bits_csrNum,
  input         io_in1_bits_inst_ertn,
                io_in1_bits_rdtimel,
                io_in1_bits_rdtimeh,
  input  [4:0]  io_in1_bits_tlbOp,
                io_in1_bits_invtlb_op,
  input         io_in1_bits_is_refetch,
                io_in1_bits_is_cacop,
  input  [4:0]  io_in1_bits_cacop_op,
  input         io_in1_bits_src1_read,
                io_in1_bits_src2_read,
                io_in1_bits_is_branch,
                io_in1_bits_pred_taken,
  input  [31:0] io_in1_bits_pred_target,
  input  [1:0]  io_in1_bits_bpu_type,
  input  [9:0]  io_in1_bits_ghr,
  input  [3:0]  io_in1_bits_ras_tos,
  input         io_out0_ready,
  output        io_out0_valid,
  output [31:0] io_out0_bits_pc,
                io_out0_bits_inst,
  output [12:0] io_out0_bits_aluOp,
  output [6:0]  io_out0_bits_mduOp,
  output [8:0]  io_out0_bits_brType,
  output [31:0] io_out0_bits_imm,
  output        io_out0_bits_src1IsPC,
                io_out0_bits_src2IsImm,
                io_out0_bits_src2IsFour,
  output [4:0]  io_out0_bits_src1_addr,
                io_out0_bits_src2_addr,
  output        io_out0_bits_resFromMulDiv,
                io_out0_bits_memWe,
  output [7:0]  io_out0_bits_lsOp,
  output        io_out0_bits_resFromMem,
                io_out0_bits_regWriteEn,
  output [4:0]  io_out0_bits_destReg,
  output [31:0] io_out0_bits_aux_data,
  output        io_out0_bits_hasException,
  output [5:0]  io_out0_bits_ecode,
  output        io_out0_bits_isCsr,
                io_out0_bits_csrWe,
  output [13:0] io_out0_bits_csrNum,
  output        io_out0_bits_inst_ertn,
                io_out0_bits_rdtimel,
                io_out0_bits_rdtimeh,
  output [4:0]  io_out0_bits_tlbOp,
                io_out0_bits_invtlb_op,
  output        io_out0_bits_is_refetch,
                io_out0_bits_is_cacop,
  output [4:0]  io_out0_bits_cacop_op,
  output        io_out0_bits_src1_read,
                io_out0_bits_src2_read,
                io_out0_bits_is_branch,
                io_out0_bits_pred_taken,
  output [31:0] io_out0_bits_pred_target,
  output [1:0]  io_out0_bits_bpu_type,
  output [9:0]  io_out0_bits_ghr,
  output [3:0]  io_out0_bits_ras_tos,
  input         io_out1_ready,
  output        io_out1_valid,
  output [31:0] io_out1_bits_pc,
                io_out1_bits_inst,
  output [12:0] io_out1_bits_aluOp,
  output [6:0]  io_out1_bits_mduOp,
  output [8:0]  io_out1_bits_brType,
  output [31:0] io_out1_bits_imm,
  output        io_out1_bits_src1IsPC,
                io_out1_bits_src2IsImm,
                io_out1_bits_src2IsFour,
  output [4:0]  io_out1_bits_src1_addr,
                io_out1_bits_src2_addr,
  output        io_out1_bits_resFromMulDiv,
                io_out1_bits_memWe,
  output [7:0]  io_out1_bits_lsOp,
  output        io_out1_bits_resFromMem,
                io_out1_bits_regWriteEn,
  output [4:0]  io_out1_bits_destReg,
  output [31:0] io_out1_bits_aux_data,
  output        io_out1_bits_hasException,
  output [5:0]  io_out1_bits_ecode,
  output        io_out1_bits_isCsr,
                io_out1_bits_csrWe,
  output [13:0] io_out1_bits_csrNum,
  output        io_out1_bits_inst_ertn,
                io_out1_bits_rdtimel,
                io_out1_bits_rdtimeh,
  output [4:0]  io_out1_bits_tlbOp,
                io_out1_bits_invtlb_op,
  output        io_out1_bits_is_refetch,
                io_out1_bits_is_cacop,
  output [4:0]  io_out1_bits_cacop_op,
  output        io_out1_bits_src1_read,
                io_out1_bits_src2_read,
                io_out1_bits_is_branch,
                io_out1_bits_pred_taken,
  output [31:0] io_out1_bits_pred_target,
  output [1:0]  io_out1_bits_bpu_type,
  output [9:0]  io_out1_bits_ghr,
  output [3:0]  io_out1_bits_ras_tos
);

  reg         valid0;
  reg  [31:0] bits0_pc;
  reg  [31:0] bits0_inst;
  reg  [12:0] bits0_aluOp;
  reg  [6:0]  bits0_mduOp;
  reg  [8:0]  bits0_brType;
  reg  [31:0] bits0_imm;
  reg         bits0_src1IsPC;
  reg         bits0_src2IsImm;
  reg         bits0_src2IsFour;
  reg  [4:0]  bits0_src1_addr;
  reg  [4:0]  bits0_src2_addr;
  reg         bits0_resFromMulDiv;
  reg         bits0_memWe;
  reg  [7:0]  bits0_lsOp;
  reg         bits0_resFromMem;
  reg         bits0_regWriteEn;
  reg  [4:0]  bits0_destReg;
  reg  [31:0] bits0_aux_data;
  reg         bits0_hasException;
  reg  [5:0]  bits0_ecode;
  reg         bits0_isCsr;
  reg         bits0_csrWe;
  reg  [13:0] bits0_csrNum;
  reg         bits0_inst_ertn;
  reg         bits0_rdtimel;
  reg         bits0_rdtimeh;
  reg  [4:0]  bits0_tlbOp;
  reg  [4:0]  bits0_invtlb_op;
  reg         bits0_is_refetch;
  reg         bits0_is_cacop;
  reg  [4:0]  bits0_cacop_op;
  reg         bits0_src1_read;
  reg         bits0_src2_read;
  reg         bits0_is_branch;
  reg         bits0_pred_taken;
  reg  [31:0] bits0_pred_target;
  reg  [1:0]  bits0_bpu_type;
  reg  [9:0]  bits0_ghr;
  reg  [3:0]  bits0_ras_tos;
  reg         valid1;
  reg  [31:0] bits1_pc;
  reg  [31:0] bits1_inst;
  reg  [12:0] bits1_aluOp;
  reg  [6:0]  bits1_mduOp;
  reg  [8:0]  bits1_brType;
  reg  [31:0] bits1_imm;
  reg         bits1_src1IsPC;
  reg         bits1_src2IsImm;
  reg         bits1_src2IsFour;
  reg  [4:0]  bits1_src1_addr;
  reg  [4:0]  bits1_src2_addr;
  reg         bits1_resFromMulDiv;
  reg         bits1_memWe;
  reg  [7:0]  bits1_lsOp;
  reg         bits1_resFromMem;
  reg         bits1_regWriteEn;
  reg  [4:0]  bits1_destReg;
  reg  [31:0] bits1_aux_data;
  reg         bits1_hasException;
  reg  [5:0]  bits1_ecode;
  reg         bits1_isCsr;
  reg         bits1_csrWe;
  reg  [13:0] bits1_csrNum;
  reg         bits1_inst_ertn;
  reg         bits1_rdtimel;
  reg         bits1_rdtimeh;
  reg  [4:0]  bits1_tlbOp;
  reg  [4:0]  bits1_invtlb_op;
  reg         bits1_is_refetch;
  reg         bits1_is_cacop;
  reg  [4:0]  bits1_cacop_op;
  reg         bits1_src1_read;
  reg         bits1_src2_read;
  reg         bits1_is_branch;
  reg         bits1_pred_taken;
  reg  [31:0] bits1_pred_target;
  reg  [1:0]  bits1_bpu_type;
  reg  [9:0]  bits1_ghr;
  reg  [3:0]  bits1_ras_tos;
  wire        pop0 = valid0 & io_out0_ready;
  wire [1:0]  pop_cnt = pop0 & valid1 & io_out1_ready ? 2'h2 : {1'h0, pop0};
  wire        remain0_v = pop_cnt != 2'h2 & (pop_cnt == 2'h1 ? valid1 : valid0);
  wire        remain1_v = ~(|pop_cnt) & valid1;
  wire [1:0]  space = remain0_v ? {1'h0, ~remain1_v} : 2'h2;
  wire        io_in1_ready_0 = space == 2'h2;
  wire        _GEN = space == 2'h1;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid0 <= 1'h0;
      valid1 <= 1'h0;
    end
    else begin
      automatic logic enq0 = io_in0_valid & (|space);
      valid0 <= ~io_flush & (io_in1_ready_0 ? enq0 : _GEN | remain0_v);
      valid1 <=
        ~io_flush & (io_in1_ready_0 ? io_in1_valid & enq0 : _GEN ? enq0 : remain1_v);
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_flush) begin
    end
    else if (io_in1_ready_0) begin
      bits0_pc <= io_in0_bits_pc;
      bits0_inst <= io_in0_bits_inst;
      bits0_aluOp <= io_in0_bits_aluOp;
      bits0_mduOp <= io_in0_bits_mduOp;
      bits0_brType <= io_in0_bits_brType;
      bits0_imm <= io_in0_bits_imm;
      bits0_src1IsPC <= io_in0_bits_src1IsPC;
      bits0_src2IsImm <= io_in0_bits_src2IsImm;
      bits0_src2IsFour <= io_in0_bits_src2IsFour;
      bits0_src1_addr <= io_in0_bits_src1_addr;
      bits0_src2_addr <= io_in0_bits_src2_addr;
      bits0_resFromMulDiv <= io_in0_bits_resFromMulDiv;
      bits0_memWe <= io_in0_bits_memWe;
      bits0_lsOp <= io_in0_bits_lsOp;
      bits0_resFromMem <= io_in0_bits_resFromMem;
      bits0_regWriteEn <= io_in0_bits_regWriteEn;
      bits0_destReg <= io_in0_bits_destReg;
      bits0_aux_data <= io_in0_bits_aux_data;
      bits0_hasException <= io_in0_bits_hasException;
      bits0_ecode <= io_in0_bits_ecode;
      bits0_isCsr <= io_in0_bits_isCsr;
      bits0_csrWe <= io_in0_bits_csrWe;
      bits0_csrNum <= io_in0_bits_csrNum;
      bits0_inst_ertn <= io_in0_bits_inst_ertn;
      bits0_rdtimel <= io_in0_bits_rdtimel;
      bits0_rdtimeh <= io_in0_bits_rdtimeh;
      bits0_tlbOp <= io_in0_bits_tlbOp;
      bits0_invtlb_op <= io_in0_bits_invtlb_op;
      bits0_is_refetch <= io_in0_bits_is_refetch;
      bits0_is_cacop <= io_in0_bits_is_cacop;
      bits0_cacop_op <= io_in0_bits_cacop_op;
      bits0_src1_read <= io_in0_bits_src1_read;
      bits0_src2_read <= io_in0_bits_src2_read;
      bits0_is_branch <= io_in0_bits_is_branch;
      bits0_pred_taken <= io_in0_bits_pred_taken;
      bits0_pred_target <= io_in0_bits_pred_target;
      bits0_bpu_type <= io_in0_bits_bpu_type;
      bits0_ghr <= io_in0_bits_ghr;
      bits0_ras_tos <= io_in0_bits_ras_tos;
      bits1_pc <= io_in1_bits_pc;
      bits1_inst <= io_in1_bits_inst;
      bits1_aluOp <= io_in1_bits_aluOp;
      bits1_mduOp <= io_in1_bits_mduOp;
      bits1_brType <= io_in1_bits_brType;
      bits1_imm <= io_in1_bits_imm;
      bits1_src1IsPC <= io_in1_bits_src1IsPC;
      bits1_src2IsImm <= io_in1_bits_src2IsImm;
      bits1_src2IsFour <= io_in1_bits_src2IsFour;
      bits1_src1_addr <= io_in1_bits_src1_addr;
      bits1_src2_addr <= io_in1_bits_src2_addr;
      bits1_resFromMulDiv <= io_in1_bits_resFromMulDiv;
      bits1_memWe <= io_in1_bits_memWe;
      bits1_lsOp <= io_in1_bits_lsOp;
      bits1_resFromMem <= io_in1_bits_resFromMem;
      bits1_regWriteEn <= io_in1_bits_regWriteEn;
      bits1_destReg <= io_in1_bits_destReg;
      bits1_aux_data <= io_in1_bits_aux_data;
      bits1_hasException <= io_in1_bits_hasException;
      bits1_ecode <= io_in1_bits_ecode;
      bits1_isCsr <= io_in1_bits_isCsr;
      bits1_csrWe <= io_in1_bits_csrWe;
      bits1_csrNum <= io_in1_bits_csrNum;
      bits1_inst_ertn <= io_in1_bits_inst_ertn;
      bits1_rdtimel <= io_in1_bits_rdtimel;
      bits1_rdtimeh <= io_in1_bits_rdtimeh;
      bits1_tlbOp <= io_in1_bits_tlbOp;
      bits1_invtlb_op <= io_in1_bits_invtlb_op;
      bits1_is_refetch <= io_in1_bits_is_refetch;
      bits1_is_cacop <= io_in1_bits_is_cacop;
      bits1_cacop_op <= io_in1_bits_cacop_op;
      bits1_src1_read <= io_in1_bits_src1_read;
      bits1_src2_read <= io_in1_bits_src2_read;
      bits1_is_branch <= io_in1_bits_is_branch;
      bits1_pred_taken <= io_in1_bits_pred_taken;
      bits1_pred_target <= io_in1_bits_pred_target;
      bits1_bpu_type <= io_in1_bits_bpu_type;
      bits1_ghr <= io_in1_bits_ghr;
      bits1_ras_tos <= io_in1_bits_ras_tos;
    end
    else begin
      if (|pop_cnt) begin
        bits0_pc <= bits1_pc;
        bits0_inst <= bits1_inst;
        bits0_aluOp <= bits1_aluOp;
        bits0_mduOp <= bits1_mduOp;
        bits0_brType <= bits1_brType;
        bits0_imm <= bits1_imm;
        bits0_src1IsPC <= bits1_src1IsPC;
        bits0_src2IsImm <= bits1_src2IsImm;
        bits0_src2IsFour <= bits1_src2IsFour;
        bits0_src1_addr <= bits1_src1_addr;
        bits0_src2_addr <= bits1_src2_addr;
        bits0_resFromMulDiv <= bits1_resFromMulDiv;
        bits0_memWe <= bits1_memWe;
        bits0_lsOp <= bits1_lsOp;
        bits0_resFromMem <= bits1_resFromMem;
        bits0_regWriteEn <= bits1_regWriteEn;
        bits0_destReg <= bits1_destReg;
        bits0_aux_data <= bits1_aux_data;
        bits0_hasException <= bits1_hasException;
        bits0_ecode <= bits1_ecode;
        bits0_isCsr <= bits1_isCsr;
        bits0_csrWe <= bits1_csrWe;
        bits0_csrNum <= bits1_csrNum;
        bits0_inst_ertn <= bits1_inst_ertn;
        bits0_rdtimel <= bits1_rdtimel;
        bits0_rdtimeh <= bits1_rdtimeh;
        bits0_tlbOp <= bits1_tlbOp;
        bits0_invtlb_op <= bits1_invtlb_op;
        bits0_is_refetch <= bits1_is_refetch;
        bits0_is_cacop <= bits1_is_cacop;
        bits0_cacop_op <= bits1_cacop_op;
        bits0_src1_read <= bits1_src1_read;
        bits0_src2_read <= bits1_src2_read;
        bits0_is_branch <= bits1_is_branch;
        bits0_pred_taken <= bits1_pred_taken;
        bits0_pred_target <= bits1_pred_target;
        bits0_bpu_type <= bits1_bpu_type;
        bits0_ghr <= bits1_ghr;
        bits0_ras_tos <= bits1_ras_tos;
      end
      if (_GEN) begin
        bits1_pc <= io_in0_bits_pc;
        bits1_inst <= io_in0_bits_inst;
        bits1_aluOp <= io_in0_bits_aluOp;
        bits1_mduOp <= io_in0_bits_mduOp;
        bits1_brType <= io_in0_bits_brType;
        bits1_imm <= io_in0_bits_imm;
        bits1_src1IsPC <= io_in0_bits_src1IsPC;
        bits1_src2IsImm <= io_in0_bits_src2IsImm;
        bits1_src2IsFour <= io_in0_bits_src2IsFour;
        bits1_src1_addr <= io_in0_bits_src1_addr;
        bits1_src2_addr <= io_in0_bits_src2_addr;
        bits1_resFromMulDiv <= io_in0_bits_resFromMulDiv;
        bits1_memWe <= io_in0_bits_memWe;
        bits1_lsOp <= io_in0_bits_lsOp;
        bits1_resFromMem <= io_in0_bits_resFromMem;
        bits1_regWriteEn <= io_in0_bits_regWriteEn;
        bits1_destReg <= io_in0_bits_destReg;
        bits1_aux_data <= io_in0_bits_aux_data;
        bits1_hasException <= io_in0_bits_hasException;
        bits1_ecode <= io_in0_bits_ecode;
        bits1_isCsr <= io_in0_bits_isCsr;
        bits1_csrWe <= io_in0_bits_csrWe;
        bits1_csrNum <= io_in0_bits_csrNum;
        bits1_inst_ertn <= io_in0_bits_inst_ertn;
        bits1_rdtimel <= io_in0_bits_rdtimel;
        bits1_rdtimeh <= io_in0_bits_rdtimeh;
        bits1_tlbOp <= io_in0_bits_tlbOp;
        bits1_invtlb_op <= io_in0_bits_invtlb_op;
        bits1_is_refetch <= io_in0_bits_is_refetch;
        bits1_is_cacop <= io_in0_bits_is_cacop;
        bits1_cacop_op <= io_in0_bits_cacop_op;
        bits1_src1_read <= io_in0_bits_src1_read;
        bits1_src2_read <= io_in0_bits_src2_read;
        bits1_is_branch <= io_in0_bits_is_branch;
        bits1_pred_taken <= io_in0_bits_pred_taken;
        bits1_pred_target <= io_in0_bits_pred_target;
        bits1_bpu_type <= io_in0_bits_bpu_type;
        bits1_ghr <= io_in0_bits_ghr;
        bits1_ras_tos <= io_in0_bits_ras_tos;
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        valid0 = 1'h0;
        valid1 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in0_ready = |space;
  assign io_in1_ready = io_in1_ready_0;
  assign io_out0_valid = valid0;
  assign io_out0_bits_pc = bits0_pc;
  assign io_out0_bits_inst = bits0_inst;
  assign io_out0_bits_aluOp = bits0_aluOp;
  assign io_out0_bits_mduOp = bits0_mduOp;
  assign io_out0_bits_brType = bits0_brType;
  assign io_out0_bits_imm = bits0_imm;
  assign io_out0_bits_src1IsPC = bits0_src1IsPC;
  assign io_out0_bits_src2IsImm = bits0_src2IsImm;
  assign io_out0_bits_src2IsFour = bits0_src2IsFour;
  assign io_out0_bits_src1_addr = bits0_src1_addr;
  assign io_out0_bits_src2_addr = bits0_src2_addr;
  assign io_out0_bits_resFromMulDiv = bits0_resFromMulDiv;
  assign io_out0_bits_memWe = bits0_memWe;
  assign io_out0_bits_lsOp = bits0_lsOp;
  assign io_out0_bits_resFromMem = bits0_resFromMem;
  assign io_out0_bits_regWriteEn = bits0_regWriteEn;
  assign io_out0_bits_destReg = bits0_destReg;
  assign io_out0_bits_aux_data = bits0_aux_data;
  assign io_out0_bits_hasException = bits0_hasException;
  assign io_out0_bits_ecode = bits0_ecode;
  assign io_out0_bits_isCsr = bits0_isCsr;
  assign io_out0_bits_csrWe = bits0_csrWe;
  assign io_out0_bits_csrNum = bits0_csrNum;
  assign io_out0_bits_inst_ertn = bits0_inst_ertn;
  assign io_out0_bits_rdtimel = bits0_rdtimel;
  assign io_out0_bits_rdtimeh = bits0_rdtimeh;
  assign io_out0_bits_tlbOp = bits0_tlbOp;
  assign io_out0_bits_invtlb_op = bits0_invtlb_op;
  assign io_out0_bits_is_refetch = bits0_is_refetch;
  assign io_out0_bits_is_cacop = bits0_is_cacop;
  assign io_out0_bits_cacop_op = bits0_cacop_op;
  assign io_out0_bits_src1_read = bits0_src1_read;
  assign io_out0_bits_src2_read = bits0_src2_read;
  assign io_out0_bits_is_branch = bits0_is_branch;
  assign io_out0_bits_pred_taken = bits0_pred_taken;
  assign io_out0_bits_pred_target = bits0_pred_target;
  assign io_out0_bits_bpu_type = bits0_bpu_type;
  assign io_out0_bits_ghr = bits0_ghr;
  assign io_out0_bits_ras_tos = bits0_ras_tos;
  assign io_out1_valid = valid1;
  assign io_out1_bits_pc = bits1_pc;
  assign io_out1_bits_inst = bits1_inst;
  assign io_out1_bits_aluOp = bits1_aluOp;
  assign io_out1_bits_mduOp = bits1_mduOp;
  assign io_out1_bits_brType = bits1_brType;
  assign io_out1_bits_imm = bits1_imm;
  assign io_out1_bits_src1IsPC = bits1_src1IsPC;
  assign io_out1_bits_src2IsImm = bits1_src2IsImm;
  assign io_out1_bits_src2IsFour = bits1_src2IsFour;
  assign io_out1_bits_src1_addr = bits1_src1_addr;
  assign io_out1_bits_src2_addr = bits1_src2_addr;
  assign io_out1_bits_resFromMulDiv = bits1_resFromMulDiv;
  assign io_out1_bits_memWe = bits1_memWe;
  assign io_out1_bits_lsOp = bits1_lsOp;
  assign io_out1_bits_resFromMem = bits1_resFromMem;
  assign io_out1_bits_regWriteEn = bits1_regWriteEn;
  assign io_out1_bits_destReg = bits1_destReg;
  assign io_out1_bits_aux_data = bits1_aux_data;
  assign io_out1_bits_hasException = bits1_hasException;
  assign io_out1_bits_ecode = bits1_ecode;
  assign io_out1_bits_isCsr = bits1_isCsr;
  assign io_out1_bits_csrWe = bits1_csrWe;
  assign io_out1_bits_csrNum = bits1_csrNum;
  assign io_out1_bits_inst_ertn = bits1_inst_ertn;
  assign io_out1_bits_rdtimel = bits1_rdtimel;
  assign io_out1_bits_rdtimeh = bits1_rdtimeh;
  assign io_out1_bits_tlbOp = bits1_tlbOp;
  assign io_out1_bits_invtlb_op = bits1_invtlb_op;
  assign io_out1_bits_is_refetch = bits1_is_refetch;
  assign io_out1_bits_is_cacop = bits1_is_cacop;
  assign io_out1_bits_cacop_op = bits1_cacop_op;
  assign io_out1_bits_src1_read = bits1_src1_read;
  assign io_out1_bits_src2_read = bits1_src2_read;
  assign io_out1_bits_is_branch = bits1_is_branch;
  assign io_out1_bits_pred_taken = bits1_pred_taken;
  assign io_out1_bits_pred_target = bits1_pred_target;
  assign io_out1_bits_bpu_type = bits1_bpu_type;
  assign io_out1_bits_ghr = bits1_ghr;
  assign io_out1_bits_ras_tos = bits1_ras_tos;
endmodule

