// Generated by CIRCT firtool-1.139.0
module Divider(
  input         clock,
                io_enable,
  input  [31:0] io_a,
                io_b,
  output [31:0] io_q,
                io_r,
  output        io_done
);

  wire [63:0] _div_ip_m_axis_dout_tdata;
  div_gen_0 div_ip (
    .aclk                   (clock),
    .s_axis_divisor_tvalid  (io_enable),
    .s_axis_divisor_tdata   (io_b),
    .s_axis_dividend_tvalid (io_enable),
    .s_axis_dividend_tdata  (io_a),
    .m_axis_dout_tvalid     (io_done),
    .m_axis_dout_tdata      (_div_ip_m_axis_dout_tdata)
  );
  assign io_q = _div_ip_m_axis_dout_tdata[63:32];
  assign io_r = _div_ip_m_axis_dout_tdata[31:0];
endmodule

