// Generated by CIRCT firtool-1.139.0
module FetchBuffer(
  input         clock,
                reset,
                io_flush,
  output        io_in0_ready,
  input         io_in0_valid,
  input  [31:0] io_in0_bits_pc,
                io_in0_bits_inst,
  input         io_in0_bits_hasException,
  input  [5:0]  io_in0_bits_ecode,
  input         io_in0_bits_pred_taken,
  input  [31:0] io_in0_bits_pred_target,
  input  [1:0]  io_in0_bits_bpu_type,
  input  [9:0]  io_in0_bits_ghr,
  input  [3:0]  io_in0_bits_ras_tos,
  output        io_in1_ready,
  input         io_in1_valid,
  input  [31:0] io_in1_bits_pc,
                io_in1_bits_inst,
  input         io_in1_bits_hasException,
  input  [5:0]  io_in1_bits_ecode,
  input         io_in1_bits_pred_taken,
  input  [31:0] io_in1_bits_pred_target,
  input  [1:0]  io_in1_bits_bpu_type,
  input  [9:0]  io_in1_bits_ghr,
  input  [3:0]  io_in1_bits_ras_tos,
  output        io_out_valid0,
  output [31:0] io_out_inst0_pc,
                io_out_inst0_inst,
                io_out_inst0_aux_data,
  output        io_out_inst0_hasException,
  output [5:0]  io_out_inst0_ecode,
  output [8:0]  io_out_inst0_esubcode,
  output        io_out_inst0_pred_taken,
  output [31:0] io_out_inst0_pred_target,
  output [1:0]  io_out_inst0_bpu_type,
  output [9:0]  io_out_inst0_ghr,
  output [3:0]  io_out_inst0_ras_tos,
  output        io_out_valid1,
  output [31:0] io_out_inst1_pc,
                io_out_inst1_inst,
                io_out_inst1_aux_data,
  output        io_out_inst1_hasException,
  output [5:0]  io_out_inst1_ecode,
  output [8:0]  io_out_inst1_esubcode,
  output        io_out_inst1_pred_taken,
  output [31:0] io_out_inst1_pred_target,
  output [1:0]  io_out_inst1_bpu_type,
  output [9:0]  io_out_inst1_ghr,
  output [3:0]  io_out_inst1_ras_tos,
  input  [1:0]  io_out_pop
);

  reg  [31:0]      buffer_0_pc;
  reg  [31:0]      buffer_0_inst;
  reg              buffer_0_hasException;
  reg  [5:0]       buffer_0_ecode;
  reg              buffer_0_pred_taken;
  reg  [31:0]      buffer_0_pred_target;
  reg  [1:0]       buffer_0_bpu_type;
  reg  [9:0]       buffer_0_ghr;
  reg  [3:0]       buffer_0_ras_tos;
  reg  [31:0]      buffer_1_pc;
  reg  [31:0]      buffer_1_inst;
  reg              buffer_1_hasException;
  reg  [5:0]       buffer_1_ecode;
  reg              buffer_1_pred_taken;
  reg  [31:0]      buffer_1_pred_target;
  reg  [1:0]       buffer_1_bpu_type;
  reg  [9:0]       buffer_1_ghr;
  reg  [3:0]       buffer_1_ras_tos;
  reg  [31:0]      buffer_2_pc;
  reg  [31:0]      buffer_2_inst;
  reg              buffer_2_hasException;
  reg  [5:0]       buffer_2_ecode;
  reg              buffer_2_pred_taken;
  reg  [31:0]      buffer_2_pred_target;
  reg  [1:0]       buffer_2_bpu_type;
  reg  [9:0]       buffer_2_ghr;
  reg  [3:0]       buffer_2_ras_tos;
  reg  [31:0]      buffer_3_pc;
  reg  [31:0]      buffer_3_inst;
  reg              buffer_3_hasException;
  reg  [5:0]       buffer_3_ecode;
  reg              buffer_3_pred_taken;
  reg  [31:0]      buffer_3_pred_target;
  reg  [1:0]       buffer_3_bpu_type;
  reg  [9:0]       buffer_3_ghr;
  reg  [3:0]       buffer_3_ras_tos;
  reg  [31:0]      buffer_4_pc;
  reg  [31:0]      buffer_4_inst;
  reg              buffer_4_hasException;
  reg  [5:0]       buffer_4_ecode;
  reg              buffer_4_pred_taken;
  reg  [31:0]      buffer_4_pred_target;
  reg  [1:0]       buffer_4_bpu_type;
  reg  [9:0]       buffer_4_ghr;
  reg  [3:0]       buffer_4_ras_tos;
  reg  [31:0]      buffer_5_pc;
  reg  [31:0]      buffer_5_inst;
  reg              buffer_5_hasException;
  reg  [5:0]       buffer_5_ecode;
  reg              buffer_5_pred_taken;
  reg  [31:0]      buffer_5_pred_target;
  reg  [1:0]       buffer_5_bpu_type;
  reg  [9:0]       buffer_5_ghr;
  reg  [3:0]       buffer_5_ras_tos;
  reg  [31:0]      buffer_6_pc;
  reg  [31:0]      buffer_6_inst;
  reg              buffer_6_hasException;
  reg  [5:0]       buffer_6_ecode;
  reg              buffer_6_pred_taken;
  reg  [31:0]      buffer_6_pred_target;
  reg  [1:0]       buffer_6_bpu_type;
  reg  [9:0]       buffer_6_ghr;
  reg  [3:0]       buffer_6_ras_tos;
  reg  [31:0]      buffer_7_pc;
  reg  [31:0]      buffer_7_inst;
  reg              buffer_7_hasException;
  reg  [5:0]       buffer_7_ecode;
  reg              buffer_7_pred_taken;
  reg  [31:0]      buffer_7_pred_target;
  reg  [1:0]       buffer_7_bpu_type;
  reg  [9:0]       buffer_7_ghr;
  reg  [3:0]       buffer_7_ras_tos;
  reg  [2:0]       head;
  reg  [2:0]       tail;
  reg  [3:0]       count;
  wire             in_ready = count < 4'h7;
  wire [7:0][31:0] _GEN =
    {{buffer_7_pc},
     {buffer_6_pc},
     {buffer_5_pc},
     {buffer_4_pc},
     {buffer_3_pc},
     {buffer_2_pc},
     {buffer_1_pc},
     {buffer_0_pc}};
  wire [7:0][31:0] _GEN_0 =
    {{buffer_7_inst},
     {buffer_6_inst},
     {buffer_5_inst},
     {buffer_4_inst},
     {buffer_3_inst},
     {buffer_2_inst},
     {buffer_1_inst},
     {buffer_0_inst}};
  wire [7:0]       _GEN_1 =
    {{buffer_7_hasException},
     {buffer_6_hasException},
     {buffer_5_hasException},
     {buffer_4_hasException},
     {buffer_3_hasException},
     {buffer_2_hasException},
     {buffer_1_hasException},
     {buffer_0_hasException}};
  wire [7:0][5:0]  _GEN_2 =
    {{buffer_7_ecode},
     {buffer_6_ecode},
     {buffer_5_ecode},
     {buffer_4_ecode},
     {buffer_3_ecode},
     {buffer_2_ecode},
     {buffer_1_ecode},
     {buffer_0_ecode}};
  wire [7:0]       _GEN_3 =
    {{buffer_7_pred_taken},
     {buffer_6_pred_taken},
     {buffer_5_pred_taken},
     {buffer_4_pred_taken},
     {buffer_3_pred_taken},
     {buffer_2_pred_taken},
     {buffer_1_pred_taken},
     {buffer_0_pred_taken}};
  wire [7:0][31:0] _GEN_4 =
    {{buffer_7_pred_target},
     {buffer_6_pred_target},
     {buffer_5_pred_target},
     {buffer_4_pred_target},
     {buffer_3_pred_target},
     {buffer_2_pred_target},
     {buffer_1_pred_target},
     {buffer_0_pred_target}};
  wire [7:0][1:0]  _GEN_5 =
    {{buffer_7_bpu_type},
     {buffer_6_bpu_type},
     {buffer_5_bpu_type},
     {buffer_4_bpu_type},
     {buffer_3_bpu_type},
     {buffer_2_bpu_type},
     {buffer_1_bpu_type},
     {buffer_0_bpu_type}};
  wire [7:0][9:0]  _GEN_6 =
    {{buffer_7_ghr},
     {buffer_6_ghr},
     {buffer_5_ghr},
     {buffer_4_ghr},
     {buffer_3_ghr},
     {buffer_2_ghr},
     {buffer_1_ghr},
     {buffer_0_ghr}};
  wire [7:0][3:0]  _GEN_7 =
    {{buffer_7_ras_tos},
     {buffer_6_ras_tos},
     {buffer_5_ras_tos},
     {buffer_4_ras_tos},
     {buffer_3_ras_tos},
     {buffer_2_ras_tos},
     {buffer_1_ras_tos},
     {buffer_0_ras_tos}};
  wire [2:0]       _io_out_inst1_sum_T = head + 3'h1;
  always @(posedge clock) begin
    if (io_flush) begin
    end
    else begin
      automatic logic [7:0] t0_oh;
      automatic logic [7:0] t1_oh;
      t0_oh = 8'h1 << tail;
      t1_oh = 8'h1 << tail + 3'h1;
      if (in_ready & t0_oh[0]) begin
        buffer_0_pc <= io_in0_bits_pc;
        buffer_0_inst <= io_in0_bits_inst;
        buffer_0_hasException <= io_in0_bits_hasException;
        buffer_0_ecode <= io_in0_bits_ecode;
        buffer_0_pred_taken <= io_in0_bits_pred_taken;
        buffer_0_pred_target <= io_in0_bits_pred_target;
        buffer_0_bpu_type <= io_in0_bits_bpu_type;
        buffer_0_ghr <= io_in0_bits_ghr;
        buffer_0_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[0]) begin
        buffer_0_pc <= io_in1_bits_pc;
        buffer_0_inst <= io_in1_bits_inst;
        buffer_0_hasException <= io_in1_bits_hasException;
        buffer_0_ecode <= io_in1_bits_ecode;
        buffer_0_pred_taken <= io_in1_bits_pred_taken;
        buffer_0_pred_target <= io_in1_bits_pred_target;
        buffer_0_bpu_type <= io_in1_bits_bpu_type;
        buffer_0_ghr <= io_in1_bits_ghr;
        buffer_0_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[1]) begin
        buffer_1_pc <= io_in0_bits_pc;
        buffer_1_inst <= io_in0_bits_inst;
        buffer_1_hasException <= io_in0_bits_hasException;
        buffer_1_ecode <= io_in0_bits_ecode;
        buffer_1_pred_taken <= io_in0_bits_pred_taken;
        buffer_1_pred_target <= io_in0_bits_pred_target;
        buffer_1_bpu_type <= io_in0_bits_bpu_type;
        buffer_1_ghr <= io_in0_bits_ghr;
        buffer_1_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[1]) begin
        buffer_1_pc <= io_in1_bits_pc;
        buffer_1_inst <= io_in1_bits_inst;
        buffer_1_hasException <= io_in1_bits_hasException;
        buffer_1_ecode <= io_in1_bits_ecode;
        buffer_1_pred_taken <= io_in1_bits_pred_taken;
        buffer_1_pred_target <= io_in1_bits_pred_target;
        buffer_1_bpu_type <= io_in1_bits_bpu_type;
        buffer_1_ghr <= io_in1_bits_ghr;
        buffer_1_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[2]) begin
        buffer_2_pc <= io_in0_bits_pc;
        buffer_2_inst <= io_in0_bits_inst;
        buffer_2_hasException <= io_in0_bits_hasException;
        buffer_2_ecode <= io_in0_bits_ecode;
        buffer_2_pred_taken <= io_in0_bits_pred_taken;
        buffer_2_pred_target <= io_in0_bits_pred_target;
        buffer_2_bpu_type <= io_in0_bits_bpu_type;
        buffer_2_ghr <= io_in0_bits_ghr;
        buffer_2_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[2]) begin
        buffer_2_pc <= io_in1_bits_pc;
        buffer_2_inst <= io_in1_bits_inst;
        buffer_2_hasException <= io_in1_bits_hasException;
        buffer_2_ecode <= io_in1_bits_ecode;
        buffer_2_pred_taken <= io_in1_bits_pred_taken;
        buffer_2_pred_target <= io_in1_bits_pred_target;
        buffer_2_bpu_type <= io_in1_bits_bpu_type;
        buffer_2_ghr <= io_in1_bits_ghr;
        buffer_2_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[3]) begin
        buffer_3_pc <= io_in0_bits_pc;
        buffer_3_inst <= io_in0_bits_inst;
        buffer_3_hasException <= io_in0_bits_hasException;
        buffer_3_ecode <= io_in0_bits_ecode;
        buffer_3_pred_taken <= io_in0_bits_pred_taken;
        buffer_3_pred_target <= io_in0_bits_pred_target;
        buffer_3_bpu_type <= io_in0_bits_bpu_type;
        buffer_3_ghr <= io_in0_bits_ghr;
        buffer_3_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[3]) begin
        buffer_3_pc <= io_in1_bits_pc;
        buffer_3_inst <= io_in1_bits_inst;
        buffer_3_hasException <= io_in1_bits_hasException;
        buffer_3_ecode <= io_in1_bits_ecode;
        buffer_3_pred_taken <= io_in1_bits_pred_taken;
        buffer_3_pred_target <= io_in1_bits_pred_target;
        buffer_3_bpu_type <= io_in1_bits_bpu_type;
        buffer_3_ghr <= io_in1_bits_ghr;
        buffer_3_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[4]) begin
        buffer_4_pc <= io_in0_bits_pc;
        buffer_4_inst <= io_in0_bits_inst;
        buffer_4_hasException <= io_in0_bits_hasException;
        buffer_4_ecode <= io_in0_bits_ecode;
        buffer_4_pred_taken <= io_in0_bits_pred_taken;
        buffer_4_pred_target <= io_in0_bits_pred_target;
        buffer_4_bpu_type <= io_in0_bits_bpu_type;
        buffer_4_ghr <= io_in0_bits_ghr;
        buffer_4_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[4]) begin
        buffer_4_pc <= io_in1_bits_pc;
        buffer_4_inst <= io_in1_bits_inst;
        buffer_4_hasException <= io_in1_bits_hasException;
        buffer_4_ecode <= io_in1_bits_ecode;
        buffer_4_pred_taken <= io_in1_bits_pred_taken;
        buffer_4_pred_target <= io_in1_bits_pred_target;
        buffer_4_bpu_type <= io_in1_bits_bpu_type;
        buffer_4_ghr <= io_in1_bits_ghr;
        buffer_4_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[5]) begin
        buffer_5_pc <= io_in0_bits_pc;
        buffer_5_inst <= io_in0_bits_inst;
        buffer_5_hasException <= io_in0_bits_hasException;
        buffer_5_ecode <= io_in0_bits_ecode;
        buffer_5_pred_taken <= io_in0_bits_pred_taken;
        buffer_5_pred_target <= io_in0_bits_pred_target;
        buffer_5_bpu_type <= io_in0_bits_bpu_type;
        buffer_5_ghr <= io_in0_bits_ghr;
        buffer_5_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[5]) begin
        buffer_5_pc <= io_in1_bits_pc;
        buffer_5_inst <= io_in1_bits_inst;
        buffer_5_hasException <= io_in1_bits_hasException;
        buffer_5_ecode <= io_in1_bits_ecode;
        buffer_5_pred_taken <= io_in1_bits_pred_taken;
        buffer_5_pred_target <= io_in1_bits_pred_target;
        buffer_5_bpu_type <= io_in1_bits_bpu_type;
        buffer_5_ghr <= io_in1_bits_ghr;
        buffer_5_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[6]) begin
        buffer_6_pc <= io_in0_bits_pc;
        buffer_6_inst <= io_in0_bits_inst;
        buffer_6_hasException <= io_in0_bits_hasException;
        buffer_6_ecode <= io_in0_bits_ecode;
        buffer_6_pred_taken <= io_in0_bits_pred_taken;
        buffer_6_pred_target <= io_in0_bits_pred_target;
        buffer_6_bpu_type <= io_in0_bits_bpu_type;
        buffer_6_ghr <= io_in0_bits_ghr;
        buffer_6_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[6]) begin
        buffer_6_pc <= io_in1_bits_pc;
        buffer_6_inst <= io_in1_bits_inst;
        buffer_6_hasException <= io_in1_bits_hasException;
        buffer_6_ecode <= io_in1_bits_ecode;
        buffer_6_pred_taken <= io_in1_bits_pred_taken;
        buffer_6_pred_target <= io_in1_bits_pred_target;
        buffer_6_bpu_type <= io_in1_bits_bpu_type;
        buffer_6_ghr <= io_in1_bits_ghr;
        buffer_6_ras_tos <= io_in1_bits_ras_tos;
      end
      if (in_ready & t0_oh[7]) begin
        buffer_7_pc <= io_in0_bits_pc;
        buffer_7_inst <= io_in0_bits_inst;
        buffer_7_hasException <= io_in0_bits_hasException;
        buffer_7_ecode <= io_in0_bits_ecode;
        buffer_7_pred_taken <= io_in0_bits_pred_taken;
        buffer_7_pred_target <= io_in0_bits_pred_target;
        buffer_7_bpu_type <= io_in0_bits_bpu_type;
        buffer_7_ghr <= io_in0_bits_ghr;
        buffer_7_ras_tos <= io_in0_bits_ras_tos;
      end
      else if (in_ready & t1_oh[7]) begin
        buffer_7_pc <= io_in1_bits_pc;
        buffer_7_inst <= io_in1_bits_inst;
        buffer_7_hasException <= io_in1_bits_hasException;
        buffer_7_ecode <= io_in1_bits_ecode;
        buffer_7_pred_taken <= io_in1_bits_pred_taken;
        buffer_7_pred_target <= io_in1_bits_pred_target;
        buffer_7_bpu_type <= io_in1_bits_bpu_type;
        buffer_7_ghr <= io_in1_bits_ghr;
        buffer_7_ras_tos <= io_in1_bits_ras_tos;
      end
    end
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      head <= 3'h0;
      tail <= 3'h0;
      count <= 4'h0;
    end
    else begin
      automatic logic [1:0] do_enq_cnt =
        io_in1_valid & in_ready ? 2'h2 : {1'h0, io_in0_valid & in_ready};
      head <= io_flush ? 3'h0 : head + {1'h0, io_out_pop};
      tail <= io_flush ? 3'h0 : tail + {1'h0, do_enq_cnt};
      count <= io_flush ? 4'h0 : count + {2'h0, do_enq_cnt} - {2'h0, io_out_pop};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        head = 3'h0;
        tail = 3'h0;
        count = 4'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in0_ready = in_ready;
  assign io_in1_ready = in_ready;
  assign io_out_valid0 = |count;
  assign io_out_inst0_pc = _GEN[head];
  assign io_out_inst0_inst = _GEN_0[head];
  assign io_out_inst0_aux_data = 32'h0;
  assign io_out_inst0_hasException = _GEN_1[head];
  assign io_out_inst0_ecode = _GEN_2[head];
  assign io_out_inst0_esubcode = 9'h0;
  assign io_out_inst0_pred_taken = _GEN_3[head];
  assign io_out_inst0_pred_target = _GEN_4[head];
  assign io_out_inst0_bpu_type = _GEN_5[head];
  assign io_out_inst0_ghr = _GEN_6[head];
  assign io_out_inst0_ras_tos = _GEN_7[head];
  assign io_out_valid1 = |(count[3:1]);
  assign io_out_inst1_pc = _GEN[_io_out_inst1_sum_T];
  assign io_out_inst1_inst = _GEN_0[_io_out_inst1_sum_T];
  assign io_out_inst1_aux_data = 32'h0;
  assign io_out_inst1_hasException = _GEN_1[_io_out_inst1_sum_T];
  assign io_out_inst1_ecode = _GEN_2[_io_out_inst1_sum_T];
  assign io_out_inst1_esubcode = 9'h0;
  assign io_out_inst1_pred_taken = _GEN_3[_io_out_inst1_sum_T];
  assign io_out_inst1_pred_target = _GEN_4[_io_out_inst1_sum_T];
  assign io_out_inst1_bpu_type = _GEN_5[_io_out_inst1_sum_T];
  assign io_out_inst1_ghr = _GEN_6[_io_out_inst1_sum_T];
  assign io_out_inst1_ras_tos = _GEN_7[_io_out_inst1_sum_T];
endmodule

