// Generated by CIRCT firtool-1.139.0
module IssueBuffer(
  input         clock,
                reset,
                io_flush,
                io_br_resolve_valid,
                io_br_resolve_mispredict,
  input  [1:0]  io_br_resolve_tag,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_pc,
                io_enq_bits_inst,
  input  [12:0] io_enq_bits_aluOp,
  input  [6:0]  io_enq_bits_mduOp,
  input  [8:0]  io_enq_bits_brType,
  input  [31:0] io_enq_bits_imm,
  input         io_enq_bits_src1IsPC,
                io_enq_bits_src2IsImm,
                io_enq_bits_src2IsFour,
  input  [4:0]  io_enq_bits_src1_addr,
  input         io_enq_bits_resFromMulDiv,
                io_enq_bits_memWe,
  input  [7:0]  io_enq_bits_lsOp,
  input         io_enq_bits_resFromMem,
                io_enq_bits_regWriteEn,
  input  [31:0] io_enq_bits_aux_data,
  input         io_enq_bits_hasException,
  input  [5:0]  io_enq_bits_ecode,
  input         io_enq_bits_isCsr,
                io_enq_bits_csrWe,
  input  [13:0] io_enq_bits_csrNum,
  input         io_enq_bits_inst_ertn,
                io_enq_bits_rdtimel,
                io_enq_bits_rdtimeh,
  input  [4:0]  io_enq_bits_tlbOp,
                io_enq_bits_invtlb_op,
  input         io_enq_bits_is_refetch,
                io_enq_bits_is_cacop,
  input  [4:0]  io_enq_bits_cacop_op,
                io_enq_bits_rob_idx,
  input         io_enq_bits_src1_read,
                io_enq_bits_src2_read,
  input  [5:0]  io_enq_bits_pdest,
                io_enq_bits_psrc1,
                io_enq_bits_psrc2,
  input         io_enq_bits_is_branch,
  input  [1:0]  io_enq_bits_branch_tag,
  input  [3:0]  io_enq_bits_branch_mask,
                io_enq_bits_lsq_idx,
  input         io_enq_bits_pred_taken,
  input  [31:0] io_enq_bits_pred_target,
  input  [1:0]  io_enq_bits_bpu_type,
  input  [9:0]  io_enq_bits_ghr,
  input  [3:0]  io_enq_bits_ras_tos,
  input         io_enq_bits_br_actual_taken,
  input  [1:0]  io_enq_bits_br_type,
  input         io_enq_bits_bimodal_pred,
                io_enq_bits_gshare_pred,
                io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_pc,
                io_deq_bits_inst,
  output [12:0] io_deq_bits_aluOp,
  output [6:0]  io_deq_bits_mduOp,
  output [8:0]  io_deq_bits_brType,
  output [31:0] io_deq_bits_imm,
  output        io_deq_bits_src1IsPC,
                io_deq_bits_src2IsImm,
                io_deq_bits_src2IsFour,
  output [4:0]  io_deq_bits_src1_addr,
  output        io_deq_bits_resFromMulDiv,
                io_deq_bits_memWe,
  output [7:0]  io_deq_bits_lsOp,
  output        io_deq_bits_resFromMem,
                io_deq_bits_regWriteEn,
  output [31:0] io_deq_bits_aux_data,
  output        io_deq_bits_hasException,
  output [5:0]  io_deq_bits_ecode,
  output        io_deq_bits_isCsr,
                io_deq_bits_csrWe,
  output [13:0] io_deq_bits_csrNum,
  output        io_deq_bits_inst_ertn,
                io_deq_bits_rdtimel,
                io_deq_bits_rdtimeh,
  output [4:0]  io_deq_bits_tlbOp,
                io_deq_bits_invtlb_op,
  output        io_deq_bits_is_refetch,
                io_deq_bits_is_cacop,
  output [4:0]  io_deq_bits_cacop_op,
                io_deq_bits_rob_idx,
  output        io_deq_bits_src1_read,
                io_deq_bits_src2_read,
  output [5:0]  io_deq_bits_pdest,
                io_deq_bits_psrc1,
                io_deq_bits_psrc2,
  output        io_deq_bits_is_branch,
  output [1:0]  io_deq_bits_branch_tag,
  output [3:0]  io_deq_bits_branch_mask,
                io_deq_bits_lsq_idx,
  output        io_deq_bits_pred_taken,
  output [31:0] io_deq_bits_pred_target,
  output [1:0]  io_deq_bits_bpu_type,
  output [9:0]  io_deq_bits_ghr,
  output [3:0]  io_deq_bits_ras_tos,
  output        io_deq_bits_br_actual_taken,
  output [1:0]  io_deq_bits_br_type,
  output        io_deq_bits_bimodal_pred,
                io_deq_bits_gshare_pred
);

  reg         valid_reg;
  reg  [31:0] data_reg_pc;
  reg  [31:0] data_reg_inst;
  reg  [12:0] data_reg_aluOp;
  reg  [6:0]  data_reg_mduOp;
  reg  [8:0]  data_reg_brType;
  reg  [31:0] data_reg_imm;
  reg         data_reg_src1IsPC;
  reg         data_reg_src2IsImm;
  reg         data_reg_src2IsFour;
  reg  [4:0]  data_reg_src1_addr;
  reg         data_reg_resFromMulDiv;
  reg         data_reg_memWe;
  reg  [7:0]  data_reg_lsOp;
  reg         data_reg_resFromMem;
  reg         data_reg_regWriteEn;
  reg  [31:0] data_reg_aux_data;
  reg         data_reg_hasException;
  reg  [5:0]  data_reg_ecode;
  reg         data_reg_isCsr;
  reg         data_reg_csrWe;
  reg  [13:0] data_reg_csrNum;
  reg         data_reg_inst_ertn;
  reg         data_reg_rdtimel;
  reg         data_reg_rdtimeh;
  reg  [4:0]  data_reg_tlbOp;
  reg  [4:0]  data_reg_invtlb_op;
  reg         data_reg_is_refetch;
  reg         data_reg_is_cacop;
  reg  [4:0]  data_reg_cacop_op;
  reg  [4:0]  data_reg_rob_idx;
  reg         data_reg_src1_read;
  reg         data_reg_src2_read;
  reg  [5:0]  data_reg_pdest;
  reg  [5:0]  data_reg_psrc1;
  reg  [5:0]  data_reg_psrc2;
  reg         data_reg_is_branch;
  reg  [1:0]  data_reg_branch_tag;
  reg  [3:0]  data_reg_branch_mask;
  reg  [3:0]  data_reg_lsq_idx;
  reg         data_reg_pred_taken;
  reg  [31:0] data_reg_pred_target;
  reg  [1:0]  data_reg_bpu_type;
  reg  [9:0]  data_reg_ghr;
  reg  [3:0]  data_reg_ras_tos;
  reg         data_reg_br_actual_taken;
  reg  [1:0]  data_reg_br_type;
  reg         data_reg_bimodal_pred;
  reg         data_reg_gshare_pred;
  wire [6:0]  _clear_mask_T_1 = 7'h1 << io_br_resolve_tag;
  wire        current_is_killed =
    valid_reg & io_br_resolve_valid & io_br_resolve_mispredict
    & (|(_clear_mask_T_1[3:0] & data_reg_branch_mask));
  wire        allow_in = ~valid_reg | current_is_killed | io_deq_ready;
  wire        _GEN = io_br_resolve_valid & ~io_br_resolve_mispredict;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_reg <= 1'h0;
      data_reg_pc <= 32'h0;
      data_reg_inst <= 32'h0;
      data_reg_aluOp <= 13'h0;
      data_reg_mduOp <= 7'h0;
      data_reg_brType <= 9'h0;
      data_reg_imm <= 32'h0;
      data_reg_src1IsPC <= 1'h0;
      data_reg_src2IsImm <= 1'h0;
      data_reg_src2IsFour <= 1'h0;
      data_reg_src1_addr <= 5'h0;
      data_reg_resFromMulDiv <= 1'h0;
      data_reg_memWe <= 1'h0;
      data_reg_lsOp <= 8'h0;
      data_reg_resFromMem <= 1'h0;
      data_reg_regWriteEn <= 1'h0;
      data_reg_aux_data <= 32'h0;
      data_reg_hasException <= 1'h0;
      data_reg_ecode <= 6'h0;
      data_reg_isCsr <= 1'h0;
      data_reg_csrWe <= 1'h0;
      data_reg_csrNum <= 14'h0;
      data_reg_inst_ertn <= 1'h0;
      data_reg_rdtimel <= 1'h0;
      data_reg_rdtimeh <= 1'h0;
      data_reg_tlbOp <= 5'h0;
      data_reg_invtlb_op <= 5'h0;
      data_reg_is_refetch <= 1'h0;
      data_reg_is_cacop <= 1'h0;
      data_reg_cacop_op <= 5'h0;
      data_reg_rob_idx <= 5'h0;
      data_reg_src1_read <= 1'h0;
      data_reg_src2_read <= 1'h0;
      data_reg_pdest <= 6'h0;
      data_reg_psrc1 <= 6'h0;
      data_reg_psrc2 <= 6'h0;
      data_reg_is_branch <= 1'h0;
      data_reg_branch_tag <= 2'h0;
      data_reg_branch_mask <= 4'h0;
      data_reg_lsq_idx <= 4'h0;
      data_reg_pred_taken <= 1'h0;
      data_reg_pred_target <= 32'h0;
      data_reg_bpu_type <= 2'h0;
      data_reg_ghr <= 10'h0;
      data_reg_ras_tos <= 4'h0;
      data_reg_br_actual_taken <= 1'h0;
      data_reg_br_type <= 2'h0;
      data_reg_bimodal_pred <= 1'h0;
      data_reg_gshare_pred <= 1'h0;
    end
    else begin
      automatic logic _data_reg_branch_mask_T;
      _data_reg_branch_mask_T = io_enq_valid & allow_in;
      valid_reg <=
        ~io_flush
        & (allow_in
             ? io_enq_valid
               & ~(io_enq_valid & io_br_resolve_valid & io_br_resolve_mispredict
                   & (|(_clear_mask_T_1[3:0] & io_enq_bits_branch_mask)))
             : ~current_is_killed & valid_reg);
      if (_data_reg_branch_mask_T) begin
        data_reg_pc <= io_enq_bits_pc;
        data_reg_inst <= io_enq_bits_inst;
        data_reg_aluOp <= io_enq_bits_aluOp;
        data_reg_mduOp <= io_enq_bits_mduOp;
        data_reg_brType <= io_enq_bits_brType;
        data_reg_imm <= io_enq_bits_imm;
        data_reg_src1IsPC <= io_enq_bits_src1IsPC;
        data_reg_src2IsImm <= io_enq_bits_src2IsImm;
        data_reg_src2IsFour <= io_enq_bits_src2IsFour;
        data_reg_src1_addr <= io_enq_bits_src1_addr;
        data_reg_resFromMulDiv <= io_enq_bits_resFromMulDiv;
        data_reg_memWe <= io_enq_bits_memWe;
        data_reg_lsOp <= io_enq_bits_lsOp;
        data_reg_resFromMem <= io_enq_bits_resFromMem;
        data_reg_regWriteEn <= io_enq_bits_regWriteEn;
        data_reg_aux_data <= io_enq_bits_aux_data;
        data_reg_hasException <= io_enq_bits_hasException;
        data_reg_ecode <= io_enq_bits_ecode;
        data_reg_isCsr <= io_enq_bits_isCsr;
        data_reg_csrWe <= io_enq_bits_csrWe;
        data_reg_csrNum <= io_enq_bits_csrNum;
        data_reg_inst_ertn <= io_enq_bits_inst_ertn;
        data_reg_rdtimel <= io_enq_bits_rdtimel;
        data_reg_rdtimeh <= io_enq_bits_rdtimeh;
        data_reg_tlbOp <= io_enq_bits_tlbOp;
        data_reg_invtlb_op <= io_enq_bits_invtlb_op;
        data_reg_is_refetch <= io_enq_bits_is_refetch;
        data_reg_is_cacop <= io_enq_bits_is_cacop;
        data_reg_cacop_op <= io_enq_bits_cacop_op;
        data_reg_rob_idx <= io_enq_bits_rob_idx;
        data_reg_src1_read <= io_enq_bits_src1_read;
        data_reg_src2_read <= io_enq_bits_src2_read;
        data_reg_pdest <= io_enq_bits_pdest;
        data_reg_psrc1 <= io_enq_bits_psrc1;
        data_reg_psrc2 <= io_enq_bits_psrc2;
        data_reg_is_branch <= io_enq_bits_is_branch;
        data_reg_branch_tag <= io_enq_bits_branch_tag;
        data_reg_lsq_idx <= io_enq_bits_lsq_idx;
        data_reg_pred_taken <= io_enq_bits_pred_taken;
        data_reg_pred_target <= io_enq_bits_pred_target;
        data_reg_bpu_type <= io_enq_bits_bpu_type;
        data_reg_ghr <= io_enq_bits_ghr;
        data_reg_ras_tos <= io_enq_bits_ras_tos;
        data_reg_br_actual_taken <= io_enq_bits_br_actual_taken;
        data_reg_br_type <= io_enq_bits_br_type;
        data_reg_bimodal_pred <= io_enq_bits_bimodal_pred;
        data_reg_gshare_pred <= io_enq_bits_gshare_pred;
      end
      if (_GEN)
        data_reg_branch_mask <=
          ~(_clear_mask_T_1[3:0])
          & (_data_reg_branch_mask_T ? io_enq_bits_branch_mask : data_reg_branch_mask);
      else if (_data_reg_branch_mask_T)
        data_reg_branch_mask <= io_enq_bits_branch_mask;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        valid_reg = 1'h0;
        data_reg_pc = 32'h0;
        data_reg_inst = 32'h0;
        data_reg_aluOp = 13'h0;
        data_reg_mduOp = 7'h0;
        data_reg_brType = 9'h0;
        data_reg_imm = 32'h0;
        data_reg_src1IsPC = 1'h0;
        data_reg_src2IsImm = 1'h0;
        data_reg_src2IsFour = 1'h0;
        data_reg_src1_addr = 5'h0;
        data_reg_resFromMulDiv = 1'h0;
        data_reg_memWe = 1'h0;
        data_reg_lsOp = 8'h0;
        data_reg_resFromMem = 1'h0;
        data_reg_regWriteEn = 1'h0;
        data_reg_aux_data = 32'h0;
        data_reg_hasException = 1'h0;
        data_reg_ecode = 6'h0;
        data_reg_isCsr = 1'h0;
        data_reg_csrWe = 1'h0;
        data_reg_csrNum = 14'h0;
        data_reg_inst_ertn = 1'h0;
        data_reg_rdtimel = 1'h0;
        data_reg_rdtimeh = 1'h0;
        data_reg_tlbOp = 5'h0;
        data_reg_invtlb_op = 5'h0;
        data_reg_is_refetch = 1'h0;
        data_reg_is_cacop = 1'h0;
        data_reg_cacop_op = 5'h0;
        data_reg_rob_idx = 5'h0;
        data_reg_src1_read = 1'h0;
        data_reg_src2_read = 1'h0;
        data_reg_pdest = 6'h0;
        data_reg_psrc1 = 6'h0;
        data_reg_psrc2 = 6'h0;
        data_reg_is_branch = 1'h0;
        data_reg_branch_tag = 2'h0;
        data_reg_branch_mask = 4'h0;
        data_reg_lsq_idx = 4'h0;
        data_reg_pred_taken = 1'h0;
        data_reg_pred_target = 32'h0;
        data_reg_bpu_type = 2'h0;
        data_reg_ghr = 10'h0;
        data_reg_ras_tos = 4'h0;
        data_reg_br_actual_taken = 1'h0;
        data_reg_br_type = 2'h0;
        data_reg_bimodal_pred = 1'h0;
        data_reg_gshare_pred = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = allow_in;
  assign io_deq_valid = valid_reg & ~current_is_killed;
  assign io_deq_bits_pc = data_reg_pc;
  assign io_deq_bits_inst = data_reg_inst;
  assign io_deq_bits_aluOp = data_reg_aluOp;
  assign io_deq_bits_mduOp = data_reg_mduOp;
  assign io_deq_bits_brType = data_reg_brType;
  assign io_deq_bits_imm = data_reg_imm;
  assign io_deq_bits_src1IsPC = data_reg_src1IsPC;
  assign io_deq_bits_src2IsImm = data_reg_src2IsImm;
  assign io_deq_bits_src2IsFour = data_reg_src2IsFour;
  assign io_deq_bits_src1_addr = data_reg_src1_addr;
  assign io_deq_bits_resFromMulDiv = data_reg_resFromMulDiv;
  assign io_deq_bits_memWe = data_reg_memWe;
  assign io_deq_bits_lsOp = data_reg_lsOp;
  assign io_deq_bits_resFromMem = data_reg_resFromMem;
  assign io_deq_bits_regWriteEn = data_reg_regWriteEn;
  assign io_deq_bits_aux_data = data_reg_aux_data;
  assign io_deq_bits_hasException = data_reg_hasException;
  assign io_deq_bits_ecode = data_reg_ecode;
  assign io_deq_bits_isCsr = data_reg_isCsr;
  assign io_deq_bits_csrWe = data_reg_csrWe;
  assign io_deq_bits_csrNum = data_reg_csrNum;
  assign io_deq_bits_inst_ertn = data_reg_inst_ertn;
  assign io_deq_bits_rdtimel = data_reg_rdtimel;
  assign io_deq_bits_rdtimeh = data_reg_rdtimeh;
  assign io_deq_bits_tlbOp = data_reg_tlbOp;
  assign io_deq_bits_invtlb_op = data_reg_invtlb_op;
  assign io_deq_bits_is_refetch = data_reg_is_refetch;
  assign io_deq_bits_is_cacop = data_reg_is_cacop;
  assign io_deq_bits_cacop_op = data_reg_cacop_op;
  assign io_deq_bits_rob_idx = data_reg_rob_idx;
  assign io_deq_bits_src1_read = data_reg_src1_read;
  assign io_deq_bits_src2_read = data_reg_src2_read;
  assign io_deq_bits_pdest = data_reg_pdest;
  assign io_deq_bits_psrc1 = data_reg_psrc1;
  assign io_deq_bits_psrc2 = data_reg_psrc2;
  assign io_deq_bits_is_branch = data_reg_is_branch;
  assign io_deq_bits_branch_tag = data_reg_branch_tag;
  assign io_deq_bits_branch_mask =
    ({4{~_GEN}} | ~(_clear_mask_T_1[3:0])) & data_reg_branch_mask;
  assign io_deq_bits_lsq_idx = data_reg_lsq_idx;
  assign io_deq_bits_pred_taken = data_reg_pred_taken;
  assign io_deq_bits_pred_target = data_reg_pred_target;
  assign io_deq_bits_bpu_type = data_reg_bpu_type;
  assign io_deq_bits_ghr = data_reg_ghr;
  assign io_deq_bits_ras_tos = data_reg_ras_tos;
  assign io_deq_bits_br_actual_taken = data_reg_br_actual_taken;
  assign io_deq_bits_br_type = data_reg_br_type;
  assign io_deq_bits_bimodal_pred = data_reg_bimodal_pred;
  assign io_deq_bits_gshare_pred = data_reg_gshare_pred;
endmodule

