// Generated by CIRCT firtool-1.139.0
module LsqDcacheSkidBuffer(
  input         clock,
                reset,
                io_flush,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [7:0]  io_enq_bits_req_id,
  input         io_enq_bits_op,
  input  [31:0] io_enq_bits_addr,
  input  [3:0]  io_enq_bits_wstrb,
  input  [31:0] io_enq_bits_wdata,
  input         io_enq_bits_uncached,
                io_enq_bits_cacop_en,
  input  [1:0]  io_enq_bits_cacop_op,
  input         io_deq_ready,
  output        io_deq_valid,
  output [7:0]  io_deq_bits_req_id,
  output        io_deq_bits_op,
  output [31:0] io_deq_bits_addr,
  output [3:0]  io_deq_bits_wstrb,
  output [31:0] io_deq_bits_wdata,
  output        io_deq_bits_uncached,
                io_deq_bits_cacop_en,
  output [1:0]  io_deq_bits_cacop_op
);

  reg  [7:0]  q_0_req_id;
  reg         q_0_op;
  reg  [31:0] q_0_addr;
  reg  [3:0]  q_0_wstrb;
  reg  [31:0] q_0_wdata;
  reg         q_0_uncached;
  reg         q_0_cacop_en;
  reg  [1:0]  q_0_cacop_op;
  reg  [7:0]  q_1_req_id;
  reg         q_1_op;
  reg  [31:0] q_1_addr;
  reg  [3:0]  q_1_wstrb;
  reg  [31:0] q_1_wdata;
  reg         q_1_uncached;
  reg         q_1_cacop_en;
  reg  [1:0]  q_1_cacop_op;
  reg         head;
  reg         tail;
  reg  [1:0]  count;
  wire        do_enq = io_enq_valid & ~(count[1]);
  wire        do_deq = (|count) & io_deq_ready;
  wire        _GEN = do_enq & ~do_deq;
  wire        _GEN_0 = ~do_enq & do_deq;
  wire        _GEN_1 = do_enq & do_deq;
  always @(posedge clock) begin
    if (io_flush | (_GEN ? tail : _GEN_0 | ~(_GEN_1 & ~tail))) begin
    end
    else begin
      q_0_req_id <= io_enq_bits_req_id;
      q_0_op <= io_enq_bits_op;
      q_0_addr <= io_enq_bits_addr;
      q_0_wstrb <= io_enq_bits_wstrb;
      q_0_wdata <= io_enq_bits_wdata;
      q_0_uncached <= io_enq_bits_uncached;
      q_0_cacop_en <= io_enq_bits_cacop_en;
      q_0_cacop_op <= io_enq_bits_cacop_op;
    end
    if (io_flush) begin
    end
    else if (_GEN) begin
      if (tail) begin
        q_1_req_id <= io_enq_bits_req_id;
        q_1_op <= io_enq_bits_op;
        q_1_addr <= io_enq_bits_addr;
        q_1_wstrb <= io_enq_bits_wstrb;
        q_1_wdata <= io_enq_bits_wdata;
        q_1_uncached <= io_enq_bits_uncached;
        q_1_cacop_en <= io_enq_bits_cacop_en;
        q_1_cacop_op <= io_enq_bits_cacop_op;
      end
    end
    else if (_GEN_0 | ~(_GEN_1 & tail)) begin
    end
    else begin
      q_1_req_id <= io_enq_bits_req_id;
      q_1_op <= io_enq_bits_op;
      q_1_addr <= io_enq_bits_addr;
      q_1_wstrb <= io_enq_bits_wstrb;
      q_1_wdata <= io_enq_bits_wdata;
      q_1_uncached <= io_enq_bits_uncached;
      q_1_cacop_en <= io_enq_bits_cacop_en;
      q_1_cacop_op <= io_enq_bits_cacop_op;
    end
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      head <= 1'h0;
      tail <= 1'h0;
      count <= 2'h0;
    end
    else begin
      head <=
        ~io_flush & (_GEN ? head : _GEN_0 ? head - 1'h1 : _GEN_1 ? head - 1'h1 : head);
      tail <= ~io_flush & (_GEN ? tail - 1'h1 : _GEN_0 | ~_GEN_1 ? tail : tail - 1'h1);
      if (io_flush)
        count <= 2'h0;
      else if (_GEN)
        count <= count + 2'h1;
      else if (_GEN_0)
        count <= count - 2'h1;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        head = 1'h0;
        tail = 1'h0;
        count = 2'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~(count[1]);
  assign io_deq_valid = |count;
  assign io_deq_bits_req_id = head ? q_1_req_id : q_0_req_id;
  assign io_deq_bits_op = head ? q_1_op : q_0_op;
  assign io_deq_bits_addr = head ? q_1_addr : q_0_addr;
  assign io_deq_bits_wstrb = head ? q_1_wstrb : q_0_wstrb;
  assign io_deq_bits_wdata = head ? q_1_wdata : q_0_wdata;
  assign io_deq_bits_uncached = head ? q_1_uncached : q_0_uncached;
  assign io_deq_bits_cacop_en = head ? q_1_cacop_en : q_0_cacop_en;
  assign io_deq_bits_cacop_op = head ? q_1_cacop_op : q_0_cacop_op;
endmodule

