// Generated by CIRCT firtool-1.139.0
module MaskedQueue(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_pc,
                io_enq_bits_src2_value,
  input         io_enq_bits_memWe,
                io_enq_bits_resFromMem,
                io_enq_bits_regWriteEn,
  input  [31:0] io_enq_bits_ex_result,
                io_enq_bits_aux_data,
  input         io_enq_bits_hasException,
  input  [5:0]  io_enq_bits_ecode,
  input         io_enq_bits_isCsr,
                io_enq_bits_csrWe,
  input  [13:0] io_enq_bits_csrNum,
  input         io_enq_bits_inst_ertn,
  input  [4:0]  io_enq_bits_tlbOp,
  input         io_enq_bits_is_refetch,
                io_enq_bits_is_cacop,
  input  [4:0]  io_enq_bits_rob_idx,
  input  [5:0]  io_enq_bits_pdest,
  input         io_enq_bits_is_branch,
  input  [3:0]  io_enq_bits_branch_mask,
  input  [9:0]  io_enq_bits_ghr,
  input         io_enq_bits_br_actual_taken,
  input  [1:0]  io_enq_bits_br_type,
  input         io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_pc,
                io_deq_bits_src2_value,
  output        io_deq_bits_memWe,
                io_deq_bits_resFromMem,
                io_deq_bits_regWriteEn,
  output [31:0] io_deq_bits_ex_result,
                io_deq_bits_aux_data,
  output        io_deq_bits_hasException,
  output [5:0]  io_deq_bits_ecode,
  output        io_deq_bits_isCsr,
                io_deq_bits_csrWe,
  output [13:0] io_deq_bits_csrNum,
  output        io_deq_bits_inst_ertn,
  output [4:0]  io_deq_bits_tlbOp,
  output        io_deq_bits_is_refetch,
                io_deq_bits_is_cacop,
  output [4:0]  io_deq_bits_rob_idx,
  output [5:0]  io_deq_bits_pdest,
  output        io_deq_bits_is_branch,
  output [9:0]  io_deq_bits_ghr,
  output        io_deq_bits_br_actual_taken,
  output [1:0]  io_deq_bits_br_type,
  input         io_flush,
                io_br_resolve_in_valid,
                io_br_resolve_in_mispredict,
  input  [1:0]  io_br_resolve_in_tag
);

  reg         valid_0;
  reg  [31:0] data_0_pc;
  reg  [31:0] data_0_src2_value;
  reg         data_0_memWe;
  reg         data_0_resFromMem;
  reg         data_0_regWriteEn;
  reg  [31:0] data_0_ex_result;
  reg  [31:0] data_0_aux_data;
  reg         data_0_hasException;
  reg  [5:0]  data_0_ecode;
  reg         data_0_isCsr;
  reg         data_0_csrWe;
  reg  [13:0] data_0_csrNum;
  reg         data_0_inst_ertn;
  reg  [4:0]  data_0_tlbOp;
  reg         data_0_is_refetch;
  reg         data_0_is_cacop;
  reg  [4:0]  data_0_rob_idx;
  reg  [5:0]  data_0_pdest;
  reg         data_0_is_branch;
  reg  [3:0]  data_0_branch_mask;
  reg  [9:0]  data_0_ghr;
  reg         data_0_br_actual_taken;
  reg  [1:0]  data_0_br_type;
  reg         valid_1;
  reg  [31:0] data_1_pc;
  reg  [31:0] data_1_src2_value;
  reg         data_1_memWe;
  reg         data_1_resFromMem;
  reg         data_1_regWriteEn;
  reg  [31:0] data_1_ex_result;
  reg  [31:0] data_1_aux_data;
  reg         data_1_hasException;
  reg  [5:0]  data_1_ecode;
  reg         data_1_isCsr;
  reg         data_1_csrWe;
  reg  [13:0] data_1_csrNum;
  reg         data_1_inst_ertn;
  reg  [4:0]  data_1_tlbOp;
  reg         data_1_is_refetch;
  reg         data_1_is_cacop;
  reg  [4:0]  data_1_rob_idx;
  reg  [5:0]  data_1_pdest;
  reg         data_1_is_branch;
  reg  [3:0]  data_1_branch_mask;
  reg  [9:0]  data_1_ghr;
  reg         data_1_br_actual_taken;
  reg  [1:0]  data_1_br_type;
  wire        br_fail = io_br_resolve_in_valid & io_br_resolve_in_mispredict;
  wire [6:0]  br_tag_bit = 7'h1 << io_br_resolve_in_tag;
  wire        keep_0 = valid_0 & ~(br_fail & (|(br_tag_bit[3:0] & data_0_branch_mask)));
  wire        keep_1 = valid_1 & ~(br_fail & (|(br_tag_bit[3:0] & data_1_branch_mask)));
  wire        do_deq = io_deq_ready & keep_0;
  wire [1:0]  _slots_used_T_4 = {1'h0, keep_0 & ~do_deq} + {1'h0, keep_1};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_0 <= 1'h0;
      data_0_pc <= 32'h0;
      data_0_src2_value <= 32'h0;
      data_0_memWe <= 1'h0;
      data_0_resFromMem <= 1'h0;
      data_0_regWriteEn <= 1'h0;
      data_0_ex_result <= 32'h0;
      data_0_aux_data <= 32'h0;
      data_0_hasException <= 1'h0;
      data_0_ecode <= 6'h0;
      data_0_isCsr <= 1'h0;
      data_0_csrWe <= 1'h0;
      data_0_csrNum <= 14'h0;
      data_0_inst_ertn <= 1'h0;
      data_0_tlbOp <= 5'h0;
      data_0_is_refetch <= 1'h0;
      data_0_is_cacop <= 1'h0;
      data_0_rob_idx <= 5'h0;
      data_0_pdest <= 6'h0;
      data_0_is_branch <= 1'h0;
      data_0_branch_mask <= 4'h0;
      data_0_ghr <= 10'h0;
      data_0_br_actual_taken <= 1'h0;
      data_0_br_type <= 2'h0;
      valid_1 <= 1'h0;
      data_1_pc <= 32'h0;
      data_1_src2_value <= 32'h0;
      data_1_memWe <= 1'h0;
      data_1_resFromMem <= 1'h0;
      data_1_regWriteEn <= 1'h0;
      data_1_ex_result <= 32'h0;
      data_1_aux_data <= 32'h0;
      data_1_hasException <= 1'h0;
      data_1_ecode <= 6'h0;
      data_1_isCsr <= 1'h0;
      data_1_csrWe <= 1'h0;
      data_1_csrNum <= 14'h0;
      data_1_inst_ertn <= 1'h0;
      data_1_tlbOp <= 5'h0;
      data_1_is_refetch <= 1'h0;
      data_1_is_cacop <= 1'h0;
      data_1_rob_idx <= 5'h0;
      data_1_pdest <= 6'h0;
      data_1_is_branch <= 1'h0;
      data_1_branch_mask <= 4'h0;
      data_1_ghr <= 10'h0;
      data_1_br_actual_taken <= 1'h0;
      data_1_br_type <= 2'h0;
    end
    else begin
      automatic logic [3:0] _GEN;
      automatic logic [3:0] clean_enq_data_branch_mask;
      automatic logic [3:0] clean_data_1_branch_mask;
      automatic logic [2:0] v_bits;
      automatic logic       _GEN_0;
      automatic logic       _GEN_1;
      automatic logic       _GEN_2;
      automatic logic       _GEN_3;
      automatic logic       _GEN_4;
      automatic logic       _GEN_5;
      automatic logic       _GEN_6;
      automatic logic       _GEN_7;
      automatic logic       _GEN_8;
      automatic logic       _GEN_9;
      automatic logic       _GEN_10;
      automatic logic       _GEN_11;
      _GEN = {4{io_br_resolve_in_valid & ~io_br_resolve_in_mispredict}} & br_tag_bit[3:0];
      clean_enq_data_branch_mask = ~_GEN & io_enq_bits_branch_mask;
      clean_data_1_branch_mask = ~_GEN & data_1_branch_mask;
      v_bits =
        {~(_slots_used_T_4[1]) & io_enq_valid
           & ~(br_fail & (|(br_tag_bit[3:0] & io_enq_bits_branch_mask))),
         keep_1,
         keep_0 & ~do_deq};
      _GEN_0 = v_bits == 3'h0;
      _GEN_1 = v_bits == 3'h1;
      _GEN_2 = v_bits == 3'h2;
      _GEN_3 = v_bits == 3'h4;
      _GEN_4 = v_bits == 3'h3;
      _GEN_5 = v_bits == 3'h5;
      _GEN_6 = v_bits == 3'h6;
      _GEN_7 = _GEN_4 | _GEN_5;
      _GEN_8 = io_flush | _GEN_0;
      _GEN_9 = _GEN_5 | _GEN_6;
      _GEN_10 = io_flush | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3;
      _GEN_11 = _GEN_10 | _GEN_4 | ~_GEN_9;
      valid_0 <= ~_GEN_8 & (_GEN_1 | _GEN_2 | _GEN_3 | _GEN_7 | _GEN_6);
      if (~(_GEN_8 | _GEN_1)) begin
        if (_GEN_2) begin
          data_0_pc <= data_1_pc;
          data_0_src2_value <= data_1_src2_value;
          data_0_memWe <= data_1_memWe;
          data_0_resFromMem <= data_1_resFromMem;
          data_0_regWriteEn <= data_1_regWriteEn;
          data_0_ex_result <= data_1_ex_result;
          data_0_aux_data <= data_1_aux_data;
          data_0_hasException <= data_1_hasException;
          data_0_ecode <= data_1_ecode;
          data_0_isCsr <= data_1_isCsr;
          data_0_csrWe <= data_1_csrWe;
          data_0_csrNum <= data_1_csrNum;
          data_0_inst_ertn <= data_1_inst_ertn;
          data_0_tlbOp <= data_1_tlbOp;
          data_0_is_refetch <= data_1_is_refetch;
          data_0_is_cacop <= data_1_is_cacop;
          data_0_rob_idx <= data_1_rob_idx;
          data_0_pdest <= data_1_pdest;
          data_0_is_branch <= data_1_is_branch;
          data_0_ghr <= data_1_ghr;
          data_0_br_actual_taken <= data_1_br_actual_taken;
          data_0_br_type <= data_1_br_type;
        end
        else if (_GEN_3) begin
          data_0_pc <= io_enq_bits_pc;
          data_0_src2_value <= io_enq_bits_src2_value;
          data_0_memWe <= io_enq_bits_memWe;
          data_0_resFromMem <= io_enq_bits_resFromMem;
          data_0_regWriteEn <= io_enq_bits_regWriteEn;
          data_0_ex_result <= io_enq_bits_ex_result;
          data_0_aux_data <= io_enq_bits_aux_data;
          data_0_hasException <= io_enq_bits_hasException;
          data_0_ecode <= io_enq_bits_ecode;
          data_0_isCsr <= io_enq_bits_isCsr;
          data_0_csrWe <= io_enq_bits_csrWe;
          data_0_csrNum <= io_enq_bits_csrNum;
          data_0_inst_ertn <= io_enq_bits_inst_ertn;
          data_0_tlbOp <= io_enq_bits_tlbOp;
          data_0_is_refetch <= io_enq_bits_is_refetch;
          data_0_is_cacop <= io_enq_bits_is_cacop;
          data_0_rob_idx <= io_enq_bits_rob_idx;
          data_0_pdest <= io_enq_bits_pdest;
          data_0_is_branch <= io_enq_bits_is_branch;
          data_0_ghr <= io_enq_bits_ghr;
          data_0_br_actual_taken <= io_enq_bits_br_actual_taken;
          data_0_br_type <= io_enq_bits_br_type;
        end
        else if (_GEN_7 | ~_GEN_6) begin
        end
        else begin
          data_0_pc <= data_1_pc;
          data_0_src2_value <= data_1_src2_value;
          data_0_memWe <= data_1_memWe;
          data_0_resFromMem <= data_1_resFromMem;
          data_0_regWriteEn <= data_1_regWriteEn;
          data_0_ex_result <= data_1_ex_result;
          data_0_aux_data <= data_1_aux_data;
          data_0_hasException <= data_1_hasException;
          data_0_ecode <= data_1_ecode;
          data_0_isCsr <= data_1_isCsr;
          data_0_csrWe <= data_1_csrWe;
          data_0_csrNum <= data_1_csrNum;
          data_0_inst_ertn <= data_1_inst_ertn;
          data_0_tlbOp <= data_1_tlbOp;
          data_0_is_refetch <= data_1_is_refetch;
          data_0_is_cacop <= data_1_is_cacop;
          data_0_rob_idx <= data_1_rob_idx;
          data_0_pdest <= data_1_pdest;
          data_0_is_branch <= data_1_is_branch;
          data_0_ghr <= data_1_ghr;
          data_0_br_actual_taken <= data_1_br_actual_taken;
          data_0_br_type <= data_1_br_type;
        end
      end
      if (~_GEN_8) begin
        automatic logic [3:0]      out_data_branch_mask;
        automatic logic [7:0][3:0] _GEN_12;
        out_data_branch_mask = ~_GEN & data_0_branch_mask;
        _GEN_12 =
          {{data_0_branch_mask},
           {clean_data_1_branch_mask},
           {out_data_branch_mask},
           {clean_enq_data_branch_mask},
           {out_data_branch_mask},
           {clean_data_1_branch_mask},
           {out_data_branch_mask},
           {data_0_branch_mask}};
        data_0_branch_mask <= _GEN_12[v_bits];
      end
      valid_1 <= ~_GEN_10 & (_GEN_7 | _GEN_6);
      if (_GEN_11) begin
      end
      else begin
        data_1_pc <= io_enq_bits_pc;
        data_1_src2_value <= io_enq_bits_src2_value;
        data_1_memWe <= io_enq_bits_memWe;
        data_1_resFromMem <= io_enq_bits_resFromMem;
        data_1_regWriteEn <= io_enq_bits_regWriteEn;
        data_1_ex_result <= io_enq_bits_ex_result;
        data_1_aux_data <= io_enq_bits_aux_data;
        data_1_hasException <= io_enq_bits_hasException;
        data_1_ecode <= io_enq_bits_ecode;
        data_1_isCsr <= io_enq_bits_isCsr;
        data_1_csrWe <= io_enq_bits_csrWe;
        data_1_csrNum <= io_enq_bits_csrNum;
        data_1_inst_ertn <= io_enq_bits_inst_ertn;
        data_1_tlbOp <= io_enq_bits_tlbOp;
        data_1_is_refetch <= io_enq_bits_is_refetch;
        data_1_is_cacop <= io_enq_bits_is_cacop;
        data_1_rob_idx <= io_enq_bits_rob_idx;
        data_1_pdest <= io_enq_bits_pdest;
        data_1_is_branch <= io_enq_bits_is_branch;
      end
      if (~_GEN_10) begin
        if (_GEN_4)
          data_1_branch_mask <= clean_data_1_branch_mask;
        else if (_GEN_9)
          data_1_branch_mask <= clean_enq_data_branch_mask;
      end
      if (_GEN_11) begin
      end
      else begin
        data_1_ghr <= io_enq_bits_ghr;
        data_1_br_actual_taken <= io_enq_bits_br_actual_taken;
        data_1_br_type <= io_enq_bits_br_type;
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        valid_0 = 1'h0;
        data_0_pc = 32'h0;
        data_0_src2_value = 32'h0;
        data_0_memWe = 1'h0;
        data_0_resFromMem = 1'h0;
        data_0_regWriteEn = 1'h0;
        data_0_ex_result = 32'h0;
        data_0_aux_data = 32'h0;
        data_0_hasException = 1'h0;
        data_0_ecode = 6'h0;
        data_0_isCsr = 1'h0;
        data_0_csrWe = 1'h0;
        data_0_csrNum = 14'h0;
        data_0_inst_ertn = 1'h0;
        data_0_tlbOp = 5'h0;
        data_0_is_refetch = 1'h0;
        data_0_is_cacop = 1'h0;
        data_0_rob_idx = 5'h0;
        data_0_pdest = 6'h0;
        data_0_is_branch = 1'h0;
        data_0_branch_mask = 4'h0;
        data_0_ghr = 10'h0;
        data_0_br_actual_taken = 1'h0;
        data_0_br_type = 2'h0;
        valid_1 = 1'h0;
        data_1_pc = 32'h0;
        data_1_src2_value = 32'h0;
        data_1_memWe = 1'h0;
        data_1_resFromMem = 1'h0;
        data_1_regWriteEn = 1'h0;
        data_1_ex_result = 32'h0;
        data_1_aux_data = 32'h0;
        data_1_hasException = 1'h0;
        data_1_ecode = 6'h0;
        data_1_isCsr = 1'h0;
        data_1_csrWe = 1'h0;
        data_1_csrNum = 14'h0;
        data_1_inst_ertn = 1'h0;
        data_1_tlbOp = 5'h0;
        data_1_is_refetch = 1'h0;
        data_1_is_cacop = 1'h0;
        data_1_rob_idx = 5'h0;
        data_1_pdest = 6'h0;
        data_1_is_branch = 1'h0;
        data_1_branch_mask = 4'h0;
        data_1_ghr = 10'h0;
        data_1_br_actual_taken = 1'h0;
        data_1_br_type = 2'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~(_slots_used_T_4[1]);
  assign io_deq_valid = keep_0;
  assign io_deq_bits_pc = data_0_pc;
  assign io_deq_bits_src2_value = data_0_src2_value;
  assign io_deq_bits_memWe = data_0_memWe;
  assign io_deq_bits_resFromMem = data_0_resFromMem;
  assign io_deq_bits_regWriteEn = data_0_regWriteEn;
  assign io_deq_bits_ex_result = data_0_ex_result;
  assign io_deq_bits_aux_data = data_0_aux_data;
  assign io_deq_bits_hasException = data_0_hasException;
  assign io_deq_bits_ecode = data_0_ecode;
  assign io_deq_bits_isCsr = data_0_isCsr;
  assign io_deq_bits_csrWe = data_0_csrWe;
  assign io_deq_bits_csrNum = data_0_csrNum;
  assign io_deq_bits_inst_ertn = data_0_inst_ertn;
  assign io_deq_bits_tlbOp = data_0_tlbOp;
  assign io_deq_bits_is_refetch = data_0_is_refetch;
  assign io_deq_bits_is_cacop = data_0_is_cacop;
  assign io_deq_bits_rob_idx = data_0_rob_idx;
  assign io_deq_bits_pdest = data_0_pdest;
  assign io_deq_bits_is_branch = data_0_is_branch;
  assign io_deq_bits_ghr = data_0_ghr;
  assign io_deq_bits_br_actual_taken = data_0_br_actual_taken;
  assign io_deq_bits_br_type = data_0_br_type;
endmodule

