// Generated by CIRCT firtool-1.139.0
module MduUnit(
  input         clock,
                reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [31:0] io_in_bits_pc,
  input  [6:0]  io_in_bits_mduOp,
  input  [31:0] io_in_bits_src1_value,
                io_in_bits_src2_value,
  input         io_in_bits_resFromMulDiv,
                io_in_bits_memWe,
                io_in_bits_resFromMem,
                io_in_bits_regWriteEn,
  input  [31:0] io_in_bits_aux_data,
  input         io_in_bits_hasException,
  input  [5:0]  io_in_bits_ecode,
  input         io_in_bits_isCsr,
                io_in_bits_csrWe,
  input  [13:0] io_in_bits_csrNum,
  input         io_in_bits_inst_ertn,
  input  [4:0]  io_in_bits_tlbOp,
  input         io_in_bits_is_refetch,
                io_in_bits_is_cacop,
  input  [4:0]  io_in_bits_rob_idx,
  input  [5:0]  io_in_bits_pdest,
  input  [3:0]  io_in_bits_branch_mask,
  input         io_out_ready,
  output        io_out_valid,
  output [31:0] io_out_bits_pc,
                io_out_bits_src2_value,
  output        io_out_bits_memWe,
                io_out_bits_resFromMem,
                io_out_bits_regWriteEn,
  output [31:0] io_out_bits_ex_result,
                io_out_bits_aux_data,
  output        io_out_bits_hasException,
  output [5:0]  io_out_bits_ecode,
  output        io_out_bits_isCsr,
                io_out_bits_csrWe,
  output [13:0] io_out_bits_csrNum,
  output        io_out_bits_inst_ertn,
  output [4:0]  io_out_bits_tlbOp,
  output        io_out_bits_is_refetch,
                io_out_bits_is_cacop,
  output [4:0]  io_out_bits_rob_idx,
  output [5:0]  io_out_bits_pdest,
  input         io_flush,
                io_br_resolve_in_valid,
                io_br_resolve_in_mispredict,
  input  [1:0]  io_br_resolve_in_tag
);

  wire [31:0] _div_io_q;
  wire [31:0] _div_io_r;
  wire        _div_io_done;
  wire [63:0] _mul_io_result64;
  wire        br_fail = io_br_resolve_in_valid & io_br_resolve_in_mispredict;
  wire [6:0]  br_tag_bit = 7'h1 << io_br_resolve_in_tag;
  reg         valid_reg;
  reg  [31:0] data_reg_pc;
  reg  [6:0]  data_reg_mduOp;
  reg  [31:0] data_reg_src1_value;
  reg  [31:0] data_reg_src2_value;
  reg         data_reg_resFromMulDiv;
  reg         data_reg_memWe;
  reg         data_reg_resFromMem;
  reg         data_reg_regWriteEn;
  reg  [31:0] data_reg_aux_data;
  reg         data_reg_hasException;
  reg  [5:0]  data_reg_ecode;
  reg         data_reg_isCsr;
  reg         data_reg_csrWe;
  reg  [13:0] data_reg_csrNum;
  reg         data_reg_inst_ertn;
  reg  [4:0]  data_reg_tlbOp;
  reg         data_reg_is_refetch;
  reg         data_reg_is_cacop;
  reg  [4:0]  data_reg_rob_idx;
  reg  [5:0]  data_reg_pdest;
  reg  [3:0]  data_reg_branch_mask;
  wire [3:0]  _GEN = br_tag_bit[3:0] & data_reg_branch_mask;
  wire        active = valid_reg & ~(br_fail & (|_GEN));
  reg         mdu_busy;
  reg         mdu_finished;
  wire        _mdu_res_T_9 = data_reg_mduOp == 7'h8;
  wire        _mdu_res_T_11 = data_reg_mduOp == 7'h10;
  wire        _mdu_res_T_13 = data_reg_mduOp == 7'h20;
  wire        _mdu_res_T_15 = data_reg_mduOp == 7'h40;
  wire        is_div = _mdu_res_T_9 | _mdu_res_T_11 | _mdu_res_T_13 | _mdu_res_T_15;
  wire        _mdu_res_T_3 = data_reg_mduOp == 7'h1;
  wire        _mdu_res_T_5 = data_reg_mduOp == 7'h2;
  wire        _mdu_res_T_7 = data_reg_mduOp == 7'h4;
  wire        is_signed = _mdu_res_T_5 | _mdu_res_T_9 | _mdu_res_T_11;
  wire        valid_mdu_req = active & data_reg_resFromMulDiv & ~data_reg_hasException;
  wire        start_pulse = valid_mdu_req & ~mdu_busy & ~mdu_finished & ~io_flush;
  reg         mul_done;
  wire        math_done =
    ~valid_mdu_req | mdu_finished | mdu_busy & (is_div ? _div_io_done : mul_done);
  wire        in_ready = ~active | math_done & io_out_ready;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_reg <= 1'h0;
      data_reg_pc <= 32'h0;
      data_reg_mduOp <= 7'h0;
      data_reg_src1_value <= 32'h0;
      data_reg_src2_value <= 32'h0;
      data_reg_resFromMulDiv <= 1'h0;
      data_reg_memWe <= 1'h0;
      data_reg_resFromMem <= 1'h0;
      data_reg_regWriteEn <= 1'h0;
      data_reg_aux_data <= 32'h0;
      data_reg_hasException <= 1'h0;
      data_reg_ecode <= 6'h0;
      data_reg_isCsr <= 1'h0;
      data_reg_csrWe <= 1'h0;
      data_reg_csrNum <= 14'h0;
      data_reg_inst_ertn <= 1'h0;
      data_reg_tlbOp <= 5'h0;
      data_reg_is_refetch <= 1'h0;
      data_reg_is_cacop <= 1'h0;
      data_reg_rob_idx <= 5'h0;
      data_reg_pdest <= 6'h0;
      data_reg_branch_mask <= 4'h0;
      mdu_busy <= 1'h0;
      mdu_finished <= 1'h0;
      mul_done <= 1'h0;
    end
    else begin
      automatic logic _GEN_0 = br_fail & (|_GEN);
      automatic logic _GEN_1;
      automatic logic _GEN_2 = io_flush | in_ready | _GEN_0;
      _GEN_1 = mdu_busy & (_div_io_done | mul_done);
      valid_reg <=
        ~io_flush
        & (in_ready
             ? io_in_valid & ~(br_fail & (|(br_tag_bit[3:0] & io_in_bits_branch_mask)))
             : ~_GEN_0 & valid_reg);
      if (io_flush | ~in_ready) begin
      end
      else begin
        data_reg_pc <= io_in_bits_pc;
        data_reg_mduOp <= io_in_bits_mduOp;
        data_reg_src1_value <= io_in_bits_src1_value;
        data_reg_src2_value <= io_in_bits_src2_value;
        data_reg_resFromMulDiv <= io_in_bits_resFromMulDiv;
        data_reg_memWe <= io_in_bits_memWe;
        data_reg_resFromMem <= io_in_bits_resFromMem;
        data_reg_regWriteEn <= io_in_bits_regWriteEn;
        data_reg_aux_data <= io_in_bits_aux_data;
        data_reg_hasException <= io_in_bits_hasException;
        data_reg_ecode <= io_in_bits_ecode;
        data_reg_isCsr <= io_in_bits_isCsr;
        data_reg_csrWe <= io_in_bits_csrWe;
        data_reg_csrNum <= io_in_bits_csrNum;
        data_reg_inst_ertn <= io_in_bits_inst_ertn;
        data_reg_tlbOp <= io_in_bits_tlbOp;
        data_reg_is_refetch <= io_in_bits_is_refetch;
        data_reg_is_cacop <= io_in_bits_is_cacop;
        data_reg_rob_idx <= io_in_bits_rob_idx;
        data_reg_pdest <= io_in_bits_pdest;
      end
      if (io_flush) begin
      end
      else begin
        automatic logic [3:0] _GEN_3 =
          {4{io_br_resolve_in_valid & ~io_br_resolve_in_mispredict}} & br_tag_bit[3:0];
        data_reg_branch_mask <=
          in_ready ? ~_GEN_3 & io_in_bits_branch_mask : ~_GEN_3 & data_reg_branch_mask;
      end
      mdu_busy <= ~_GEN_2 & (start_pulse | ~_GEN_1 & mdu_busy);
      mdu_finished <= ~_GEN_2 & (~start_pulse & _GEN_1 | mdu_finished);
      mul_done <= start_pulse & (_mdu_res_T_3 | _mdu_res_T_5 | _mdu_res_T_7);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        valid_reg = 1'h0;
        data_reg_pc = 32'h0;
        data_reg_mduOp = 7'h0;
        data_reg_src1_value = 32'h0;
        data_reg_src2_value = 32'h0;
        data_reg_resFromMulDiv = 1'h0;
        data_reg_memWe = 1'h0;
        data_reg_resFromMem = 1'h0;
        data_reg_regWriteEn = 1'h0;
        data_reg_aux_data = 32'h0;
        data_reg_hasException = 1'h0;
        data_reg_ecode = 6'h0;
        data_reg_isCsr = 1'h0;
        data_reg_csrWe = 1'h0;
        data_reg_csrNum = 14'h0;
        data_reg_inst_ertn = 1'h0;
        data_reg_tlbOp = 5'h0;
        data_reg_is_refetch = 1'h0;
        data_reg_is_cacop = 1'h0;
        data_reg_rob_idx = 5'h0;
        data_reg_pdest = 6'h0;
        data_reg_branch_mask = 4'h0;
        mdu_busy = 1'h0;
        mdu_finished = 1'h0;
        mul_done = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Multiplier mul (
    .clock       (clock),
    .io_src1     (data_reg_src1_value),
    .io_src2     (data_reg_src2_value),
    .io_isSigned (is_signed),
    .io_result64 (_mul_io_result64)
  );
  Divider div (
    .clock      (clock),
    .io_enable  (start_pulse & is_div),
    .io_aresetn (~(io_flush | br_fail & (|_GEN))),
    .io_a
      (is_signed & data_reg_src1_value[31]
         ? ~data_reg_src1_value + 32'h1
         : data_reg_src1_value),
    .io_b
      (is_signed & data_reg_src2_value[31]
         ? ~data_reg_src2_value + 32'h1
         : data_reg_src2_value),
    .io_q       (_div_io_q),
    .io_r       (_div_io_r),
    .io_done    (_div_io_done)
  );
  assign io_in_ready = in_ready;
  assign io_out_valid = active & math_done;
  assign io_out_bits_pc = data_reg_pc;
  assign io_out_bits_src2_value = data_reg_src2_value;
  assign io_out_bits_memWe = data_reg_memWe;
  assign io_out_bits_resFromMem = data_reg_resFromMem;
  assign io_out_bits_regWriteEn = data_reg_regWriteEn;
  assign io_out_bits_ex_result =
    _mdu_res_T_15
      ? _div_io_r
      : _mdu_res_T_13
          ? _div_io_q
          : _mdu_res_T_11
              ? (is_signed & data_reg_src1_value[31] ? ~_div_io_r + 32'h1 : _div_io_r)
              : _mdu_res_T_9
                  ? (is_signed & (data_reg_src1_value[31] ^ data_reg_src2_value[31])
                       ? ~_div_io_q + 32'h1
                       : _div_io_q)
                  : _mdu_res_T_7 | _mdu_res_T_5
                      ? _mul_io_result64[63:32]
                      : _mdu_res_T_3 ? _mul_io_result64[31:0] : 32'h0;
  assign io_out_bits_aux_data = data_reg_aux_data;
  assign io_out_bits_hasException = data_reg_hasException;
  assign io_out_bits_ecode = data_reg_ecode;
  assign io_out_bits_isCsr = data_reg_isCsr;
  assign io_out_bits_csrWe = data_reg_csrWe;
  assign io_out_bits_csrNum = data_reg_csrNum;
  assign io_out_bits_inst_ertn = data_reg_inst_ertn;
  assign io_out_bits_tlbOp = data_reg_tlbOp;
  assign io_out_bits_is_refetch = data_reg_is_refetch;
  assign io_out_bits_is_cacop = data_reg_is_cacop;
  assign io_out_bits_rob_idx = data_reg_rob_idx;
  assign io_out_bits_pdest = data_reg_pdest;
endmodule

