// Generated by CIRCT firtool-1.139.0
module Multiplier(
  input         clock,
  input  [31:0] io_src1,
                io_src2,
  input         io_isSigned,
  output [63:0] io_result64
);

  reg [63:0] signedRes_REG;
  reg [63:0] unsignedRes;
  always @(posedge clock) begin
    signedRes_REG <= {{32{io_src1[31]}}, io_src1} * {{32{io_src2[31]}}, io_src2};
    unsignedRes <= {32'h0, io_src1} * {32'h0, io_src2};
  end // always @(posedge)
  assign io_result64 = io_isSigned ? signedRes_REG : unsignedRes;
endmodule

