// Generated by CIRCT firtool-1.139.0
module Queue2_AxiWChannel(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_wdata,
  input  [3:0]  io_enq_bits_wstrb,
  input         io_enq_bits_wlast,
                io_deq_ready,
  output        io_deq_valid,
  output [3:0]  io_deq_bits_wid,
  output [31:0] io_deq_bits_wdata,
  output [3:0]  io_deq_bits_wstrb,
  output        io_deq_bits_wlast
);

  wire [40:0] _ram_ext_R0_data;
  reg         enq_ptr_value;
  reg         deq_ptr_value;
  reg         maybe_full;
  wire        ptr_match = enq_ptr_value == deq_ptr_value;
  wire        empty = ptr_match & ~maybe_full;
  wire        full = ptr_match & maybe_full;
  wire        do_enq = ~full & io_enq_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      enq_ptr_value <= 1'h0;
      deq_ptr_value <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value - 1'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value - 1'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        enq_ptr_value = 1'h0;
        deq_ptr_value = 1'h0;
        maybe_full = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x41 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data ({4'h1, io_enq_bits_wdata, io_enq_bits_wstrb, io_enq_bits_wlast})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_wid = _ram_ext_R0_data[40:37];
  assign io_deq_bits_wdata = _ram_ext_R0_data[36:5];
  assign io_deq_bits_wstrb = _ram_ext_R0_data[4:1];
  assign io_deq_bits_wlast = _ram_ext_R0_data[0];
endmodule

