// Generated by CIRCT firtool-1.139.0
module Queue2_AxiBChannel(
  input  clock,
         reset,
  output io_enq_ready,
  input  io_enq_valid,
  output io_deq_valid
);

  reg  enq_ptr_value;
  reg  deq_ptr_value;
  reg  maybe_full;
  wire ptr_match = enq_ptr_value == deq_ptr_value;
  wire empty = ptr_match & ~maybe_full;
  wire full = ptr_match & maybe_full;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      enq_ptr_value <= 1'h0;
      deq_ptr_value <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_enq;
      do_enq = ~full & io_enq_valid;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value - 1'h1;
      if (~empty)
        deq_ptr_value <= deq_ptr_value - 1'h1;
      if (do_enq != ~empty)
        maybe_full <= do_enq;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        enq_ptr_value = 1'h0;
        deq_ptr_value = 1'h0;
        maybe_full = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
endmodule

