// Generated by CIRCT firtool-1.139.0
module Queue2_IfOutBundle(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
                io_enq_bits_v1,
  input  [31:0] io_enq_bits_d0_pc,
                io_enq_bits_d0_inst,
  input         io_enq_bits_d0_hasException,
  input  [5:0]  io_enq_bits_d0_ecode,
  input         io_enq_bits_d0_pred_taken,
  input  [31:0] io_enq_bits_d0_pred_target,
  input  [1:0]  io_enq_bits_d0_bpu_type,
  input  [9:0]  io_enq_bits_d0_ghr,
  input  [3:0]  io_enq_bits_d0_ras_tos,
  input  [31:0] io_enq_bits_d1_pc,
                io_enq_bits_d1_inst,
  input         io_enq_bits_d1_hasException,
  input  [5:0]  io_enq_bits_d1_ecode,
  input         io_enq_bits_d1_pred_taken,
  input  [31:0] io_enq_bits_d1_pred_target,
  input  [1:0]  io_enq_bits_d1_bpu_type,
  input  [9:0]  io_enq_bits_d1_ghr,
  input  [3:0]  io_enq_bits_d1_ras_tos,
  input         io_deq_ready,
  output        io_deq_valid,
                io_deq_bits_v0,
                io_deq_bits_v1,
  output [31:0] io_deq_bits_d0_pc,
                io_deq_bits_d0_inst,
                io_deq_bits_d0_aux_data,
  output        io_deq_bits_d0_hasException,
  output [5:0]  io_deq_bits_d0_ecode,
  output [8:0]  io_deq_bits_d0_esubcode,
  output        io_deq_bits_d0_pred_taken,
  output [31:0] io_deq_bits_d0_pred_target,
  output [1:0]  io_deq_bits_d0_bpu_type,
  output [9:0]  io_deq_bits_d0_ghr,
  output [3:0]  io_deq_bits_d0_ras_tos,
  output [31:0] io_deq_bits_d1_pc,
                io_deq_bits_d1_inst,
                io_deq_bits_d1_aux_data,
  output        io_deq_bits_d1_hasException,
  output [5:0]  io_deq_bits_d1_ecode,
  output [8:0]  io_deq_bits_d1_esubcode,
  output        io_deq_bits_d1_pred_taken,
  output [31:0] io_deq_bits_d1_pred_target,
  output [1:0]  io_deq_bits_d1_bpu_type,
  output [9:0]  io_deq_bits_d1_ghr,
  output [3:0]  io_deq_bits_d1_ras_tos
);

  wire [323:0] _ram_ext_R0_data;
  reg          enq_ptr_value;
  reg          deq_ptr_value;
  reg          maybe_full;
  wire         ptr_match = enq_ptr_value == deq_ptr_value;
  wire         empty = ptr_match & ~maybe_full;
  wire         full = ptr_match & maybe_full;
  wire         do_enq = ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 1'h0;
      deq_ptr_value <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value - 1'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value - 1'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_2x324 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({1'h1,
        io_enq_bits_v1,
        io_enq_bits_d0_pc,
        io_enq_bits_d0_inst,
        32'h0,
        io_enq_bits_d0_hasException,
        io_enq_bits_d0_ecode,
        9'h0,
        io_enq_bits_d0_pred_taken,
        io_enq_bits_d0_pred_target,
        io_enq_bits_d0_bpu_type,
        io_enq_bits_d0_ghr,
        io_enq_bits_d0_ras_tos,
        io_enq_bits_d1_pc,
        io_enq_bits_d1_inst,
        32'h0,
        io_enq_bits_d1_hasException,
        io_enq_bits_d1_ecode,
        9'h0,
        io_enq_bits_d1_pred_taken,
        io_enq_bits_d1_pred_target,
        io_enq_bits_d1_bpu_type,
        io_enq_bits_d1_ghr,
        io_enq_bits_d1_ras_tos})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_v0 = _ram_ext_R0_data[323];
  assign io_deq_bits_v1 = _ram_ext_R0_data[322];
  assign io_deq_bits_d0_pc = _ram_ext_R0_data[321:290];
  assign io_deq_bits_d0_inst = _ram_ext_R0_data[289:258];
  assign io_deq_bits_d0_aux_data = _ram_ext_R0_data[257:226];
  assign io_deq_bits_d0_hasException = _ram_ext_R0_data[225];
  assign io_deq_bits_d0_ecode = _ram_ext_R0_data[224:219];
  assign io_deq_bits_d0_esubcode = _ram_ext_R0_data[218:210];
  assign io_deq_bits_d0_pred_taken = _ram_ext_R0_data[209];
  assign io_deq_bits_d0_pred_target = _ram_ext_R0_data[208:177];
  assign io_deq_bits_d0_bpu_type = _ram_ext_R0_data[176:175];
  assign io_deq_bits_d0_ghr = _ram_ext_R0_data[174:165];
  assign io_deq_bits_d0_ras_tos = _ram_ext_R0_data[164:161];
  assign io_deq_bits_d1_pc = _ram_ext_R0_data[160:129];
  assign io_deq_bits_d1_inst = _ram_ext_R0_data[128:97];
  assign io_deq_bits_d1_aux_data = _ram_ext_R0_data[96:65];
  assign io_deq_bits_d1_hasException = _ram_ext_R0_data[64];
  assign io_deq_bits_d1_ecode = _ram_ext_R0_data[63:58];
  assign io_deq_bits_d1_esubcode = _ram_ext_R0_data[57:49];
  assign io_deq_bits_d1_pred_taken = _ram_ext_R0_data[48];
  assign io_deq_bits_d1_pred_target = _ram_ext_R0_data[47:16];
  assign io_deq_bits_d1_bpu_type = _ram_ext_R0_data[15:14];
  assign io_deq_bits_d1_ghr = _ram_ext_R0_data[13:4];
  assign io_deq_bits_d1_ras_tos = _ram_ext_R0_data[3:0];
endmodule

