// Generated by CIRCT firtool-1.139.0
module Queue1_LsqDcacheReq(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [7:0]  io_enq_bits_req_id,
  input         io_enq_bits_op,
  input  [31:0] io_enq_bits_addr,
  input  [3:0]  io_enq_bits_wstrb,
  input  [31:0] io_enq_bits_wdata,
  input         io_enq_bits_uncached,
                io_enq_bits_cacop_en,
  input  [1:0]  io_enq_bits_cacop_op,
  input         io_deq_ready,
  output        io_deq_valid,
  output [7:0]  io_deq_bits_req_id,
  output        io_deq_bits_op,
  output [31:0] io_deq_bits_addr,
  output [3:0]  io_deq_bits_wstrb,
  output [31:0] io_deq_bits_wdata,
  output        io_deq_bits_uncached,
                io_deq_bits_cacop_en,
  output [1:0]  io_deq_bits_cacop_op
);

  reg  [80:0] ram;
  reg         maybe_full;
  wire        do_enq = ~maybe_full & io_enq_valid;
  always @(posedge clock or posedge reset) begin
    if (reset)
      maybe_full <= 1'h0;
    else if (do_enq != (io_deq_ready & maybe_full))
      maybe_full <= do_enq;
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (do_enq)
      ram <=
        {io_enq_bits_req_id,
         io_enq_bits_op,
         io_enq_bits_addr,
         io_enq_bits_wstrb,
         io_enq_bits_wdata,
         io_enq_bits_uncached,
         io_enq_bits_cacop_en,
         io_enq_bits_cacop_op};
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        maybe_full = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~maybe_full;
  assign io_deq_valid = maybe_full;
  assign io_deq_bits_req_id = ram[80:73];
  assign io_deq_bits_op = ram[72];
  assign io_deq_bits_addr = ram[71:40];
  assign io_deq_bits_wstrb = ram[39:36];
  assign io_deq_bits_wdata = ram[35:4];
  assign io_deq_bits_uncached = ram[3];
  assign io_deq_bits_cacop_en = ram[2];
  assign io_deq_bits_cacop_op = ram[1:0];
endmodule

