// Generated by CIRCT firtool-1.139.0
module Queue4_Bool(
  input  clock,
         reset,
  output io_enq_ready,
  input  io_enq_valid,
         io_enq_bits,
         io_deq_ready,
  output io_deq_valid,
         io_deq_bits
);

  wire       io_enq_ready_0;
  wire       _ram_ext_R0_data;
  reg  [1:0] enq_ptr_value;
  reg  [1:0] deq_ptr_value;
  reg        maybe_full;
  wire       ptr_match = enq_ptr_value == deq_ptr_value;
  wire       empty = ptr_match & ~maybe_full;
  wire       io_deq_valid_0 = io_enq_valid | ~empty;
  wire       do_enq = ~(empty & io_deq_ready) & io_enq_ready_0 & io_enq_valid;
  assign io_enq_ready_0 = io_deq_ready | ~(ptr_match & maybe_full);
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      enq_ptr_value <= 2'h0;
      deq_ptr_value <= 2'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = ~empty & io_deq_ready & io_deq_valid_0;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value + 2'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value + 2'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        enq_ptr_value = 2'h0;
        deq_ptr_value = 2'h0;
        maybe_full = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_4x1 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
  assign io_enq_ready = io_enq_ready_0;
  assign io_deq_valid = io_deq_valid_0;
  assign io_deq_bits = empty ? io_enq_bits : _ram_ext_R0_data;
endmodule

