// Generated by CIRCT firtool-1.139.0
module Queue16_PipelineData(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_ex_result,
  input         io_enq_bits_hasException,
  input  [5:0]  io_enq_bits_ecode,
  input  [4:0]  io_enq_bits_rob_idx,
  input  [5:0]  io_enq_bits_pdest,
  input         io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_pc,
                io_deq_bits_src2_value,
  output        io_deq_bits_memWe,
                io_deq_bits_resFromMem,
                io_deq_bits_regWriteEn,
  output [31:0] io_deq_bits_ex_result,
                io_deq_bits_aux_data,
  output        io_deq_bits_hasException,
  output [5:0]  io_deq_bits_ecode,
  output        io_deq_bits_isCsr,
                io_deq_bits_csrWe,
  output [13:0] io_deq_bits_csrNum,
  output        io_deq_bits_inst_ertn,
  output [4:0]  io_deq_bits_tlbOp,
  output        io_deq_bits_is_refetch,
                io_deq_bits_is_cacop,
  output [4:0]  io_deq_bits_rob_idx,
  output [5:0]  io_deq_bits_pdest
);

  wire [172:0] _ram_ext_R0_data;
  reg  [3:0]   enq_ptr_value;
  reg  [3:0]   deq_ptr_value;
  reg          maybe_full;
  wire         ptr_match = enq_ptr_value == deq_ptr_value;
  wire         empty = ptr_match & ~maybe_full;
  wire         full = ptr_match & maybe_full;
  wire         do_enq = ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 4'h0;
      deq_ptr_value <= 4'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value + 4'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value + 4'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_16x173 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({67'h3,
        io_enq_bits_ex_result,
        32'h0,
        io_enq_bits_hasException,
        io_enq_bits_ecode,
        24'h0,
        io_enq_bits_rob_idx,
        io_enq_bits_pdest})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_pc = _ram_ext_R0_data[172:141];
  assign io_deq_bits_src2_value = _ram_ext_R0_data[140:109];
  assign io_deq_bits_memWe = _ram_ext_R0_data[108];
  assign io_deq_bits_resFromMem = _ram_ext_R0_data[107];
  assign io_deq_bits_regWriteEn = _ram_ext_R0_data[106];
  assign io_deq_bits_ex_result = _ram_ext_R0_data[105:74];
  assign io_deq_bits_aux_data = _ram_ext_R0_data[73:42];
  assign io_deq_bits_hasException = _ram_ext_R0_data[41];
  assign io_deq_bits_ecode = _ram_ext_R0_data[40:35];
  assign io_deq_bits_isCsr = _ram_ext_R0_data[34];
  assign io_deq_bits_csrWe = _ram_ext_R0_data[33];
  assign io_deq_bits_csrNum = _ram_ext_R0_data[32:19];
  assign io_deq_bits_inst_ertn = _ram_ext_R0_data[18];
  assign io_deq_bits_tlbOp = _ram_ext_R0_data[17:13];
  assign io_deq_bits_is_refetch = _ram_ext_R0_data[12];
  assign io_deq_bits_is_cacop = _ram_ext_R0_data[11];
  assign io_deq_bits_rob_idx = _ram_ext_R0_data[10:6];
  assign io_deq_bits_pdest = _ram_ext_R0_data[5:0];
endmodule

