// Generated by CIRCT firtool-1.139.0
module Queue2_LsqDcacheReq(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [7:0]  io_enq_bits_req_id,
  input         io_enq_bits_op,
  input  [31:0] io_enq_bits_addr,
  input  [3:0]  io_enq_bits_wstrb,
  input  [31:0] io_enq_bits_wdata,
  input         io_enq_bits_uncached,
                io_enq_bits_cacop_en,
  input  [1:0]  io_enq_bits_cacop_op,
  input         io_deq_ready,
  output        io_deq_valid,
  output [7:0]  io_deq_bits_req_id,
  output        io_deq_bits_op,
  output [31:0] io_deq_bits_addr,
  output [3:0]  io_deq_bits_wstrb,
  output [31:0] io_deq_bits_wdata,
  output        io_deq_bits_uncached,
                io_deq_bits_cacop_en,
  output [1:0]  io_deq_bits_cacop_op
);

  wire [80:0] _ram_ext_R0_data;
  reg         enq_ptr_value;
  reg         deq_ptr_value;
  reg         maybe_full;
  wire        ptr_match = enq_ptr_value == deq_ptr_value;
  wire        empty = ptr_match & ~maybe_full;
  wire        full = ptr_match & maybe_full;
  wire        do_enq = ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 1'h0;
      deq_ptr_value <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value - 1'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value - 1'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_2x81 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_req_id,
        io_enq_bits_op,
        io_enq_bits_addr,
        io_enq_bits_wstrb,
        io_enq_bits_wdata,
        io_enq_bits_uncached,
        io_enq_bits_cacop_en,
        io_enq_bits_cacop_op})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_req_id = _ram_ext_R0_data[80:73];
  assign io_deq_bits_op = _ram_ext_R0_data[72];
  assign io_deq_bits_addr = _ram_ext_R0_data[71:40];
  assign io_deq_bits_wstrb = _ram_ext_R0_data[39:36];
  assign io_deq_bits_wdata = _ram_ext_R0_data[35:4];
  assign io_deq_bits_uncached = _ram_ext_R0_data[3];
  assign io_deq_bits_cacop_en = _ram_ext_R0_data[2];
  assign io_deq_bits_cacop_op = _ram_ext_R0_data[1:0];
endmodule

