// Generated by CIRCT firtool-1.139.0
module Queue32_FetchMeta(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_pc,
  input         io_enq_bits_is_cross,
                io_enq_bits_has_exc,
  input  [5:0]  io_enq_bits_ecode,
  input         io_enq_bits_pred_taken0,
  input  [31:0] io_enq_bits_pred_target0,
  input  [1:0]  io_enq_bits_pred_type0,
  input         io_enq_bits_pred_taken1,
  input  [31:0] io_enq_bits_pred_target1,
  input  [1:0]  io_enq_bits_pred_type1,
  input  [9:0]  io_enq_bits_ghr,
  input  [3:0]  io_enq_bits_ras_tos,
                io_enq_bits_ras_tos1,
  input  [7:0]  io_enq_bits_ticket,
  input         io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_pc,
  output        io_deq_bits_is_cross,
                io_deq_bits_has_exc,
  output [5:0]  io_deq_bits_ecode,
  output        io_deq_bits_pred_taken0,
  output [31:0] io_deq_bits_pred_target0,
  output [1:0]  io_deq_bits_pred_type0,
  output        io_deq_bits_pred_taken1,
  output [31:0] io_deq_bits_pred_target1,
  output [1:0]  io_deq_bits_pred_type1,
  output [9:0]  io_deq_bits_ghr,
  output [3:0]  io_deq_bits_ras_tos,
                io_deq_bits_ras_tos1,
  output [7:0]  io_deq_bits_ticket
);

  wire [135:0] _ram_ext_R0_data;
  reg  [4:0]   enq_ptr_value;
  reg  [4:0]   deq_ptr_value;
  reg          maybe_full;
  wire         ptr_match = enq_ptr_value == deq_ptr_value;
  wire         empty = ptr_match & ~maybe_full;
  wire         full = ptr_match & maybe_full;
  wire         do_enq = ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 5'h0;
      deq_ptr_value <= 5'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value + 5'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value + 5'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_32x136 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_pc,
        io_enq_bits_is_cross,
        io_enq_bits_has_exc,
        io_enq_bits_ecode,
        io_enq_bits_pred_taken0,
        io_enq_bits_pred_target0,
        io_enq_bits_pred_type0,
        io_enq_bits_pred_taken1,
        io_enq_bits_pred_target1,
        io_enq_bits_pred_type1,
        io_enq_bits_ghr,
        io_enq_bits_ras_tos,
        io_enq_bits_ras_tos1,
        io_enq_bits_ticket})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_pc = _ram_ext_R0_data[135:104];
  assign io_deq_bits_is_cross = _ram_ext_R0_data[103];
  assign io_deq_bits_has_exc = _ram_ext_R0_data[102];
  assign io_deq_bits_ecode = _ram_ext_R0_data[101:96];
  assign io_deq_bits_pred_taken0 = _ram_ext_R0_data[95];
  assign io_deq_bits_pred_target0 = _ram_ext_R0_data[94:63];
  assign io_deq_bits_pred_type0 = _ram_ext_R0_data[62:61];
  assign io_deq_bits_pred_taken1 = _ram_ext_R0_data[60];
  assign io_deq_bits_pred_target1 = _ram_ext_R0_data[59:28];
  assign io_deq_bits_pred_type1 = _ram_ext_R0_data[27:26];
  assign io_deq_bits_ghr = _ram_ext_R0_data[25:16];
  assign io_deq_bits_ras_tos = _ram_ext_R0_data[15:12];
  assign io_deq_bits_ras_tos1 = _ram_ext_R0_data[11:8];
  assign io_deq_bits_ticket = _ram_ext_R0_data[7:0];
endmodule

