// Generated by CIRCT firtool-1.139.0
module Queue1_AguIcacheReq(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_addr,
  input  [7:0]  io_enq_bits_req_id,
  input  [1:0]  io_enq_bits_cacop_op,
  input         io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_addr,
  output [7:0]  io_deq_bits_req_id,
  output [1:0]  io_deq_bits_cacop_op
);

  reg [41:0] ram;
  reg        maybe_full;
  always @(posedge clock) begin
    automatic logic do_enq;
    do_enq = ~maybe_full & io_enq_valid;
    if (reset)
      maybe_full <= 1'h0;
    else if (do_enq != (io_deq_ready & maybe_full))
      maybe_full <= do_enq;
    if (do_enq)
      ram <= {io_enq_bits_addr, io_enq_bits_req_id, io_enq_bits_cacop_op};
  end // always @(posedge)
  assign io_enq_ready = ~maybe_full;
  assign io_deq_valid = maybe_full;
  assign io_deq_bits_addr = ram[41:10];
  assign io_deq_bits_req_id = ram[9:2];
  assign io_deq_bits_cacop_op = ram[1:0];
endmodule

