// Generated by CIRCT firtool-1.139.0
// VCS coverage exclude_file
module ram_16x141(
  input  [3:0]   R0_addr,
  input          R0_en,
                 R0_clk,
  output [140:0] R0_data,
  input  [3:0]   W0_addr,
  input          W0_en,
                 W0_clk,
  input  [140:0] W0_data
);

  reg [140:0] Memory[0:15];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 141'bx;
endmodule

