// Generated by CIRCT firtool-1.139.0
module SramToAxiBridge(
  input          clock,
                 reset,
                 io_inst_cache_rd_req,
  input  [3:0]   io_inst_cache_rd_id,
  input  [2:0]   io_inst_cache_rd_type,
  input  [31:0]  io_inst_cache_rd_addr,
  output         io_inst_cache_rd_rdy,
                 io_inst_cache_ret_valid,
  output [3:0]   io_inst_cache_ret_id,
  output         io_inst_cache_ret_last,
  output [31:0]  io_inst_cache_ret_data,
  input          io_data_cache_rd_req,
  input  [3:0]   io_data_cache_rd_id,
  input  [2:0]   io_data_cache_rd_type,
  input  [31:0]  io_data_cache_rd_addr,
  output         io_data_cache_rd_rdy,
                 io_data_cache_ret_valid,
  output [3:0]   io_data_cache_ret_id,
  output         io_data_cache_ret_last,
  output [31:0]  io_data_cache_ret_data,
  input          io_data_cache_wr_req,
  input  [2:0]   io_data_cache_wr_type,
  input  [31:0]  io_data_cache_wr_addr,
  input  [3:0]   io_data_cache_wr_wstrb,
  input  [255:0] io_data_cache_wr_data,
  output         io_data_cache_wr_rdy,
  output [3:0]   io_axi_arid,
  output [31:0]  io_axi_araddr,
  output [7:0]   io_axi_arlen,
  output         io_axi_arvalid,
  input          io_axi_arready,
  input  [31:0]  io_axi_rdata,
  input          io_axi_rlast,
                 io_axi_rvalid,
  output [31:0]  io_axi_awaddr,
  output [7:0]   io_axi_awlen,
  output         io_axi_awvalid,
  input          io_axi_awready,
  output [31:0]  io_axi_wdata,
  output [3:0]   io_axi_wstrb,
  output         io_axi_wlast,
                 io_axi_wvalid,
  input          io_axi_wready,
                 io_axi_bvalid
);

  wire             _id_queue_io_deq_valid;
  wire [3:0]       _id_queue_io_deq_bits;
  reg  [1:0]       w_state;
  reg              uc_w_pending;
  wire             is_uncached_write_req =
    io_data_cache_wr_req & io_data_cache_wr_type == 3'h2;
  wire             _w_safe_to_fire_T = is_uncached_write_req & uc_w_pending;
  wire             _io_data_cache_wr_rdy_T = w_state == 2'h0;
  reg              ar_state;
  reg  [3:0]       ar_grant_id;
  reg  [31:0]      ar_addr_reg;
  reg  [2:0]       ar_size_reg;
  wire             dcache_read_safe =
    io_data_cache_rd_req & ~(io_data_cache_rd_type == 3'h2 & uc_w_pending);
  wire [3:0]       real_rid = _id_queue_io_deq_valid ? _id_queue_io_deq_bits : 4'h0;
  wire [3:0]       io_data_cache_ret_id_0 = {1'h0, real_rid[2:0]};
  reg  [31:0]      aw_addr_reg;
  reg  [2:0]       aw_size_reg;
  reg  [2:0]       w_beat_cnt;
  reg  [255:0]     w_data_reg;
  reg  [3:0]       w_strb_reg;
  wire             is_burst_write = aw_size_reg == 3'h4;
  wire             _io_axi_wvalid_T = w_state == 2'h1;
  wire             io_axi_awvalid_0 = _io_axi_wvalid_T | w_state == 2'h2;
  wire             io_axi_wvalid_0 = _io_axi_wvalid_T | (&w_state);
  wire [7:0][31:0] _GEN =
    {{w_data_reg[255:224]},
     {w_data_reg[223:192]},
     {w_data_reg[191:160]},
     {w_data_reg[159:128]},
     {w_data_reg[127:96]},
     {w_data_reg[95:64]},
     {w_data_reg[63:32]},
     {w_data_reg[31:0]}};
  wire             io_axi_wlast_0 = ~is_burst_write | (&w_beat_cnt);
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      w_state <= 2'h0;
      uc_w_pending <= 1'h0;
      ar_state <= 1'h0;
      ar_grant_id <= 4'h0;
      ar_addr_reg <= 32'h0;
      ar_size_reg <= 3'h0;
      aw_addr_reg <= 32'h0;
      aw_size_reg <= 3'h0;
      w_beat_cnt <= 3'h0;
      w_data_reg <= 256'h0;
      w_strb_reg <= 4'h0;
    end
    else begin
      automatic logic ar_fire;
      automatic logic w_fire;
      automatic logic _GEN_0;
      automatic logic _GEN_1;
      ar_fire = ~ar_state & (dcache_read_safe | io_inst_cache_rd_req);
      w_fire = io_axi_wready & io_axi_wvalid_0;
      _GEN_0 = io_data_cache_wr_req & ~_w_safe_to_fire_T;
      _GEN_1 = _io_data_cache_wr_rdy_T & _GEN_0;
      if (_io_data_cache_wr_rdy_T) begin
        if (_GEN_0)
          w_state <= 2'h1;
      end
      else begin
        automatic logic aw_fire;
        automatic logic w_finish;
        aw_fire = io_axi_awready & io_axi_awvalid_0;
        w_finish = w_fire & io_axi_wlast_0;
        if (w_state == 2'h1) begin
          if (aw_fire & w_finish)
            w_state <= 2'h0;
          else if (aw_fire)
            w_state <= 2'h3;
          else if (w_finish)
            w_state <= 2'h2;
        end
        else if (w_state == 2'h2 ? aw_fire : (&w_state) & w_finish)
          w_state <= 2'h0;
      end
      uc_w_pending <=
        _io_data_cache_wr_rdy_T & is_uncached_write_req & ~_w_safe_to_fire_T
        | ~io_axi_bvalid & uc_w_pending;
      ar_state <= ar_fire | ~(ar_state & io_axi_arready) & ar_state;
      if (ar_fire) begin
        ar_grant_id <=
          dcache_read_safe
            ? {1'h1, io_data_cache_rd_id[2:0]}
            : {1'h0, io_inst_cache_rd_id[2:0]};
        ar_addr_reg <= dcache_read_safe ? io_data_cache_rd_addr : io_inst_cache_rd_addr;
        ar_size_reg <= dcache_read_safe ? io_data_cache_rd_type : io_inst_cache_rd_type;
      end
      if (_GEN_1) begin
        aw_addr_reg <= io_data_cache_wr_addr;
        aw_size_reg <= io_data_cache_wr_type;
        w_data_reg <= io_data_cache_wr_data;
        w_strb_reg <= io_data_cache_wr_wstrb;
      end
      if (w_fire & ~io_axi_wlast_0)
        w_beat_cnt <= w_beat_cnt + 3'h1;
      else if (_GEN_1)
        w_beat_cnt <= 3'h0;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        w_state = 2'h0;
        uc_w_pending = 1'h0;
        ar_state = 1'h0;
        ar_grant_id = 4'h0;
        ar_addr_reg = 32'h0;
        ar_size_reg = 3'h0;
        aw_addr_reg = 32'h0;
        aw_size_reg = 3'h0;
        w_beat_cnt = 3'h0;
        w_data_reg = 256'h0;
        w_strb_reg = 4'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue16_UInt4 id_queue (
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (ar_state & io_axi_arready),
    .io_enq_bits  (ar_grant_id),
    .io_deq_ready (io_axi_rvalid & io_axi_rlast),
    .io_deq_valid (_id_queue_io_deq_valid),
    .io_deq_bits  (_id_queue_io_deq_bits)
  );
  assign io_inst_cache_rd_rdy = ~ar_state & io_inst_cache_rd_req & ~dcache_read_safe;
  assign io_inst_cache_ret_valid = io_axi_rvalid & ~(real_rid[3]);
  assign io_inst_cache_ret_id = io_data_cache_ret_id_0;
  assign io_inst_cache_ret_last = io_axi_rlast;
  assign io_inst_cache_ret_data = io_axi_rdata;
  assign io_data_cache_rd_rdy = ~ar_state & dcache_read_safe;
  assign io_data_cache_ret_valid = io_axi_rvalid & real_rid[3];
  assign io_data_cache_ret_id = io_data_cache_ret_id_0;
  assign io_data_cache_ret_last = io_axi_rlast;
  assign io_data_cache_ret_data = io_axi_rdata;
  assign io_data_cache_wr_rdy = _io_data_cache_wr_rdy_T & ~_w_safe_to_fire_T;
  assign io_axi_arid = ar_grant_id;
  assign io_axi_araddr = ar_addr_reg;
  assign io_axi_arlen = {5'h0, {3{ar_size_reg == 3'h4}}};
  assign io_axi_arvalid = ar_state;
  assign io_axi_awaddr = aw_addr_reg;
  assign io_axi_awlen = {5'h0, {3{is_burst_write}}};
  assign io_axi_awvalid = io_axi_awvalid_0;
  assign io_axi_wdata = _GEN[w_beat_cnt];
  assign io_axi_wstrb = is_burst_write ? 4'hF : w_strb_reg;
  assign io_axi_wlast = io_axi_wlast_0;
  assign io_axi_wvalid = io_axi_wvalid_0;
endmodule

