// Generated by CIRCT firtool-1.139.0
module StableCounter(
  input         clock,
                reset,
  output [63:0] io_timer_out
);

  reg [63:0] counter;
  always @(posedge clock) begin
    if (reset)
      counter <= 64'h0;
    else
      counter <= counter + 64'h1;
  end // always @(posedge)
  assign io_timer_out = counter;
endmodule

