// Generated by CIRCT firtool-1.139.0
module StableCounter(
  input         clock,
                reset,
  output [63:0] io_timer_out
);

  reg [63:0] counter;
  always @(posedge clock or posedge reset) begin
    if (reset)
      counter <= 64'h0;
    else
      counter <= counter + 64'h1;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset)
        counter = 64'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_timer_out = counter;
endmodule

