// Generated by CIRCT firtool-1.139.0
module StageID(
  input         io_in_valid0,
  input  [31:0] io_in_inst0_pc,
                io_in_inst0_inst,
                io_in_inst0_aux_data,
  input         io_in_inst0_hasException,
  input  [5:0]  io_in_inst0_ecode,
  input  [8:0]  io_in_inst0_esubcode,
  input         io_in_inst0_pred_taken,
  input  [31:0] io_in_inst0_pred_target,
  input  [1:0]  io_in_inst0_bpu_type,
  input  [9:0]  io_in_inst0_ghr,
  input  [3:0]  io_in_inst0_ras_tos,
  input         io_in_valid1,
  input  [31:0] io_in_inst1_pc,
                io_in_inst1_inst,
                io_in_inst1_aux_data,
  input         io_in_inst1_hasException,
  input  [5:0]  io_in_inst1_ecode,
  input  [8:0]  io_in_inst1_esubcode,
  input         io_in_inst1_pred_taken,
  input  [31:0] io_in_inst1_pred_target,
  input  [1:0]  io_in_inst1_bpu_type,
  input  [9:0]  io_in_inst1_ghr,
  input  [3:0]  io_in_inst1_ras_tos,
  output [1:0]  io_in_pop,
  input         io_out0_ready,
  output        io_out0_valid,
  output [31:0] io_out0_bits_pc,
                io_out0_bits_inst,
  output [12:0] io_out0_bits_aluOp,
  output [6:0]  io_out0_bits_mduOp,
  output [8:0]  io_out0_bits_brType,
  output [31:0] io_out0_bits_imm,
  output        io_out0_bits_src1IsPC,
                io_out0_bits_src2IsImm,
                io_out0_bits_src2IsFour,
  output [4:0]  io_out0_bits_src1_addr,
                io_out0_bits_src2_addr,
  output        io_out0_bits_resFromMulDiv,
                io_out0_bits_memWe,
  output [7:0]  io_out0_bits_lsOp,
  output        io_out0_bits_resFromMem,
                io_out0_bits_regWriteEn,
  output [4:0]  io_out0_bits_destReg,
  output [31:0] io_out0_bits_aux_data,
  output        io_out0_bits_hasException,
  output [5:0]  io_out0_bits_ecode,
  output [8:0]  io_out0_bits_esubcode,
  output        io_out0_bits_isCsr,
                io_out0_bits_csrWe,
  output [13:0] io_out0_bits_csrNum,
  output        io_out0_bits_inst_ertn,
                io_out0_bits_rdtimel,
                io_out0_bits_rdtimeh,
  output [4:0]  io_out0_bits_tlbOp,
                io_out0_bits_invtlb_op,
  output        io_out0_bits_is_refetch,
                io_out0_bits_is_cacop,
  output [4:0]  io_out0_bits_cacop_op,
  output        io_out0_bits_src1_read,
                io_out0_bits_src2_read,
                io_out0_bits_is_branch,
                io_out0_bits_pred_taken,
  output [31:0] io_out0_bits_pred_target,
  output [1:0]  io_out0_bits_bpu_type,
  output [9:0]  io_out0_bits_ghr,
  output [3:0]  io_out0_bits_ras_tos,
  input         io_out1_ready,
  output        io_out1_valid,
  output [31:0] io_out1_bits_pc,
                io_out1_bits_inst,
  output [12:0] io_out1_bits_aluOp,
  output [6:0]  io_out1_bits_mduOp,
  output [8:0]  io_out1_bits_brType,
  output [31:0] io_out1_bits_imm,
  output        io_out1_bits_src1IsPC,
                io_out1_bits_src2IsImm,
                io_out1_bits_src2IsFour,
  output [4:0]  io_out1_bits_src1_addr,
                io_out1_bits_src2_addr,
  output        io_out1_bits_resFromMulDiv,
                io_out1_bits_memWe,
  output [7:0]  io_out1_bits_lsOp,
  output        io_out1_bits_resFromMem,
                io_out1_bits_regWriteEn,
  output [4:0]  io_out1_bits_destReg,
  output [31:0] io_out1_bits_aux_data,
  output        io_out1_bits_hasException,
  output [5:0]  io_out1_bits_ecode,
  output [8:0]  io_out1_bits_esubcode,
  output        io_out1_bits_isCsr,
                io_out1_bits_csrWe,
  output [13:0] io_out1_bits_csrNum,
  output        io_out1_bits_inst_ertn,
                io_out1_bits_rdtimel,
                io_out1_bits_rdtimeh,
  output [4:0]  io_out1_bits_tlbOp,
                io_out1_bits_invtlb_op,
  output        io_out1_bits_is_refetch,
                io_out1_bits_is_cacop,
  output [4:0]  io_out1_bits_cacop_op,
  output        io_out1_bits_src1_read,
                io_out1_bits_src2_read,
                io_out1_bits_is_branch,
                io_out1_bits_pred_taken,
  output [31:0] io_out1_bits_pred_target,
  output [1:0]  io_out1_bits_bpu_type,
  output [9:0]  io_out1_bits_ghr,
  output [3:0]  io_out1_bits_ras_tos,
  input         io_flush
);

  wire       _dec1_io_out_hasException;
  wire [5:0] _dec1_io_out_ecode;
  wire       _dec1_io_out_isCsr;
  wire       _dec1_io_out_inst_ertn;
  wire [4:0] _dec1_io_out_tlbOp;
  wire       _dec1_io_out_is_cacop;
  wire       _dec0_io_out_hasException;
  wire [5:0] _dec0_io_out_ecode;
  wire       _dec0_io_out_isCsr;
  wire       _dec0_io_out_inst_ertn;
  wire [4:0] _dec0_io_out_tlbOp;
  wire       _dec0_io_out_is_cacop;
  wire       d0_is_branch =
    io_in_inst0_inst[31:27] == 5'hB | io_in_inst0_inst[31:28] == 4'h6
    | io_in_inst0_inst[31:26] == 6'h14 | io_in_inst0_inst[31:26] == 6'h15
    | io_in_inst0_inst[31:26] == 6'h13;
  wire       d1_is_branch =
    io_in_inst1_inst[31:27] == 5'hB | io_in_inst1_inst[31:28] == 4'h6
    | io_in_inst1_inst[31:26] == 6'h14 | io_in_inst1_inst[31:26] == 6'h15
    | io_in_inst1_inst[31:26] == 6'h13;
  wire       real_valid0 = io_in_valid0 & ~io_flush;
  wire       real_valid1 =
    io_in_valid1 & ~io_flush
    & ~((|{_dec0_io_out_isCsr | _dec0_io_out_inst_ertn, _dec0_io_out_tlbOp})
        | _dec0_io_out_is_cacop)
    & ~((|{_dec1_io_out_isCsr | _dec1_io_out_inst_ertn, _dec1_io_out_tlbOp})
        | _dec1_io_out_is_cacop);
  wire       pop0 = real_valid0 & io_out0_ready;
  Decoder dec0 (
    .io_inst              (io_in_inst0_inst),
    .io_out_aluOp         (io_out0_bits_aluOp),
    .io_out_lsOp          (io_out0_bits_lsOp),
    .io_out_mduOp         (io_out0_bits_mduOp),
    .io_out_brType        (io_out0_bits_brType),
    .io_out_imm           (io_out0_bits_imm),
    .io_out_src1IsPC      (io_out0_bits_src1IsPC),
    .io_out_src2IsImm     (io_out0_bits_src2IsImm),
    .io_out_src2IsFour    (io_out0_bits_src2IsFour),
    .io_out_destReg       (io_out0_bits_destReg),
    .io_out_regWe         (io_out0_bits_regWriteEn),
    .io_out_memWe         (io_out0_bits_memWe),
    .io_out_resFromMem    (io_out0_bits_resFromMem),
    .io_out_resFromMulDiv (io_out0_bits_resFromMulDiv),
    .io_out_hasException  (_dec0_io_out_hasException),
    .io_out_ecode         (_dec0_io_out_ecode),
    .io_out_isCsr         (_dec0_io_out_isCsr),
    .io_out_csrWe         (io_out0_bits_csrWe),
    .io_out_csrNum        (io_out0_bits_csrNum),
    .io_out_inst_ertn     (_dec0_io_out_inst_ertn),
    .io_out_rdtimel       (io_out0_bits_rdtimel),
    .io_out_rdtimeh       (io_out0_bits_rdtimeh),
    .io_out_src1_read     (io_out0_bits_src1_read),
    .io_out_src2_read     (io_out0_bits_src2_read),
    .io_out_tlbOp         (_dec0_io_out_tlbOp),
    .io_out_invtlb_op     (io_out0_bits_invtlb_op),
    .io_out_is_refetch    (io_out0_bits_is_refetch),
    .io_out_is_cacop      (_dec0_io_out_is_cacop),
    .io_out_cacop_op      (io_out0_bits_cacop_op)
  );
  Decoder dec1 (
    .io_inst              (io_in_inst1_inst),
    .io_out_aluOp         (io_out1_bits_aluOp),
    .io_out_lsOp          (io_out1_bits_lsOp),
    .io_out_mduOp         (io_out1_bits_mduOp),
    .io_out_brType        (io_out1_bits_brType),
    .io_out_imm           (io_out1_bits_imm),
    .io_out_src1IsPC      (io_out1_bits_src1IsPC),
    .io_out_src2IsImm     (io_out1_bits_src2IsImm),
    .io_out_src2IsFour    (io_out1_bits_src2IsFour),
    .io_out_destReg       (io_out1_bits_destReg),
    .io_out_regWe         (io_out1_bits_regWriteEn),
    .io_out_memWe         (io_out1_bits_memWe),
    .io_out_resFromMem    (io_out1_bits_resFromMem),
    .io_out_resFromMulDiv (io_out1_bits_resFromMulDiv),
    .io_out_hasException  (_dec1_io_out_hasException),
    .io_out_ecode         (_dec1_io_out_ecode),
    .io_out_isCsr         (_dec1_io_out_isCsr),
    .io_out_csrWe         (io_out1_bits_csrWe),
    .io_out_csrNum        (io_out1_bits_csrNum),
    .io_out_inst_ertn     (_dec1_io_out_inst_ertn),
    .io_out_rdtimel       (io_out1_bits_rdtimel),
    .io_out_rdtimeh       (io_out1_bits_rdtimeh),
    .io_out_src1_read     (io_out1_bits_src1_read),
    .io_out_src2_read     (io_out1_bits_src2_read),
    .io_out_tlbOp         (_dec1_io_out_tlbOp),
    .io_out_invtlb_op     (io_out1_bits_invtlb_op),
    .io_out_is_refetch    (io_out1_bits_is_refetch),
    .io_out_is_cacop      (_dec1_io_out_is_cacop),
    .io_out_cacop_op      (io_out1_bits_cacop_op)
  );
  assign io_in_pop = pop0 & real_valid1 & io_out1_ready ? 2'h2 : {1'h0, pop0};
  assign io_out0_valid = real_valid0;
  assign io_out0_bits_pc = io_in_inst0_pc;
  assign io_out0_bits_inst = io_in_inst0_inst;
  assign io_out0_bits_src1_addr = io_in_inst0_inst[9:5];
  assign io_out0_bits_src2_addr =
    io_in_inst0_inst[31:26] == 6'hA & io_in_inst0_inst[24] | d0_is_branch
    | io_in_inst0_inst[31:24] == 8'h4 & (|(io_in_inst0_inst[9:5]))
      ? io_in_inst0_inst[4:0]
      : io_in_inst0_inst[14:10];
  assign io_out0_bits_aux_data = io_in_inst0_aux_data;
  assign io_out0_bits_hasException = io_in_inst0_hasException | _dec0_io_out_hasException;
  assign io_out0_bits_ecode =
    io_in_inst0_hasException ? io_in_inst0_ecode : _dec0_io_out_ecode;
  assign io_out0_bits_esubcode = io_in_inst0_esubcode;
  assign io_out0_bits_isCsr = _dec0_io_out_isCsr;
  assign io_out0_bits_inst_ertn = _dec0_io_out_inst_ertn;
  assign io_out0_bits_tlbOp = _dec0_io_out_tlbOp;
  assign io_out0_bits_is_cacop = _dec0_io_out_is_cacop;
  assign io_out0_bits_is_branch = d0_is_branch;
  assign io_out0_bits_pred_taken = io_in_inst0_pred_taken;
  assign io_out0_bits_pred_target = io_in_inst0_pred_target;
  assign io_out0_bits_bpu_type = io_in_inst0_bpu_type;
  assign io_out0_bits_ghr = io_in_inst0_ghr;
  assign io_out0_bits_ras_tos = io_in_inst0_ras_tos;
  assign io_out1_valid = real_valid1;
  assign io_out1_bits_pc = io_in_inst1_pc;
  assign io_out1_bits_inst = io_in_inst1_inst;
  assign io_out1_bits_src1_addr = io_in_inst1_inst[9:5];
  assign io_out1_bits_src2_addr =
    io_in_inst1_inst[31:26] == 6'hA & io_in_inst1_inst[24] | d1_is_branch
    | io_in_inst1_inst[31:24] == 8'h4 & (|(io_in_inst1_inst[9:5]))
      ? io_in_inst1_inst[4:0]
      : io_in_inst1_inst[14:10];
  assign io_out1_bits_aux_data = io_in_inst1_aux_data;
  assign io_out1_bits_hasException = io_in_inst1_hasException | _dec1_io_out_hasException;
  assign io_out1_bits_ecode =
    io_in_inst1_hasException ? io_in_inst1_ecode : _dec1_io_out_ecode;
  assign io_out1_bits_esubcode = io_in_inst1_esubcode;
  assign io_out1_bits_isCsr = _dec1_io_out_isCsr;
  assign io_out1_bits_inst_ertn = _dec1_io_out_inst_ertn;
  assign io_out1_bits_tlbOp = _dec1_io_out_tlbOp;
  assign io_out1_bits_is_cacop = _dec1_io_out_is_cacop;
  assign io_out1_bits_is_branch = d1_is_branch;
  assign io_out1_bits_pred_taken = io_in_inst1_pred_taken;
  assign io_out1_bits_pred_target = io_in_inst1_pred_target;
  assign io_out1_bits_bpu_type = io_in_inst1_bpu_type;
  assign io_out1_bits_ghr = io_in_inst1_ghr;
  assign io_out1_bits_ras_tos = io_in_inst1_ras_tos;
endmodule

