// Generated by CIRCT firtool-1.139.0
`ifndef layers_core_top_Verification_Cover
  `define layers_core_top_Verification_Cover
  `include "layers-core_top-Verification.sv"
`endif // not def layers_core_top_Verification_Cover
