// Generated by CIRCT firtool-1.139.0
`ifndef layers_mycpu_top_Verification_Assume
  `define layers_mycpu_top_Verification_Assume
  `include "layers-mycpu_top-Verification.sv"
`endif // not def layers_mycpu_top_Verification_Assume
